//go:build go1.22

// Package reference provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package reference

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
)

// Defines values for EntityCategory.
const (
	EntityCategoryAsset       EntityCategory = "asset"
	EntityCategoryExecution   EntityCategory = "execution"
	EntityCategoryIdentity    EntityCategory = "identity"
	EntityCategoryNetwork     EntityCategory = "network"
	EntityCategoryOther       EntityCategory = "other"
	EntityCategoryPersistence EntityCategory = "persistence"
)

// Valid indicates whether the value is a known member of the EntityCategory enum.
func (e EntityCategory) Valid() bool {
	switch e {
	case EntityCategoryAsset:
		return true
	case EntityCategoryExecution:
		return true
	case EntityCategoryIdentity:
		return true
	case EntityCategoryNetwork:
		return true
	case EntityCategoryOther:
		return true
	case EntityCategoryPersistence:
		return true
	default:
		return false
	}
}

// Defines values for ErrorResponseErrorCode.
const (
	ErrorResponseErrorCodeConflict          ErrorResponseErrorCode = "conflict"
	ErrorResponseErrorCodeForbidden         ErrorResponseErrorCode = "forbidden"
	ErrorResponseErrorCodeInternal          ErrorResponseErrorCode = "internal"
	ErrorResponseErrorCodeNotFound          ErrorResponseErrorCode = "not_found"
	ErrorResponseErrorCodeNotImplemented    ErrorResponseErrorCode = "not_implemented"
	ErrorResponseErrorCodeSourceUnavailable ErrorResponseErrorCode = "source_unavailable"
	ErrorResponseErrorCodeUnauthorized      ErrorResponseErrorCode = "unauthorized"
	ErrorResponseErrorCodeValidation        ErrorResponseErrorCode = "validation"
)

// Valid indicates whether the value is a known member of the ErrorResponseErrorCode enum.
func (e ErrorResponseErrorCode) Valid() bool {
	switch e {
	case ErrorResponseErrorCodeConflict:
		return true
	case ErrorResponseErrorCodeForbidden:
		return true
	case ErrorResponseErrorCodeInternal:
		return true
	case ErrorResponseErrorCodeNotFound:
		return true
	case ErrorResponseErrorCodeNotImplemented:
		return true
	case ErrorResponseErrorCodeSourceUnavailable:
		return true
	case ErrorResponseErrorCodeUnauthorized:
		return true
	case ErrorResponseErrorCodeValidation:
		return true
	default:
		return false
	}
}

// Defines values for NodeType.
const (
	Entity NodeType = "entity"
	Event  NodeType = "event"
)

// Valid indicates whether the value is a known member of the NodeType enum.
func (e NodeType) Valid() bool {
	switch e {
	case Entity:
		return true
	case Event:
		return true
	default:
		return false
	}
}

// Defines values for SourceKind.
const (
	SourceKindEdr     SourceKind = "edr"
	SourceKindInfra   SourceKind = "infra"
	SourceKindNdr     SourceKind = "ndr"
	SourceKindOther   SourceKind = "other"
	SourceKindSandbox SourceKind = "sandbox"
	SourceKindSiem    SourceKind = "siem"
)

// Valid indicates whether the value is a known member of the SourceKind enum.
func (e SourceKind) Valid() bool {
	switch e {
	case SourceKindEdr:
		return true
	case SourceKindInfra:
		return true
	case SourceKindNdr:
		return true
	case SourceKindOther:
		return true
	case SourceKindSandbox:
		return true
	case SourceKindSiem:
		return true
	default:
		return false
	}
}

// EntityCategory Family of entity types, coarse enough to stay stable as new types are added.
type EntityCategory string

// EntityType A kind of thing an incident revolves around. The core set is fixed in code; anything peripheral is a dictionary row, which is why the client must read this rather than hardcode the list.
type EntityType struct {
	// Category Broad family the type belongs to. Lets the graph colour related kinds alike without knowing every code.
	Category EntityCategory `json:"category"`

	// Code What `type_code` on an entity or a graph node holds — host, user, account, email, process, ip, domain, url, file_hash.
	Code string `json:"code"`

	// Title Human-readable name for the UI.
	Title string `json:"title"`
}

// ErrorResponse Body of every non-2xx response. Clients branch on `code`, not on the HTTP status: the status says what happened at the protocol level, the code says what happened in the domain.
type ErrorResponse struct {
	// Error The failure itself. Never carries internal details of a 500.
	Error struct {
		// Code Machine-readable reason, stable across releases. `validation` covers both a malformed body (400) and a well-formed but invalid one (422). `not_implemented` means the operation exists in the contract but has no implementation yet — a client can hide the control instead of showing an error.
		Code ErrorResponseErrorCode `json:"code"`

		// Details Extra context tied to the code. Version conflicts list the clashing ids in `conflicts`; validation failures name the field.
		Details *map[string]interface{} `json:"details,omitempty"`

		// Message Human-readable explanation, safe to show. For an internal error it is deliberately generic — the real cause goes to the log.
		Message string `json:"message"`
	} `json:"error"`
}

// ErrorResponseErrorCode Machine-readable reason, stable across releases. `validation` covers both a malformed body (400) and a well-formed but invalid one (422). `not_implemented` means the operation exists in the contract but has no implementation yet — a client can hide the control instead of showing an error.
type ErrorResponseErrorCode string

// NodeType What a graph node stands for. An entity node is a host, account, process, address or hash; an event node is a source record promoted onto the graph.
type NodeType string

// Reference The full set of dictionaries, in one request.
type Reference struct {
	// EntityTypes Kinds of entity that can appear as a node.
	EntityTypes []EntityType `json:"entity_types"`

	// RelationTypes Relations an edge can assert between two nodes.
	RelationTypes []RelationType `json:"relation_types"`

	// Sources Security tools events can be pulled from. Disabled ones are omitted.
	Sources []Source `json:"sources"`
}

// RelationType A relation an edge may assert. The endpoint kinds are what make this more than a label: they say which pairs of nodes the relation is legal between, so the client can offer only the relations that fit the two nodes an analyst selected — and the server rejects the rest anyway.
type RelationType struct {
	// Code What `relation_code` on an edge holds — parent_process, logged_in, connected_to, executed, resolved_to, same_host, subevent_of, followed_by.
	Code string `json:"code"`

	// Directed Whether the order of the endpoints carries meaning. Undirected relations are drawn without an arrowhead and read the same either way.
	Directed bool `json:"directed"`

	// SourceKind Kind of node the relation may start from.
	SourceKind NodeType `json:"source_kind"`

	// TargetKind Kind of node it may point to.
	TargetKind NodeType `json:"target_kind"`

	// Title Human-readable name, drawn on or beside the edge.
	Title string `json:"title"`
}

// Source A security tool events can be pulled from. Connection settings and credentials are deliberately absent — the client only needs to name a source, never to reach it.
type Source struct {
	// Code What `source_code` holds on an event and in an ingest request.
	Code string `json:"code"`

	// Kind Class of tool. Determines which query fields make sense and how the UI groups sources.
	Kind SourceKind `json:"kind"`

	// Title Human-readable name of the installation, e.g. "MaxPatrol SIEM".
	Title string `json:"title"`
}

// SourceKind Class of security tool the source belongs to.
type SourceKind string

// Forbidden Body of every non-2xx response. Clients branch on `code`, not on the HTTP status: the status says what happened at the protocol level, the code says what happened in the domain.
type Forbidden = ErrorResponse

// Unauthorized Body of every non-2xx response. Clients branch on `code`, not on the HTTP status: the status says what happened at the protocol level, the code says what happened in the domain.
type Unauthorized = ErrorResponse

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetReference Every dictionary the UI needs
	// (GET /reference)
	GetReference(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetReference operation middleware
func (siw *ServerInterfaceWrapper) GetReference(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReference(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/reference", wrapper.GetReference)

	return m
}

type ForbiddenJSONResponse ErrorResponse

type UnauthorizedJSONResponse ErrorResponse

type GetReferenceRequestObject struct {
}

type GetReferenceResponseObject interface {
	VisitGetReferenceResponse(w http.ResponseWriter) error
}

type GetReference200JSONResponse Reference

func (response GetReference200JSONResponse) VisitGetReferenceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReference401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetReference401JSONResponse) VisitGetReferenceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetReference403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetReference403JSONResponse) VisitGetReferenceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetReference Every dictionary the UI needs
	// (GET /reference)
	GetReference(ctx context.Context, request GetReferenceRequestObject) (GetReferenceResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetReference operation middleware
func (sh *strictHandler) GetReference(w http.ResponseWriter, r *http.Request) {
	var request GetReferenceRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReference(ctx, request.(GetReferenceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReference")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReferenceResponseObject); ok {
		if err := validResponse.VisitGetReferenceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
