//go:build go1.22

// Package graph provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package graph

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for EdgeStatus.
const (
	Confirmed EdgeStatus = "confirmed"
	Proposed  EdgeStatus = "proposed"
	Rejected  EdgeStatus = "rejected"
)

// Valid indicates whether the value is a known member of the EdgeStatus enum.
func (e EdgeStatus) Valid() bool {
	switch e {
	case Confirmed:
		return true
	case Proposed:
		return true
	case Rejected:
		return true
	default:
		return false
	}
}

// Defines values for ErrorResponseErrorCode.
const (
	ErrorResponseErrorCodeConflict          ErrorResponseErrorCode = "conflict"
	ErrorResponseErrorCodeForbidden         ErrorResponseErrorCode = "forbidden"
	ErrorResponseErrorCodeInternal          ErrorResponseErrorCode = "internal"
	ErrorResponseErrorCodeNotFound          ErrorResponseErrorCode = "not_found"
	ErrorResponseErrorCodeNotImplemented    ErrorResponseErrorCode = "not_implemented"
	ErrorResponseErrorCodeSomUnavailable    ErrorResponseErrorCode = "som_unavailable"
	ErrorResponseErrorCodeSourceUnavailable ErrorResponseErrorCode = "source_unavailable"
	ErrorResponseErrorCodeUnauthorized      ErrorResponseErrorCode = "unauthorized"
	ErrorResponseErrorCodeValidation        ErrorResponseErrorCode = "validation"
)

// Valid indicates whether the value is a known member of the ErrorResponseErrorCode enum.
func (e ErrorResponseErrorCode) Valid() bool {
	switch e {
	case ErrorResponseErrorCodeConflict:
		return true
	case ErrorResponseErrorCodeForbidden:
		return true
	case ErrorResponseErrorCodeInternal:
		return true
	case ErrorResponseErrorCodeNotFound:
		return true
	case ErrorResponseErrorCodeNotImplemented:
		return true
	case ErrorResponseErrorCodeSomUnavailable:
		return true
	case ErrorResponseErrorCodeSourceUnavailable:
		return true
	case ErrorResponseErrorCodeUnauthorized:
		return true
	case ErrorResponseErrorCodeValidation:
		return true
	default:
		return false
	}
}

// Defines values for NodeType.
const (
	Entity NodeType = "entity"
	Event  NodeType = "event"
)

// Valid indicates whether the value is a known member of the NodeType enum.
func (e NodeType) Valid() bool {
	switch e {
	case Entity:
		return true
	case Event:
		return true
	default:
		return false
	}
}

// Defines values for Origin.
const (
	Agent   Origin = "agent"
	Analyst Origin = "analyst"
	Rule    Origin = "rule"
)

// Valid indicates whether the value is a known member of the Origin enum.
func (e Origin) Valid() bool {
	switch e {
	case Agent:
		return true
	case Analyst:
		return true
	case Rule:
		return true
	default:
		return false
	}
}

// Edge defines model for Edge.
type Edge struct {
	Confidence       *float32                `json:"confidence,omitempty"`
	CreatedAt        *time.Time              `json:"created_at,omitempty"`
	EvidenceCount    int                     `json:"evidence_count"`
	EvidenceEventIds *[]openapi_types.UUID   `json:"evidence_event_ids,omitempty"`
	Id               openapi_types.UUID      `json:"id"`
	InvestigationId  openapi_types.UUID      `json:"investigation_id"`
	Metadata         *map[string]interface{} `json:"metadata,omitempty"`
	Origin           Origin                  `json:"origin"`

	// OriginRef subject_id | код правила | id запуска
	OriginRef    *string            `json:"origin_ref,omitempty"`
	RejectReason *string            `json:"reject_reason,omitempty"`
	RelationCode string             `json:"relation_code"`
	SourceNodeId openapi_types.UUID `json:"source_node_id"`
	Status       EdgeStatus         `json:"status"`
	TargetNodeId openapi_types.UUID `json:"target_node_id"`
	UpdatedAt    *time.Time         `json:"updated_at,omitempty"`
	Version      int                `json:"version"`

	// Why Обоснование. Обязательно при origin=agent
	Why *string `json:"why,omitempty"`
}

// EdgeCreate defines model for EdgeCreate.
type EdgeCreate struct {
	Confidence *float32 `json:"confidence,omitempty"`

	// EvidenceEventIds События-основания того же расследования (иначе 422)
	EvidenceEventIds *[]openapi_types.UUID `json:"evidence_event_ids,omitempty"`
	RelationCode     string                `json:"relation_code"`
	SourceNodeId     openapi_types.UUID    `json:"source_node_id"`
	TargetNodeId     openapi_types.UUID    `json:"target_node_id"`
	Why              *string               `json:"why,omitempty"`
}

// EdgeStatus defines model for EdgeStatus.
type EdgeStatus string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		// Code not_implemented — ручка объявлена в контракте, но ещё не реализована.
		// Клиент может отличить её от настоящей поломки сервера и скрыть
		// элемент интерфейса, а не показывать ошибку.
		Code    ErrorResponseErrorCode  `json:"code"`
		Details *map[string]interface{} `json:"details,omitempty"`
		Message string                  `json:"message"`
	} `json:"error"`
}

// ErrorResponseErrorCode not_implemented — ручка объявлена в контракте, но ещё не реализована.
// Клиент может отличить её от настоящей поломки сервера и скрыть
// элемент интерфейса, а не показывать ошибку.
type ErrorResponseErrorCode string

// Graph defines model for Graph.
type Graph struct {
	Edges           []Edge             `json:"edges"`
	IncludeSubtree  *bool              `json:"include_subtree,omitempty"`
	InvestigationId openapi_types.UUID `json:"investigation_id"`
	Nodes           []GraphNode        `json:"nodes"`
}

// GraphNode defines model for GraphNode.
type GraphNode struct {
	// CanonicalKey Ключ для группировки дубликатов при include_subtree
	CanonicalKey    *string             `json:"canonical_key,omitempty"`
	EntityId        *openapi_types.UUID `json:"entity_id,omitempty"`
	EventId         *openapi_types.UUID `json:"event_id,omitempty"`
	Id              openapi_types.UUID  `json:"id"`
	InvestigationId openapi_types.UUID  `json:"investigation_id"`

	// Label display_name сущности или сводка события
	Label    *string  `json:"label,omitempty"`
	NodeType NodeType `json:"node_type"`

	// OccurredAt Только для node_type=event
	OccurredAt *time.Time `json:"occurred_at,omitempty"`
	Origin     Origin     `json:"origin"`

	// TypeCode Тип сущности (иконка узла). Только для node_type=entity
	TypeCode *string `json:"type_code,omitempty"`
}

// NodeType defines model for NodeType.
type NodeType string

// Origin defines model for Origin.
type Origin string

// ReviewRequest Хотя бы одно из полей непусто.
type ReviewRequest struct {
	Confirm *[]struct {
		Id      openapi_types.UUID `json:"id"`
		Version int                `json:"version"`
	} `json:"confirm,omitempty"`
	Reject *[]struct {
		Id      openapi_types.UUID `json:"id"`
		Reason  string             `json:"reason"`
		Version int                `json:"version"`
	} `json:"reject,omitempty"`
}

// ReviewResult defines model for ReviewResult.
type ReviewResult struct {
	Confirmed []openapi_types.UUID `json:"confirmed"`
	Rejected  []openapi_types.UUID `json:"rejected"`
}

// InvestigationId defines model for InvestigationId.
type InvestigationId = openapi_types.UUID

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// ValidationError defines model for ValidationError.
type ValidationError = ErrorResponse

// GetGraphParams defines parameters for GetGraph.
type GetGraphParams struct {
	IncludeSubtree *bool    `form:"include_subtree,omitempty" json:"include_subtree,omitempty"`
	MinConfidence  *float32 `form:"min_confidence,omitempty" json:"min_confidence,omitempty"`

	// Statuses Фильтр статусов рёбер, по умолчанию proposed,confirmed
	Statuses *[]EdgeStatus `form:"statuses,omitempty" json:"statuses,omitempty"`
}

// CreateEdgeJSONRequestBody defines body for CreateEdge for application/json ContentType.
type CreateEdgeJSONRequestBody = EdgeCreate

// ReviewEdgesJSONRequestBody defines body for ReviewEdges for application/json ContentType.
type ReviewEdgesJSONRequestBody = ReviewRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// CreateEdge Создать ребро (аналитик)
	// (POST /investigations/{investigation_id}/edges)
	CreateEdge(w http.ResponseWriter, r *http.Request, investigationId InvestigationId)
	// GetGraph Граф расследования
	// (GET /investigations/{investigation_id}/graph)
	GetGraph(w http.ResponseWriter, r *http.Request, investigationId InvestigationId, params GetGraphParams)
	// ReviewEdges Батч-ревизия proposed-рёбер
	// (POST /investigations/{investigation_id}/review)
	ReviewEdges(w http.ResponseWriter, r *http.Request, investigationId InvestigationId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateEdge operation middleware
func (siw *ServerInterfaceWrapper) CreateEdge(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "investigation_id" -------------
	var investigationId InvestigationId

	err = runtime.BindStyledParameterWithOptions("simple", "investigation_id", r.PathValue("investigation_id"), &investigationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "investigation_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateEdge(w, r, investigationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGraph operation middleware
func (siw *ServerInterfaceWrapper) GetGraph(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "investigation_id" -------------
	var investigationId InvestigationId

	err = runtime.BindStyledParameterWithOptions("simple", "investigation_id", r.PathValue("investigation_id"), &investigationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "investigation_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetGraphParams

	// ------------- Optional query parameter "include_subtree" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "include_subtree", r.URL.Query(), &params.IncludeSubtree, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "include_subtree"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "include_subtree", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "min_confidence" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "min_confidence", r.URL.Query(), &params.MinConfidence, runtime.BindQueryParameterOptions{Type: "number", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "min_confidence"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "min_confidence", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "statuses" -------------

	err = runtime.BindQueryParameterWithOptions("form", false, false, "statuses", r.URL.Query(), &params.Statuses, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "statuses"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "statuses", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGraph(w, r, investigationId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReviewEdges operation middleware
func (siw *ServerInterfaceWrapper) ReviewEdges(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "investigation_id" -------------
	var investigationId InvestigationId

	err = runtime.BindStyledParameterWithOptions("simple", "investigation_id", r.PathValue("investigation_id"), &investigationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "investigation_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReviewEdges(w, r, investigationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/investigations/{investigation_id}/graph", wrapper.GetGraph)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/investigations/{investigation_id}/edges", wrapper.CreateEdge)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/investigations/{investigation_id}/review", wrapper.ReviewEdges)

	return m
}

type ConflictJSONResponse ErrorResponse

type ForbiddenJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type UnauthorizedJSONResponse ErrorResponse

type ValidationErrorJSONResponse ErrorResponse

type CreateEdgeRequestObject struct {
	InvestigationId InvestigationId `json:"investigation_id"`
	Body            *CreateEdgeJSONRequestBody
}

type CreateEdgeResponseObject interface {
	VisitCreateEdgeResponse(w http.ResponseWriter) error
}

type CreateEdge201JSONResponse Edge

func (response CreateEdge201JSONResponse) VisitCreateEdgeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEdge401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateEdge401JSONResponse) VisitCreateEdgeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEdge403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateEdge403JSONResponse) VisitCreateEdgeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEdge404JSONResponse struct{ NotFoundJSONResponse }

func (response CreateEdge404JSONResponse) VisitCreateEdgeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEdge409JSONResponse struct{ ConflictJSONResponse }

func (response CreateEdge409JSONResponse) VisitCreateEdgeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEdge422JSONResponse struct{ ValidationErrorJSONResponse }

func (response CreateEdge422JSONResponse) VisitCreateEdgeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type GetGraphRequestObject struct {
	InvestigationId InvestigationId `json:"investigation_id"`
	Params          GetGraphParams
}

type GetGraphResponseObject interface {
	VisitGetGraphResponse(w http.ResponseWriter) error
}

type GetGraph200JSONResponse Graph

func (response GetGraph200JSONResponse) VisitGetGraphResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetGraph401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetGraph401JSONResponse) VisitGetGraphResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetGraph403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetGraph403JSONResponse) VisitGetGraphResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetGraph404JSONResponse struct{ NotFoundJSONResponse }

func (response GetGraph404JSONResponse) VisitGetGraphResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetGraph422JSONResponse struct{ ValidationErrorJSONResponse }

func (response GetGraph422JSONResponse) VisitGetGraphResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type ReviewEdgesRequestObject struct {
	InvestigationId InvestigationId `json:"investigation_id"`
	Body            *ReviewEdgesJSONRequestBody
}

type ReviewEdgesResponseObject interface {
	VisitReviewEdgesResponse(w http.ResponseWriter) error
}

type ReviewEdges200JSONResponse ReviewResult

func (response ReviewEdges200JSONResponse) VisitReviewEdgesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ReviewEdges401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ReviewEdges401JSONResponse) VisitReviewEdgesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ReviewEdges403JSONResponse struct{ ForbiddenJSONResponse }

func (response ReviewEdges403JSONResponse) VisitReviewEdgesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ReviewEdges404JSONResponse struct{ NotFoundJSONResponse }

func (response ReviewEdges404JSONResponse) VisitReviewEdgesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ReviewEdges409JSONResponse struct{ ConflictJSONResponse }

func (response ReviewEdges409JSONResponse) VisitReviewEdgesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ReviewEdges422JSONResponse struct{ ValidationErrorJSONResponse }

func (response ReviewEdges422JSONResponse) VisitReviewEdgesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// CreateEdge Создать ребро (аналитик)
	// (POST /investigations/{investigation_id}/edges)
	CreateEdge(ctx context.Context, request CreateEdgeRequestObject) (CreateEdgeResponseObject, error)
	// GetGraph Граф расследования
	// (GET /investigations/{investigation_id}/graph)
	GetGraph(ctx context.Context, request GetGraphRequestObject) (GetGraphResponseObject, error)
	// ReviewEdges Батч-ревизия proposed-рёбер
	// (POST /investigations/{investigation_id}/review)
	ReviewEdges(ctx context.Context, request ReviewEdgesRequestObject) (ReviewEdgesResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreateEdge operation middleware
func (sh *strictHandler) CreateEdge(w http.ResponseWriter, r *http.Request, investigationId InvestigationId) {
	var request CreateEdgeRequestObject

	request.InvestigationId = investigationId

	var body CreateEdgeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateEdge(ctx, request.(CreateEdgeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateEdge")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateEdgeResponseObject); ok {
		if err := validResponse.VisitCreateEdgeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetGraph operation middleware
func (sh *strictHandler) GetGraph(w http.ResponseWriter, r *http.Request, investigationId InvestigationId, params GetGraphParams) {
	var request GetGraphRequestObject

	request.InvestigationId = investigationId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetGraph(ctx, request.(GetGraphRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetGraph")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetGraphResponseObject); ok {
		if err := validResponse.VisitGetGraphResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ReviewEdges operation middleware
func (sh *strictHandler) ReviewEdges(w http.ResponseWriter, r *http.Request, investigationId InvestigationId) {
	var request ReviewEdgesRequestObject

	request.InvestigationId = investigationId

	var body ReviewEdgesJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ReviewEdges(ctx, request.(ReviewEdgesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReviewEdges")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReviewEdgesResponseObject); ok {
		if err := validResponse.VisitReviewEdgesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
