// Package spec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package spec

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7L3pkiPHlS74Km6YMWO3GRKFXIpLlvWPVLEo1b1camqRzKSkZTkiHIAzA+4hd49EoWllxqU13dfUczU9",
	"02Zz/033zJjN37qU6qpEitQrAK9wn+San3PcIwKIwJKVWRS3HyQTQER4+HLW73zn406iJ7lWQjnbOf64",
	"k3PDJ8IJA3/dLozVxv9fKmxiZO6kVp3jzgc5/3Uh2LmYWeFYAr9ijp8LxYZGT9hjJZ64M/z8MdND5saC",
	"5UZcSF1YlvOR6LE7KtGpsIyzXFvpb9xlSjvG2a8LYWbsv3/yryzV8NGgkFnKtBJsMGNjrtIe+2AiHZOO",
	"Oc2s48bhc/1jBmIklZJq1Ot0O9KPFu7X6XYUn4jOcQeH1el2bDIWE+7fzs1y/411RqpR5+nTbudOOhJ3",
	"09U3v5sK5eRQCuNfiysm0pGAsfrhJRmXfhTcMTf1Y4cXNIIZkXEn0jiknLtxOSJ/jzOZdrodI35dSCPS",
	"zrEzhagOcajNhLvOcaco4JcNQ1ZOutl2g4afwrA5G2vruowniS6U67Lc6ERY22U8TY2wlmnDxtyO28YO",
	"t7qC0V8I5bYbvP8l45kRPJ2xvMgykTKpnPZfSnUhrJMj7q9uG7K/wcuP+G71UY0jr/4A9qZ/nLCOTbU5",
	"t0yqHrtz4fd6LkUi/OuJC5kKlYhuWCKuUtxiA5FpNbJ+w4snPHHZzO+4LvxAaTeWasQSo60VFjfgQBcq",
	"5WbWMgm1iXr5yXhXTqRbnYKf6SmbcDVj0okJDN4IVxjVYw/HgllhLoRhEz6jj9lQTIXpMiXgc21E2yHO",
	"4HnVMaZiyIvMdY5v9rudCX8iJ8Wkc3zQ939JhX/tx6FL5cRIGBj7+zrd5qyzkeH5GA51j3n5YJkRQ2H8",
	"ejE3lhbll19nWjxtaLMOxFiqlEnXshj+ni+7Bk/9xTbXygqU3VoNM5nAoiRaOaHgf3meZzKBVb/xkfXv",
	"+XHlIf+zEcPOced/ulFqhRv4rb1xxxht7tMj8IH1+XoIOzzRJmXJmKuRSJmVODmCXQhjwzFIMulnxQov",
	"b/wHUyOdYFNdZClLCxyggLP+RFrntzbsda9kxqJ+xpm0URYkmbYi7bHHqXBcZraX0BzYxyyT1lm8PKUT",
	"kmTcjkXK/sYror8Lv/3bXudpt/OONgOZpkK9uum7zbNMGHifwo39FvKzkLJB4dhYZ6llSjOjMz8B8CJO",
	"KO5nkKYFvkq1sLANR4YrB9uS8QQmCl9zGF4M3/N97d7xguLVveb7mtkiGYedQu+SwMu/Zumleuw+CASQ",
	"7NYJnvojeNQ/ZENt6FJaRdgiTGRWTMfCiC6zmmQtjqGcEiMuBM/8lxOaDKXd2dC/Pk7GA12YRDxS/ILL",
	"jA8y8epm5USxIrfOCD5hViSF8fLDaZ2xVKZoFyk7FQYF59IJcFZkQ79xpHI8caDXjXBmBntDcWP0FOYE",
	"LSt8dwsve1aUb4uT8Ej57aeN/HvxCnfFQ+2NR2nZRFor1ajLJjzzIk+kXSae5F4m+pexcuQ3xcBrRlao",
	"c6Wnytuh9FJFZfD4Oj/nmUxhyDCGV/dG90nX59xYOsUXUnsz0Nu8pshEMIxTPeFSoTWmmJzk2lo5yIS3",
	"bF1hmTNcBQuZMy+npFcFfumn0o114Sp2Ay8nLhjmODUXcSL8xDwNqgV0hddmq/rvZLM9yx6pTJ6LaJZ1",
	"o0mccMUGXrJrNYJXG4Oe5PRSXfo/kTIjuIVXUykqT38j6417I7zMRjsuNzoXxklUbjAJ8MbNNoctjCCn",
	"Q6dFIgybcttj94tMWJZwY2aMs6F8IlJ2wbNCsFwYWJNb/gX4yKsnf8ImsFzSj2IKw4iGxX7FrOh3O6rI",
	"SGKg3ibtrIrJwFsZ3U5ihH/bM95gJf1iLFAKwsxNuWX0a//EqPdT7sSekxOxqvy7nbABzsCKX2OI0ezG",
	"pyXSCdtjvxRGoyrN9FSkIGb9TCiezbx7gBZZ+NTPT6+zakxVxhGMbLs6Fi/B/GNTGkyPnWQZGbjeRPRj",
	"s3yyLOb8JoLjwh0fcOutrKE2CawPSH1O+zXhygvMTHDFtH8H7cbCsIRb8ZqFy8EM8xbpFoZV/IAbw2f+",
	"b7nRVgyzW1u/ttuvWOJbOBJLLsFWz5kIx/3Lg9xLUxAoPLtXOVe4devPvkcHaM/mIpFDmTDxxBluu0z0",
	"Rj02HUuvy700G0qRpWzCXTLGnUsj0IOPROL8CLSRIwkylmfZB8PO8a/Wy9gP8PdPP+yuHBgdTnZKFiWX",
	"kx57H3YpGp+2ywoUTihxeuUIzuCZq6fQv4p344ODFXYcnYLXLLMFvAyTKRqu/sVfs8wL2GiHofQwhXrN",
	"Mhm3RY891CMBG9ELbYYjQQNNWjbW07h/JYh8/2oDnpz7E+EFECo2P68tsqZcaSP8IM9QsDa9qPfHQM74",
	"8adMF2BwoefBpl4a4S1AEXPwXPyopl4RTPg5ajD4hR+k4SoZs8KKYZEFe86IXBu35Wgz3Pp+FptGyx3d",
	"MosWv1+ZnBsvYmK8ItOjkUjPpOp6HalgcGdOe/NBJIXzhoQRVmcX9LEXMWcY/LDFAOWVHnbZUKMMPBvM",
	"ek3niAyn4LOtDNi7k/UBQ4TKQohqq5OKG3b7c+LV9wO8pumsCNKFuLus4yr1pqK3h6WYwrlw3IyE2/BO",
	"0rFcS9AeusfeQV1QqFQa3Ajxff3DtElB5hojwfxmE8FDVG7jBBR5ul5ZSscybl30M/1+kIrlxvs63gya",
	"0q9gk8N77qJNyVldffhPiknuDwyYO2ZGz++xB4KMF7QmZrrA8Xm/NBwoPwipRre8iSYtyEmYFMusngiQ",
	"O5kVbIQxBOMFqrEtanY6nq0O7l7GpdrLuBoVfCTYR4X1oget2x57j6uUO21mNS1+jGsonuT+YuHldzKW",
	"SjBbjEZe6eB5I/dJiqk/ylsc66fVUMavOrDMDSGnpbO0shGXpUM8G1GZlIu1YgR92KCC/FG5DcZVk71b",
	"28Ek9Rm3VvjjOxBuKryhNtVlXAJM4t3s0w9y1LwsFSMjwAtIhHFcKjfrsRNvphU8QxUPU28mPMtm4Ufr",
	"rNAVq3Mbc+wOWoRe1/g3qqjTO9xv0cK6mnEGfuayYZZImI4lWwujXxICZYWl+Pel7a4NiuJ+WLyYCkgl",
	"RD64mfXYXWdZKpKMexUnVAqSjJ1LLwvhFfFAQlwluDpdBm8zlVbUwrfwQqj9viUNsbu83uaujVLlP1TF",
	"SBeEh4uBvh6LuxmDL+HQQ8R0BNZ9Z5Nw2FUItJ3rOxdtR+5h6VZG/9T7PV2vNIZFljHDYd+6sReM/jAY",
	"CBSunuyQq2l+hr+zGwsbH2eLPBhCmx2BcDLWu0tdprPUb0PUD3hKg6L1S5NJdV4zHXGCvVVkNUrv+Ki1",
	"ZgXNJwiI1QO5tIplEgtvvmmVTtK0VRY5DW/sV4cmMOR+gtwN3tXS4myUck4znqboca5Itka3k5fOco99",
	"oEQl3AyLAjtlpLTZVbxNpLqLP97fNLXxtdom9R5vCuB8oAQkWyGzlI6aFNWaPQdXME0+CiRtt9456Ug0",
	"SfBKWrjBfOHW+tl+HPLGTrORQNvfX0h545OB9UqFlDRYWWFsO9oka7fpPa8OVgf5jndycYOC6efHAaYb",
	"bI8TNcNMnJ5I5zeHdXwGLwUO1C32mIyVxxhrmfpvo8i0GlQPmavGhkCGvhAGMyTCH3XQSbuZHPfFhbQi",
	"bbQ4djEnLhdCuC/yjCcknKzToIEhiMCmY50JyzOBubOJMKOQzHVjMWmMImzn3cao/1hnaat327t29+sk",
	"SUTumDYU8i1c1cK6HwYSdgF61v7NGIfojkxFb61L8vPVxFp0PcCcDL6G33HsqP8WrPiajGiLHRD2UN2t",
	"2Kjcw7jbztmDONlNbmvQ1itOK/ObTvvxFMrJjHE2LiZed8N0+/MWJlekJMm8oD73a1HV9anIBIQGIGvE",
	"HTvtJGORnHvBrvw2TbIiFelph9nCXMgLYePurMQ4hPJz+Ss4kX5QnW6HwvQCzRccSGUSyt2GsI0mb0Tx",
	"CYS30LBmUiUQTvJToLMLeCNdKMiPOO/4ihRNX1L3ZIGkhX8Sk4rcuR6DJ0qaEZto79E6DWKspvpulSrR",
	"CJ7tTbXJUoCLMJ7nghuQbJxZkXPDnWBGT/0SCTRIrECATpGMG10krrSSCc/OzsWsyYL1bg/sOAyiuRnz",
	"LgQYoLChpRods+GvU4UOLeFYHtx9Ozq4AdLy00fhwxLdYsf84Obr9OlQZqLHHoLwxdQixOji6/tFg/1w",
	"LmYwa+U3Y4iRWQ1WFxxkyDF8pCUEn6VrFDGptHnGZ2eY/19+93f5QGTR0n50t8fe4Vlmo01XmzqUaBy0",
	"4lbxNjAbz6wQDcLkDjeZ9LYleW6qyd+DczLxa6KVreAdWuMrG4fUZE8/AHDIHreU8pNLEXZpmx57dUH2",
	"eP9d4+xe+rZM77vclZNbn0YvsOoR4nKdcDQA6MH5nkqVUkqXxjjlmOe/8Gf48gtxOQV/x8sfxp0zclA4",
	"yrBJ7wRC0ii44ySX/vsn/8o+eBAAIV2mp0qYLhsJnekQrHrHCLHnX8GfobwwXqoe0w0sS+VwiCbQikrx",
	"H7TEB/6jVCltHQhzYOAdUpMgOQrrhxGFhphwmVXgcDLvUqa2ywqTdUFonAEyDnLyifbSVEB0ADKLt1gu",
	"jMzHwvCMAg1edPA09crFVqITXnDamMvlbCJHZkv12hZYK+ehuyRpGxUxbKLb3DS5ZLjB8qzAvQfZ8yeu",
	"kh1kSgi0iT8qIGjljiGfMSm8tUpndUkfQITWUMhTOjbm3lc2Q554ZexF7XSs4fc8Ow9Hb8nZi4pzSzMN",
	"f79qoj0sjxEN1aRgLQ104XoYRvN3asutkmvZJizLm0PmJOfGAfTvhBldjCAGDOlqPYRZS4RyfsdgyoVM",
	"DT97zZFgJeRoPNDGtqycBJgaT8b+3OOBjKZJdPGyWcWg8ooMt2omhg4sVgSKwrzYMaC0rB8q5IO8nLSO",
	"DzJpx37tvM0dvrCFzWOYLHqO9WVcrwrvOsuyZXW4jSQrcamNzi1NG9pGO+iRDTHIn6FUnlVBElebrNos",
	"EuqI3E2Bs2UXXSdJYQDT2LCjPgDtVNvgNuS70RwC9Bad7RJovMaa8hvJsiL3QhQlMvwuh8wJt1ZYO8E8",
	"BaCQGehDqdjQqzp/LCwlUeADP0PknYvkfM2uW3+iI1pCDyGAFiApCgzvJZNn9UxuNjb8FtSrk7ld7Fe6",
	"rOWkwFcRARfEc8IVSWYjMnHBVSKistG5UOAebLGxmtQMjGVJQG7eZo07dvk29b24Tm05MdKmwYd4h09k",
	"BosYJPAs96on0dwAfgTkL5YQzBgIMeE1sxJT/GmpsKteXvBHvBgSbqrNuf8Szi3moXJv2lgHsZhux29i",
	"eBu/3mtcwNa0VDxGQjlhEP025t7xG4ihhoNGuJ6aOXkVHpcXXVu5WE3uVM2ahcSKP/jB8KqACVzF8Wrw",
	"rAh8oI0bUzZMWr9n6e2tUGlbKOfl/CzUvDRprMHXuiL7OYYNwRrCFwWQmiTs3DTm8KVKZcKdNizxk+Rt",
	"a1C5wr6UOdwtrXRc+T1Yq2oCLUZT5DAALwl15Wa5DrFKLyOUww/FZpFyGTN1i1g3GT67hbuDtXS5iDcZ",
	"l9/dmDfN7VZR742R7h67WxUh8fAHjGf9VAF6A6O1IpUuQAx2sRPfF9NGO/GKTmhTCLvi7+4exn7augQP",
	"4ePVaOB5zX1dEw9scUe90eRP2i2vLvAmFf8UgsN1j7RL4D6Q1bNqfBkSZ2CgwUGpxlPH3KRJSG9n0jaq",
	"oVJf7+K5RT2/6sH9xGiesiGq+7jZKnEb9q4g0CsW8SQ604WJFjp554AWDJaRl3AgkxHooykOvwak9jhK",
	"s8eIO63UAVWrh6ia4yoiDzvYhz8rJlzt+VUDM0eB+lh3VpZEB0npYPHFVWwUJjVw/CqKSqdolcHUKq32",
	"Dp48iQUbPXYbtpkNyEKt2GOYVTxdJAV/9vDhPYJ2HtOxBLS89XIIjIsxz3Oh4KQGLLjTic5YJi5E1qVo",
	"RiqaLiEYI057Q+wh1BKs6pEhl5l357EqI2JSKT/vvQSD4B8oUcLKspv9flNCr2mnvYf4rHIhA3w+mK9Q",
	"BAiWvneOeuxxCfx/zBJ9IYxlA+3GtUqBgV+Rvznq9/8WRDRnU5Fle+HLAvS6vw0kCf7m6ODgb3vssdLu",
	"TE7yTHirU6SPyRED9F8uMIKFGXsby3y0glQFFjVxAAbGW+AFMxHjDShtvPsyliRS4AY6q1YFeQ+SRCIs",
	"S9VUr9aDoG9FVV3dTqz9oWQN1Mp1O+VslfC0So0MXVh5bYi/4aI2Gve00JeJqIZQm5OYoQkbtsdC0i8W",
	"uIGsDZlFC9JdYsLscVkEd4uVbxf2qUVJ4K8EAHejGTkR1jZaXUtCBWCEipBClg8FOFdjPY1w0bj/YanI",
	"tE9FJgd+w4hsxkZCCSOTaDcYwTOW8AKgkSJGxDI92lpmheF/2KSGa44oHOtGiXYhmgIFJ2zodzMYz7xe",
	"uNVdX5rMKGroPUwsrvCmD6UdsUJF6SjfOD6HjOyBqMTwoB4OTfMuhPIQl9ISL5WiMdeq/ZDPMTYJeG+F",
	"8jDhOU+km/XYnZhjXE4oene0DO+/ZtmE5zmYF0aDJ7gmCrM+SOeHIxOZc3e1Ubq7ztYKKdF3BqGTOG26",
	"DNe9y6xJuiy1jsqV/UEhlT7hM0qCMjeVFFChxATYZN4gvO5YHeKCXKPB+IuqOuuGN8WiCfeaZRc64YMi",
	"48S0QMbGGQARu4ziGmdWWEzSZHrk/5MKJ5KWzMR2hTEyokKVDUJ99xgYbr4NCPEpt+UZ7LG3YXEQZMko",
	"tORvAE49nMBKSgNC5oJCAX7y5ERUDOKJti4EPv1X20PLL1XtAxNWex1v08Y9SYk1qqitih031RQknZEL",
	"N9WQbQLXvUzU66myFOlEDBHThTNyNN4OuUhRmb8X6dnuvlUEZ4LgAHR91HWTiTch1IXIdI6ZQ6rA6VJV",
	"c+WsovkHv9EhYgtrXZ5KL5dtKE30jgaggb3As4Kb9rqlcrO077byrOXCVARiGdiehkoWvzcyANlrAJbP",
	"tt8+hk8vMcVYSMUzlvNZpiGwXs3Imlhr7XrsP4rcRccA9w6Gn0LoDfdl5k+A1RMBriQSskQEChgjkY1g",
	"TZiinGMytdrcK3/uoBxaujLyhYstxaTLRGq6TPl/STU0fB0sO9J/bFHEVy1S57h/euwBWdrEj+LnaqQh",
	"IFmJG2qa8nUjaSxDuy94Otub8JSAvNpQ2TaMQOeCTOx6/fwSxJdh1VRhlGWnnSnhzU47KBVOOyONdsZY",
	"JOennSuv5wi1GksTXtNY9WNVF+mtFtiJczwZU2l1W62YBhHYYz+VF4IJCcEJI4aWqoLKyaP4PsF5KaQZ",
	"5rvrb5RRLI6mdygxfoU7r8LDEnXBtCFRjdQlDbajFRlqUyBGKRTjI+4dG7jjsvQA9S0vtDtmI4B5uEqE",
	"AXBJ6LgBNCSk0LkDxbZy1i3LAqCuml5utM4akwU/hzonP9V+SIyqQDBD4B2KSjhjmUeIvYclovFta8aj",
	"nip0RGzjyfHHviGQr6fCIECmqpXjZEiVZIWVFzvo6awktCFemf1+f5WyI/evHnMXYed5lTbmJmWJkBkY",
	"y9b7+KAZEp5lNdDtzX6/KYm4hUCkJXUad2yzqCkG9MdqVNcIsQcO5tDw0QQVJGLrsM4DpT+H3UWuh3iS",
	"+8VsDjzp1Wc8yvO1KwMAy11Wprl2pNVkXocSBmO0tKp67Ke6Cu/kRSqdN3zJI6pAMYBTgwPaqnRTQRzr",
	"Yanmgy05BW2L8MBes7sytE2KgGQUnh/veUGlZTbrsUc2QJmrDxrzsjghlwBiBWGlC2SJwexV4DeAChiC",
	"aniNX6h1MI1t9TPGNisVQpfTxK5aO13XvzvtidVnNe2SCX9CpRjVw1gmq9crIwviobVu2e+uWKhKAnfF",
	"46lPNoc7i/YCGSWm2YygZBshQpFRqb0sJu4aIyDTRHkaQxnWc+kN8x47gWDt3wujGQj3sj6RuPsoBIeE",
	"eBfCZCEUUGQZalvxJF8unKvSR6QjYc+I/aJhtIBXqiNtIw9AzGAqMY3MElXtiRH4kcFwYYTbxUpYvB/P",
	"gMkPQTl4PPQAiAuzKhQUc9stb0GRlrMIzF4DzqKX9eeTyp6b3+S2n3Ab05Qh04T5/qZxLJ2KuKdqG6Jx",
	"sMvr0GqObU7FVt2drdOxd5rq3LavWhPKPSgmE25edT6WlAF35WmY5G4G33UDy4N0MTSuUnulKdzqmzdP",
	"atz1IKD5NDiE/mhHrxReJSQsxoVKjUgt5WuwhDKtXmvBdHWanctMD2ZeqQiejLF6AIsryVWxLMbRwcTl",
	"ABSg8MkVBiu/GwHH70Z08KUDfdcUzyOt1x46vNIonHS7VgG8mpDYNYSrtp7Dy0RsrjMus2ug5V2pzncK",
	"qnw3oiTVmu0mSreykrzLnJGTCZqQIEGhPupCKICI5lyJDPG56NEuyXIvwQMjAp/yWXs59pqC/K3O0jVK",
	"su/fWdnJc/q2T0hl01/6UDQdg596U7+ZFsNGTmWw9DQYPGDIdBk6QcBSrNKmImu4rM0vwQrRwKFC+QgI",
	"s8bSbDaUmRPGvnQlPUS0UnFmi4EzonFTIfg2GcssXYbsT4URSyg14DQhAE65TwZaZ4KrS1fQocu1s+pM",
	"W1xVSIqnouRdTkPyGdfTP2jaxVolaTWCu7QS2883bBy/TTaC1hvkOg6cvKf2ffl+oxQ4QbKW4FTAzEGu",
	"QaWYY6iGm0tgGfwV89eYxxxoNw6UjQoD4DujwRFz95qNaZ8KLLwCpyOMzlBXmZvrNSFYMIywJB52He3b",
	"qyjlwa8puA+cMYD+W1sfuvmZm1VX4xNBp7EPVBaZNnOjJ9pVbTiKQwivb2E7lzFE61gmL0TYBFXPeedX",
	"2M6SugSd+bWxWsJk7FxtOxBZwyoBbkqz1Duq1duHuRZhfxOuGGFQgNS0Y20cs+hIRzrPizbMf9wA2wNa",
	"vQQAnG8TXZ8MVZPIRIXJEBRtCOaFYPV2xkuJHgg2DAGPiMsXSv8uXS18tXyeBdGVwzLVpOCWlQylIIiw",
	"Ze4gEE7E70lkP5gtvf/V2PXlTohz06QEahu/0UYHSAYU3Mxy7cbCSiwPlkg2E/Ywgj/GPIdQCqJpAdsa",
	"948XseyuW8V3dPGvyAQBHJ+kr2+tNJRAyMwyPwSQKak2Ohrg4t/ozwfK/tuZACyGHDZT/BuhcfteerNu",
	"TRmdaMwWwoN77D3krRwWWSiCimvSZYYbkRExhVaMM6O1i6H4y5NF60KFHjxLrAjy72NcFbYJeG2jjMOa",
	"UuEfwC8iAY4SIo1ddYDnWk8b1svbiaaJtOBtyDo1G5JhJ/rFiRMjLCu8+YzHWSuxPkre9ETrpEpcuT+X",
	"GE7cWEeKtTYe6tDRqDHfUQ8jLRdtN98ykLucrXcCnMwyNuXIh4jdCpCxppqKKBmFf12IAk90TK1EGLUR",
	"VPgGqJJUA8feFqH+uJZxHiqzvfIiTSJqK7by+iH1p3nDGW3ARldu3JieBg6IgIPGUjgsLSe0RvhzIEBe",
	"Vah7puNZ7+rMpN0hileqHDVVJbjQJSCkfN0YSQT8GE/u3e0yXkuPQdo3MrazB8JFtC723oHjNCYukRjN",
	"MUZeiPRWDYPvRQnxU7tvm0t7m3Wlivs2E16uOqsY0BpK7y+y94sso5OIIPWKbK+UUEHFZv1nFZ1NGFfO",
	"Mm5GRIt6KVs+NxpIz5re5h5+R4GaKcVpQDnE2jtqqnKHSItRko+FkdhooVCUn6aKTqhnA+uh2nfKzw/d",
	"qTGS5A2QnRg5HoQrVje918iDUGCWaX1ucfcS+NwZyUdYTmiIl4xXwKu4gW1M1CFHWKBZhlp4G7bxrmxv",
	"NettHes21j574S2DWkCYoLdC76pU5EJB/R6JmAthUpkA0wEsHsFUQbUCulzp8Bs2Ew4hXt5+qtHHgbpt",
	"rwL7RU1elofA22DvLJucrqKx8OjjZQ5C0F2Wjw23SFzI49CwpNsK5Y0TQni1sGDtSvO9E4F3Sr2vtlvV",
	"n9MFzewwpUkYt9R0LDPRbKviWvt1q/DhOo22LmBsUTwCV3jAIGLbDdwUUIM8pR0UFqEif1Z8A8DBCsHo",
	"LXqVKThbj4DirvZyLTSJBO6LlP9LbgmyFhFtoSPkvNJQVBYk5VYy+xp412GPbUG7TtU30rXTrjd5gRXB",
	"XNZGRo7ykpq8YlDV9n3F1t/oKrbzlisxhY2B6h7+bNBC9XZqDRXW66yx2202mD/9Q24i4JTYoMAUawO8",
	"vaRurjT/BOm45HZtNM2uSJvGw4J+oR9DN1AB02egamNEotS4lgiBXrO9U/VQTHJtuJkdV24fFW9o9qbP",
	"BXVIlfDGZKv5QwYuPjR6S0Tu6OHK+7ToDw4NdLxKQaWARgrEIYXDQAm8RpGjToEyOz7lM6a9MsWC/mvX",
	"+HeVdJJnFc6fHruNKjCo+Iw7b/xdRrtFi3JVj5Gn/q5QIzfuHB/cvLmRtQKevvG8bkZH1b3pnegqlkmY",
	"LkNaUQ9EfXe5K5Zm/WooLDaTNXvFCfxESFuxlq+ZWZkJ5bLZS/Qy2z4wtROp81qx/76Ysson1y8G7kdz",
	"PoiBQIwX3QFpr9Fwvw1G2opd18U6W1I3GLUELcpukwWOai/awbfo1xCWyIAslxyOFtnlZxq+2kIeXauB",
	"e8XG6bbG6LLxWXGJNjbceHXk2DuwWzftt9Y0fZuf+MALnRCOB0JKjLcWLtGTEnAavLSL4ACUFAh+E3oz",
	"E7ZsI0NBbaAPG9EEJyFhy4YZdw6CUUPMPu/lHPgmVCoM2XvbgnzNbNl5IlQJPQs6Ook9aCXVxR4pAblN",
	"HW+9NUQ8G7U2GBK6veRuHGPiFTIJiW538FymPIN4GVpkSH9ZU6GXEC+dp90Vnks/nOZYN8CtIujbvxU1",
	"ZIzNViov2mkU520bFJ+6uj0/bOqvo/X2Nnm5SthiC6xR3BVb2OBLowxPXtc75H2dtnZuinV/mGtfSrWH",
	"SsDGcj0mUxt73FUaAZVp/WD251yamFUkypgQ5ZTIQulai+guDV5g9zHF5NULcYmKKn97XtQhI96m1xPu",
	"ZAJNo7DQV5qI3YbI2A6ou8tCIN7zUxnKSta1j9oaEnSNOXZZTbCjbzCSF0L1VnZqOZC2PbrZ6m/pGbbG",
	"2A/J6kvY+GsATd8Z+z4uZfPBr3Fr2QiY8hZ+gK7AVxidB8atWJwaSbaWqlRvxZbGlWuXeBaagT1V3Vsn",
	"Nm1Uvh/ENNGGFqf41ONKpwuHUMOVBFAqnDBeR1gnk/Z0EDOFqnhB3nOJDxzM4nOAed4oVqiSc8aLyzEH",
	"b4rc89BfMbw5pXk63Y5/bqfbgUc2zsD9gDpq4dMqsgyI7PSwJKiT1LurgkFuFb3A5NqMGrFVblgsIVGB",
	"1gVaWwA6ajcOSJQ5a7rXtYwntK+ztRba2Hyw1nswio+tBhVu2zYs4tRv6r9QITOKFMiUlKD8OcCU2dvS",
	"+lOOSEtQSuRRbz1IbLy/JU8wTeDKjJbv0iRDavOwrvVjmH1g+IHZR/T7Us9A/5qRwhbl8kSDo+5XDbko",
	"j5EL3PIZmQrehLBRBax0tc3EiGdhrZssVz0cCoMkT9VrLW7eoXT1/oXVRDFyDZAFEWg4KQmMvpUtMYhc",
	"zRoB/evID2sFSpEA0c9kSXf4bbXsDS1q2/2vsmVtwPvRctvoU4QGtuzRastb3A+p4VNVKyw1Rk/HwGQO",
	"mUqelrgtIqageV7FWxMC3u+2KzF6AkpOrTSfnCD5tXFUdlD2l7yeh3tDm88I7ux0bzfSyi5Ns1ZemQ1E",
	"ZJEKLQF3orGsznL9tSu7plmeeKXXykSCYCCnKSZfqTkAqg/sBNb1uiaTmLyG7LrhyiKxUY+dQAt7YgOp",
	"GKsZECpS80JADUGVaUtg0UxaB1ftcUtts3itmcOaQsp1HTC3suh3DtlYPu2xnxYcKBEor8yXY7Dbpu3W",
	"xW1WFTd8s8UsYgE5dFN/GJpAnIucyoGp1Vggt2zoMubXO6VwGrAKeN17nYtwyR56hEGqto2mVDHqMWAw",
	"z7w1vdIN/mr2wY6rHF90q84ErUe9mefhLtFdDCBswBNXYLfmCKjJMwmoK4rZtZ7TdsID0O4DAZVh8ccv",
	"20v5oxaNuPrIauj1sk9ckcJru+OVc/+gklto6NFRJGOW8gkfiTJNm0CDGmAMRcyQ30QlXoinHxUQqaoB",
	"hpKkmBQZJx794MVkegr0oaksJp1uZyxHY8jlSwivNHozZMo2sj1VDOp19vRtNIWgL7Rw3sujMjIjAALH",
	"iUqjRpuKTQlisIpODJiKsT0TlDgENzYUCEG1G0/GzS0j1hh8lYK9x2TjkdF3EShEpELi05GAmHv001Zm",
	"bTdDA+fY2xSNCRxusQAJyNreJmdYhHAd4qCpqgKMd8IqeZ+WgJCP7rKR0UUeWifbHW2UEjVqHc8yyiCJ",
	"3qjHTjvv8Sf3OJAYP7h75z1kX9vKZglGSmv2uTIvq/iNMC31bVgp4qwX3oQjYKWYQEmb6XQ7Cv4NDHve",
	"duIqHegna1ub/LzMU63LOgWjDoPgU12W7cogjOwYPEsVeIqhf1bIOUFeitvIid9lQ55ZcZZrK528QF7+",
	"Mz4cotmujf+ljqxg7KSKlwk3i0KqWyKfVq58WLpRoNJtBY5UJTirxTxfswxHVuY8nBGC0JeVoVQIfzHl",
	"yG2V+r/WlYY+83q/9u5EWR1eHhawfIPtW5VCphf3zgN/EFFCDAQ3wpwUmNvAv94JuuE//OJhZ4XaOj24",
	"eXP/rT1q6+gtT2sR3sKktQVGn+ygb845AFTKOZYJZLjkEFM8ZSIoLwaZTICnDCQeNJRwJOBQNPnHSTVi",
	"E+6EkZxI2ghr4/WyLTMwhLWx3o2uAW0QQOOnGUCaWSbMaxZbqPqlAPkEbhxMQ3mux87lnadPoSxu2MCS",
	"dv/Og4fs5N5dSPg8+OB22duhHio/VafqYVneHqrwMfwJBC2kz/IANq7STMeiB3jTU1WTBLZbzyusVFyI",
	"SbfixSCMBuWltuJUQRDRVvueEdyYUpdsgsT1jKoPbFtg8VQF1ybEFSvRSBoCYgBhCCgbQm9evISozdxY",
	"nKp6M1wJtKTOBsJCf97UrIqsIIXsX94/mRg9OYVfT1VgTCys0xNYfsDAzawTE1ifu3VgDhQwcDjexyFN",
	"DhY+4vV4QGM3IsdPlURfAitBlC577Z52hhL6Hp12WExTLaF3uaPNX+RM2lNl5ST3pkIQJvhoOEW8wige",
	"ksin3nLOZCKoiQN2Xumc5DwZi72DXr/T7RQmo/1tj2/cmE6nPQ5f97QZ3aBr7Y13796+8/6DO3BNqUg7",
	"D/CQL83Yyb27Fdv9uNPv7eNlOheK57Jz3Dns9XuH3ljhbgxS6Absyhsf+/+cyfQpHjHvbzUggTAGDqEp",
	"1DqDGZtI6/g5aILKvpqiFvBLEYiCgSePTY1Wo9ALcVCayGEyCQsbuhTENH1bE2kv19s6T3cJawzv489S",
	"JvgFOGa4S/HOXM28KMi0PkdLPbZguJt2jjtvw2QAm4AX8sTM6yfnoH/UkJVGX9XP+lF/vy18G+9z41G1",
	"zwJcdLj5ondiNwa44mjzFe9r9w60bKgqIzAXq2roVx96q9AGIix6mbDmEOYZWa8yQW52Pnza7YyEa3el",
	"cVFr7NiQNEbUFfZ3QLaU1Xn/qXDNk94nz88RTwtEgrD97Y2PyClHe3c7ioinT7stw/9+LOIHSrQvn5eJ",
	"E4EVky2+Q/kTmLC76DrkzWBB9PhRb1mpRhk+m5glEm0M+mc2MudIKo6ya3v61zMJNsbhy+SDEdStiWIs",
	"sP9C9qckMsfwPjVtCh/CAMBsQdFXIqf9c6ASHh4mR2MIKvZO1SPCumHwgrRnzHRAcn/MVZrhVECt4q0I",
	"+groFE1Lg2BsNC8QtjfTxeqReATo93gqwLr6iU5nV3ogEAX6tO5JOVOIp9/SSQzcjn/dJ9Jf8NbmC26H",
	"fjn+goODzRf8PPadgdZQux39O6l0cZM1nP+n3RX9fyNIaj+0VuFe4cKCUOWQyJsrhNslHVYy5nVyKTBg",
	"C5khz4QYCpUeh04waEPUcDmk7+lpAzGWgDlCixYugygM9YbX7WRLgcqpfqrelRY0TSAAu26NE5/Tst+r",
	"c/v90ECR0FdgK110I65YH+mmZNJJmloISCmM4wW9gIYfYayo0VYMAHIrQhEKbMbCYmC6Euqsde4DZBig",
	"lfUk9+oj+o7kj5UQLspg1nzTW37FsQ0XAt79AF6rmkzALwNMCVSCnHLHB+AFUdNEkc2q5cky8fY4vt5e",
	"7ax6NRkKbarvEBmIGizgkzRdOR/Xo3vCI07S9NvQQJtOZhn0HjrKfAdmyr9qxXTteua2dAJBHJE1YRdV",
	"c+PjgJhc637eFxN9IULgBrxJVBp4qL39iKdEDqmkPOLqIBGsar66v+QYri3TtnTgvYRCGHkEkEsbUbCR",
	"pT5oM5IfgKIlDCdasqXMI3d2nXfZrn6O2qYi/WHvugdO56XsxK13hUqlu/mX/omgf2B3UxDwxscRubzV",
	"dq7whLla4+9IK4Tgj+DyEAEjkZL7bSddufcx4lH2NceyiEp38+gfUWf0erSyqnTgtFgv6qGt1RC1ZsmD",
	"5N0lo/MKVdambR5And+DMMrO9v4l4y5hysKujmw0rcGXSuwYy4yx+MWLwC0hvMcQntZDh0QCQGQLkVDV",
	"gEIPNbpouywXVw6rhbnSEUTU36JstEPCOuLYWGjRBiRae2CPAWV5KCHgyk6Fsey0M+YXgk290SNobFif",
	"i7nB1YAStUM26eWMfPGEewuvhMg20EF20mSvv99LtMl7mU541llupt/0CyidP/Ov0TnuHPQPXt/rv7F3",
	"cPSwf3i8f3B89MYvO8i30zmgf/b6/X5/78j/603/r375z34Tx9pxZ58fDA6To3TDlV5ftgzk5nH/4Jed",
	"eidwbb2BDz1pLHuA6byD/sGBn2ANsWrsBHxG/WczLJ2skNJ1/K4smafOYHN2jg+7HSXkaDzQJLaXJvH2",
	"B/fvnZ7ai2RvwJPzIu/U6C63maeDFXL4407EVYL8X3pkrv22G4ss64knYvcHHjY8MOA1wYkhWkIFsOJf",
	"fbw0IweXXdajTpk5mP9/8xeLf5q/mH89//38m/kX82eL37HFJ/Nni08Xny5+O/9q/uX8GZt/web/dfH5",
	"4jfz38+fzb9afDZ/vvhk/mLxn2Fa6sN667LDulkd1v8+/3r+zfzP8LR/nn+9+O38T2zxGQzsH+Yv5l+y",
	"+Yv5H9ni0/nz+e/nf54/n3+9+Gz+jL393i9R/W5p5ZcCoM37hu++D1430TUmKO0a9ceOhhHccH389zaA",
	"t5AeMjCjYzVEwlUAAg8L707LCcSIot8NwG9QNmqpLisYPtDamTtn5KBwgrjVIYUXfhJlMfZ1CzFhgpNz",
	"KgePDKaBlrdLKOOpkVQaIiZsCimqUH0OLQERaooOgSo5HIm0D5OrYO+H0MKSldYW0S3tomvwq+Hm305U",
	"F99rU1yXfvVDdmUgULvB3AMfAyTvlv7yIwUwVI59tBCXCCVPLsRFMRlLfUjL1hmUJq3yKHeXvRGgOiE3",
	"BY+PBaLF0kPBLHrh/egh+Q6RR7hCNDsrgW8YqaqiCwG/UPfZK8ge733k/nQb70rBqXR0bOEVtvXue6fq",
	"g1AZkuh8VnZYXjZ2wS0iOBDOWGug2f+0UE4X/vwHAbPnl4IGOjCA+/D/x5PzVp+JvNotXCacjR+qy+Q9",
	"0biTIiCptnrVc4VxqrUZbOTywwWmTphp6FFg+DQsduwMTDoIes82NLR1GCKmNrPVXIkoWzwup02OSasQ",
	"ZAVw7hbYTHFLAcAFPwwBZhwV4WoavaDmLXUZB0gGQ/XlLW9oII/m5ctb1RHZufPd9hvuZk0CNk+1m0qn",
	"1vc9eGeH9M+Gd681bap5WW8d9w+O+2/98qVcuKYOSglt7OVhJ3oy4So980J+xcVhe0Il7MH/8pN3Tt4Z",
	"nfi9hPPa4AoFTpmOLQCX2IEGqvTrFV9tmYJ92dM8Oj4AT7PatBujbW93jo9ef/PNbufuBMrFO7ePT0/J",
	"/zw9fQC7/vAgfnTPj/OBH+fp6cV+r396ujLyu8qJkZcx74oLkXWOOz9DsPo9KLnb8BjKtli61z2c3Z8W",
	"sFwfvz7cTw74W/29o/RQ7B0N3uB7byX7+3tvioPhTf7GoJ8eHT1d6XJDkOGVhjWwdntvDfePkoNOvf9M",
	"xJGJ1FQCCzdotW9Ur9zeWQI50ZoLgS+/NwAZil9CJrtZT+zoLNViw/WwWGtq/X6AZVtv+VD/5EjAllbo",
	"xI1QXmUAjxLYLgBhAwb72BsQLK2hcMk44qSXECouarlIHGOJL6M5T14HHHZWJmU5wg1OU8vYm6wrQv2F",
	"XmVauwppYbW1PtTyQVmNfxD2Ce8GnGVJkljd6huJVVbq3IXI0ZEFeI6m+mGCgK4y0DUNJRJabnfkGpm2",
	"1o2sKd4qLQvEYq3DCsVB2w6s5B1bHc2D0CibCGBiCxai5GoawK9rT25Yig3H611oMr7FD28jR4c/8S9n",
	"71D91q8+rvUYKMn/D6q8/Eclj/7hKv/9/hJPfE37vXl88+Zxv//LFfj//N8hCPfF/MXi0/nXGLf7fPGP",
	"i39ZfAYxu1K9svkf58/mX82/mf8eAn0v5l9BfO+fmb+Ozb+cfzP/GoJr38y/mn/lb8vmf4Dw23P8xRfz",
	"r+fP2fyb+Zfw9+KT+fP5H+nxX8N9v8Hb/GX+Am7zxfyZf9Did71gCm1pqwSy9wrvRZUevfNG8pZ4fXCw",
	"334bzjs1XlRVZFmdqbTz1vAw2edvDA7AUomFcaEsLdouxPgVg5L/9/wbmJc/QvDzs/lzDE7C3M+fzb9c",
	"fDZ/gTOy+HTxWZhfCO/XyWprS7zfP96/eXwASxzB2od+L1daf5QXHDzcf/24f3S8DxZR8+brVzff6+Xm",
	"2z9Y3X391t138HB///igT7tvl+hywypebkVixWBcE6Jfu7oIdtvC1Oc50gSu1gQtU/J15v+2/PCvIEz9",
	"AvbHn3HDdNn8m8Vn87/4kcIhpu3E5n/xu2zx2fwLGOJ/m/9h8S/zr+Fjhj+aP1/8AxzZz3vVLXPTC7Ua",
	"EZGf6KeX0jXAvdRg6rVzrl7e9rv2aJq3VJZHW5p0S1+AadcMHqOak5UAEBUInaytQAmp9tMO4IQw50p1",
	"EZPc6Im0WKPgfyAtfIMRC2LzBTfqtENRbjLOIoQMPbGl7kWrZXAQdhsZPcWC2YQbM4NQnp6q0hoLxBvU",
	"C0SrC2Fc6PJS5SGvW4RIKnd3KcRyHUHsJjbvrYLZ+9czhDavSInpUsjplXtIVxO594fuPj2n7WWJ9tFb",
	"dBAAjRK/pD8AaFTEDYQWGK9ECHwAhLNq6fgu8/9j5kYrsU5ArHpwNz5ejs5sDfWpjycW5VFWiZjTsQwz",
	"cEeVBYbdSkoMo+yA5gGAaazprHt0A6EEhzB9j901RoD6GGQUPwTuRfCs0O2kdjllXdet0FQjlnVFooap",
	"NufYWqAs5yLniIq5Igst+nWRmAk1p3/hUNbVFv5eFS4/0AKstkB2gzZrDWgvtZ0KGLNgUsJeGgdyiBIJ",
	"FmohQ50/fF1267LVXl1N8eYNa7ijH/aj9/Wj93Ud3tdVmgHfsglwXUHSHWTQbsHS2qSuB5jcgX4B0JsD",
	"iUhsoEwJUG2R2Qq5fKWSkLRRyMU21Br6rQiUTFCDTHRT1FGqziYRmxKw25idxjq/imVR3rbKRhYBIZEF",
	"mBLhZBpwI71CLtV4AJmHqplb7ELqDJOJUJPvCqMsOzo4QIH+GKtqbQ9f4u+CGD8LlvJjrNRejWFSkYll",
	"w8JQA3TE8sB9j/pvdZl4ApRsJT+/dMd+ASA1ief47yBWSrz9VSZ6YLWxbGqkc0KFbCUvUulYpkdt2JhX",
	"7l18K0iZraRKAMx8R6TLX2VFJG6qnQyqraz/G7G16dqCeAu2uuiynAMkAFEkiAQAtJw3IQKdKJQUl11O",
	"hzJzyDoVLBpvT5taJ8sJNIRUATKDrTewV6RigyI7by9/3JjNQe5vgOCAnATEAaIiRI+9jckqWx0fcm9V",
	"adfEkzyDHCcE1dalTEQ9abIdjXA6EiFp0sDX62ZgVwy1mXTW5VRwoWLnZqJ2Nj32DqyAxGI+ZIKWFkxi",
	"HihXDLZc9EL/o4IIjIi/BRp3jkZ+36xJGJFFtq05Enqfbn4fZORF/AqopyySyDeNo46B2JCsWf9kwEDF",
	"ByvoUipVoHHFzOCakQBx/Mvm8gAeJCLvZFhTcGiBbxF6BYU2IRwDFm0jmiCcfRgLtsqBbdk76K8nw7UL",
	"McDmEDFKwR84lBPwz8O18LPL1qY1GsqNweuHtY7BE64KnlX4N8IAqc3HSSBOR7+YBd4koJkq8ZfElIQs",
	"+lGelLWW9Fmg6yh5kr0orMQCRclHP4sd9FORZNDJvmT5qHQVcdTMAUnEMdBNaL89p/cQvxEfWNrrAECt",
	"ksCHMEGP3Rd78L4B0wdxdWdkDqg/sqv7b9VrvctK6bZ4+DXzc3w70e91BB1KTH8k59hdULxt+LQkqpkB",
	"XUxL4fQW5mcMfn28sSowYmjG3FbqP7Ebadcvp7ChmSv7STRIqWAU6JqwjUm1eUeEv+YyOReGUTGqUECf",
	"E0p0K6/aYolWmu2vM0YrNkbg3gvYFy8gKJRpXdcPxHSZzLvegBZnY27HbXq9LErbyd5pwb8s1aLQ9FBJ",
	"GWRNvpfgmB+rIa+kGnJ1Jh/s7e/d3DvY39vv948OD18/PHpzb3//jTcODt98a//m3utvHvT7h4eH/b39",
	"/YPD1WluqJe8ymk+uK5pDlDg6jQLBW1TQnckuDrn1k61Sc+soIjv4V7/YG9//2G/f9xHUMvSVFNSvnG2",
	"t8TudjfWiK6b5PBuu0DdX9lelgEXXYbqc/+4N472D5YmkmDGjRO5/+bN3sFBv7ff3+8dvbE6YSvfr5uw",
	"MM5tJ+zoVU4Yt6pzfNC/ud/vE04L9Pz77y7vO5l3Xg66E2r6tnDIgj79YftkNRthTVXQ5Ytjt/fM4mCw",
	"TCObUWtBjLOHjP+A+uBQgwwkY4CiDRtZb6RKvU7WJjbk94YVdj2bBGeN23HgVhsUGRChduHOxPkQeNe8",
	"MuIjijWGLueRRqRCIEIRS3QVCWFEtqHVQOdIzPwZEAGvlPJiYkKkFG2Rk4lIJVDx907V3VRMcu1CX7xQ",
	"23suZsfAtYQd+Bv5u4LLhqXC1K6fBtbiwkVAArFyhekUygFtrZvKRFB3a//Y0NSs0e27/iLeb8n1W1vF",
	"W2nDiQQgCBKB4GeIJmgT18r/RvywhdFJmlb4d1Ydv6WS3y18P8I6tHt+wPxGKxC5zMl7QzZtnaUVp+8D",
	"g7TNgxmrlGlhakGm3Wr5LvVxs8Tt7ZUZg5Jbgd4f5Pt57NqBvQiwPsU6Psl77D6fhhrKWg88DEKVNSwl",
	"oSyWeEI1iLaixZEMRGTbupE4vqoTSX0nahVzfi8r4abanJ9ZYe2auHWlWvCy4XMcU8xEUGkn0K9LMeky",
	"kXp/3f8LOku0VntUqstebigwN4GsCpYdiXlUmcaqdAIpeXpgn4x5jugyUAlAsW4dMvU0zl8s3HypyP+7",
	"3iBnA6CL06q6n6mm11Jb36Yx+KlvfnzKndjzu3ibMTzK89YxAF35ujE4fQUjWIlRXBCBIdWKWpHGQma/",
	"v6gslGVSCdtlQBcfeaKE/T5GLv5qCpr31xQ0L1chZ3oEFuy21cf73271cRgu/Jfe4bBSVtwQC7rawuIQ",
	"1qgX3FKrntWK26PXD4723nxz/6B/uN9WcusvrtbcEkdH7dK4C34smP+xYP46C+ZfbSH5y23q1p2z+yY8",
	"arhVahvk5ZLttsM2PNywDQ/fPD7av75tSOyInW5nMHPCnunCdY733zzaP+wfVLZZPZp2fHR0WN1qFTKc",
	"2nZbEbubtlsIf9W3m2rZbn6y995446C/z9u2m+JpdbvR8tgb1UtfMmbmx7NNyKxKe/TD9lQf0ixsDJtd",
	"liRhNzjDlM+A+RzDM1Ugj+uxh+CNEKZIPPE2H8BjqUM+4NLIf0JGH4u1QNjUEFoLq0p3XPxpj90pOwtI",
	"WzGWkQ+rue9Xt8KThV+FQAhZ1OcAO4aWt/6p1E6rjJJhvV61GzZgzbA6T6oLaOvdY2Ws7LhKLRXjWYGa",
	"Ctvx7+m8xx7l/lVv9vvBocN2Z1l2Czqvm5Ew1O9cagX5YafZQGAr1gZmeEAzR1f7WiJf/ub4nNAy+lXH",
	"v6ojgE62DQIktjgArjWCl6U/IiKedjs3+1tchw04Hyl+wWXGB5nYTVLd87Me25FQZGujuNouvIZAjLbo",
	"2vt4yGM9HpKyIL4iMFtOuFRQLUcVb0OeYIeJgaaSvdhNnFACcOADjbwI9/aiZAwrXqGHIW5L6/gsgqu8",
	"kFzTFw2SC6mGCs0kK1xoZpDLxBVGNBZx/RRmYUM47SSzmuLwpTiDOaFK6TpnCsPJg6HnwuxhKLIakh9r",
	"W3JG69CfsV624GcZes5i2gP79+5BCfZgxmLeDcHI1eRkWxCDMM1nVEFZC2nQpEcAM5mVA60zwdXVIU/Z",
	"IyuGRUZRTqmg2qKqDbZDE18NUvVqceC3WM6tLRv/BWWdgRq2QmBU2c+P15EptIX/q8KOv3TQiYoFfkUd",
	"zKnf0v6aukRwc/ehaC1W9BD/8n7lo2B0g5zbKhz0IXlAN+mfa0PSxFJDv6jLdYYQD9pzeg/QL+touaP/",
	"EGDhx50j+mdDDKFkFKl07XXe5nG73WxddWH/reOj/nH/sFZdeAC4iJ1Wev+qV/pgl5U+uL6V9gu8F0jP",
	"9wJwZA0v+uUWfP8qF/zwpRe833vjYO2aH+0f37x51Wt+uMuaH17NmoNyWl50U6i9o+TN/WG/YaVj34cz",
	"zHRcYrVrQY6gdS652EcbFjssVFzs/W5nOvZG6Py/LD5d/AbIfH63+E9YIv7p/Pni08Wn8xeL3yH/z5eL",
	"Txa/Bep6qGj+M5v/t/lzBrRA3yz+V/r1N/7zL/DT5/M/AAfQs8Vv2FEfGfC/XHw+/3r+B+AIWnw6/8rf",
	"4Y/zZ/O/LD5ffDr/cv7sFps/m//BX734FJ67+HTxOfz7s/kXi8/nzxef+QcMuEUHf/H5/I/+Gb3O6s49",
	"3N+4c1//VqXV0avbuVDUXvI+/TvU3v/FzzXU7r+ApZx/w+ZfwMphRf8Lv2hfLT5f/OP82fxPUMH//Hhp",
	"ycv1+0/+Gn+Xr6Co3z/gm/mf8Ps/zJ8t/nH+fP6nXTkBVsKsxQCXRA8veeRuVo9c7H1/9fK1sVz/wJtg",
	"y2Z6aRdePv6aiq1RzJcIdu+ivF4GtTgAGtuGMcOqkG0bqeaX1fW1gJEvke/axbZ7+dlqgEfvPFtXgie+",
	"RDJvl3P28jO1ksnaeZ52ggtfIhO0i6p/+flYGfH6+QhqZhkQHPrqnO2UF91BWl/ByldTocdsQ+qzNg1E",
	"Ob9VDnOFlGaHBj8YpmrBKmIk7wed0oH5eXXVqdtFWEnvruFOoFTKEncCggO1ATJoDMJi9ZkFPCp1+xkW",
	"WUaJlYBwQnqyLMMkDsTmpoHBbMqtE8OipVE0RCx3LE6b0fADgTSmk+CztTXvK9DBdRvfD+yhv2D7AjUo",
	"p4Wz/R2Hc20/Q9vkf3E3/qClBMblv/Ua9jvV04NZANq70gCBKSCMK52tI7YZ6ycC5tjxWUlKTintQjmZ",
	"xbqJVCQypdbCE+78OKstWriDX9iQbqimbHKjJ9pBDmi5+Ux8mFa1UlmrSehQpURq+FThZbLKCQXMIgo5",
	"o86pjf5IQKlDopV1poAAeiiorVZPHNO4IOOkJwIrfwMGvFaT0Vg3AbKhWjUx5DKTahTTM4PCOaTDtXwo",
	"qPmxtVgy0VYj8T4ikK8jT+xv/e3UR4BKhTdrq48HxpMfCyS2T+Y6QCykorZRL10bj9Q8ftDXJah+AcZG",
	"ZMZIEpE70PcI8tCFw5wW/untFPACYgpPpD12kmVQXIAsdsdMDqH8SjoxAdpmGRjqMuBUA1lU0sQNQLED",
	"rw/1gSbSNnhaJIVLKJ9vHzPFJwEtIlPbrVHoVXjaCJzCFdO5kxMvHhL26C6ILqOzDDtd5caLR5HNVk/+",
	"fZj9wDB1HUcfn7ATOqR/5Q/fCAzBFUJOvR+BIbtJBJzkMp+M2pMozS4tFzBq2Op1rHSnWeJqRupor7CH",
	"mTcZFLFgG7GnTRqauHOWityBzS24P6JOTKi7NQAVmBGDQmapLXv0SOwzCllyf/yU9gq/MFZeCKyFamRj",
	"X2bafYjYhe9g15Pc74H+SzPZfk96gtSSMa9v1QHksFyIgx0XAhM61YXY334hDnbLp1QWaNtlvpIl/D/n",
	"LyBz9hnkUJ4dtzI5QzLtm/mfMVcz//P8uV/dSnrl2eZkYX1J91vbvNT3QH3V929utewHlcYvu/R9gbHe",
	"7NfP3w7Lfrjx/F3p8mZ6ur5BzMr6lpHKHfNs259YahZTyYS1tImBBN2nmJwLeVt83gsGvN+Q/w1ZxWeQ",
	"qvUf1XOKkDmupXy7bP5s8cn894vPQ3v0xW8x5fzV/MXiH+fPFv8ZEsCYh2aL/23xGdGUfz3/evHbxW96",
	"Kxk2o/Uuy3c5Dm1QUy2eU0jtfS8YtB8ut2a4XgZtbwNB5OTGx5SM3bpFhQpwyUpH80jiiQQQkQ5MG4p6",
	"DMRYApMf8SVgnERSK3jrPzrtKO3YVBs3hj7v1IU5eninneXgR+hC4W9BgRaizsZASKFSrURb84gYbtjU",
	"MwJf/nvSM+IhPxfRfx4O1zrQ3fUhd7861CyoC4F2b816T5JY4LCbCtQSJ9ykjTZp8yL0X2345fvDwa9w",
	"Ol82COsnLIqJWCXT6g39XCd8UGQcohDITg2kNPD/J/fuYqENVovMWBLavAemgFkubBflSECi2BIUPCoM",
	"0A8WJhG25huBsyNskCOJYNwhCU6RE54bvpfuOJbLSMc4exyzq4+h/kUxnfNfF4JRHgRcM6WZTLTq+t/X",
	"ADKPofJFaYrnQIqkG7H5WATIUskzPQq/jI3f/ZETpneqsPkp9rNHdw5zT9WgqhtXe7JaNhAJL6yA1JQe",
	"ErEq9mNlTo8ggNitkPOUDQ8wHiO8S9pjbwdy1VCalIo807OJUG5vKlPRBeR/LswedmSq9OXBDVrrNDZE",
	"EW9mUCgkTOMpvx+30JX0FZ9B8itgcZwYaTgA3FqBNbglOqVi9/2/8z96d4xwBfEqb0dTFp4uLKwwyz6d",
	"9+L+SP0EyavbfKOA+KgOglwJ8gjBRvMW3za3ExMus8rN7sDfS5chMhZzMUuAiuorVdFly7egKtjyBjKv",
	"XHv33l6JHtx4KRIaVh/9r6GXzcZrC1N920f3393iXSOLZ70l5LP5n+ZfsRts8Zv588U/USaRznRlL63C",
	"yZF/vCQTJDDcuVRpFb9BuLaVj8MI/o/5N4t/WvxL2H0rIOYresz/FUx+CDPUHkbuVrkXruiR/wYBjxjq",
	"AG/jhfeU/rK6xRoRvVc0jn+ffwNgWOqpBK5M/blGWCiNvNLH/tv8GcR6nkPPUXzs/IvqY72UPCNZVD6U",
	"0IiXfOr/A04aYIMBm/u8vtZ1/OaGNyXszaZH/v/QpeqzxT+jB/pfAab8YvG76nOHOsv0VKRng9llnxs+",
	"rexoRELDmSUroHpYiZyDrqe/wuXv8Sf3uDM6Yw/u3nmvdvagGD08NTWNF915+371GlW9RtWuufeQvX/y",
	"dvXHQLlU/jz8GV/sv8y/XvwD9aX9bPHJ4vP5l4vPFp8vPvHutvf8qUXYLvCmUs02GLsnWVbyqr9Kzsed",
	"qBjBkqjQvxNXlLdyql1aS5v0w6f4AHMRbFuvNo47N3gub1zsw7ahq5r8GAip6yH1N4QedtSkyRubocer",
	"RT7FBHRyCO1XfWrog1i2e00yLidUke0gg1e2fe1VSwmXmtA+2SP60/cbf7CK3bkT2vB5ezpUrhPOARAD",
	"YeaZ0zqj6le93Kyrx97hibNdprwlx0QqoU4d/xrJC6Go+1Vhe0sMZk2jpi9WR/szbf1TyCyy3UCeJqrk",
	"UbgI3HrLvaQfh5cJ7Jexl2VitLV7yFYurdOwYbirUIuN+YVgU8EsEPx7RwHtYyQWq3KJIa34yruUDKmN",
	"tb1dBEYgXsOvul9yIjmboTsjSueAuvbAGBFWwRv7v4TWuqxCycGGPKlunuC0L484wBhXKk2rZv/VOGnd",
	"Rg/tvuDpsjvWq7aOKX2B5bGX3z398On/CAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
