// Package spec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package spec

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H3vkhs3kuerIHgb4Z0INtX2eD6MHPuhV5Zne8+WFfpjb9yMrwVWJUm4i0AZQDXFdSjiHuKe8J7kIjMB",
	"VBULxT+t7nbboy8Oq0kWUED+z19m/jopzLo2GrR3k6e/Tmpp5Ro8WPrXs8Y6Y/H/SnCFVbVXRk+eTr6v",
	"5S8NiGvYOvCioG8JL69Bi4U1a/FOw3t/xX9/J8xC+BWI2sKNMo0TtVzCTDzXhSnBCSlq4xQ+eCq08UKK",
	"XxqwW/H//s//FaWhP80bVZXCaBDzrVhJXc7E92vlhfLCG+G8tJ7XxWXmsFRaK72cTaYThbul502mEy3X",
	"MHk64W1NphNXrGAt8e38tsZPnLdKLycfPkwnz7VXfntZDt/9sgTt1UKBxReTWgB9lfYrxco4PxWyKEyj",
	"/VTU1hTg3FTIsrTgnDBWrKRbpb3V0q/arfGjrlQ5mU4s/NIoC+XkqbcNdHe7MHYt/eTppGnom5nd34D2",
	"x20evymUpqNzUEHhocRt/wyFH9sl/ubjN/k3K+vV83IJx220XAKdMZJBUUmFty298BukESIkC8JCJT2U",
	"Yxsvl/Dx+77UN+C8Wkrc6lF7V91fnHjYvd9+/Oa/VWvlh1v+D7MRa6m3QnlYO+QqC76xeibe0FbtDVix",
	"ltvwZ7GADdip0EB/NxbGmK2i9bp7LGEhm8pPnv7lfDpZy/dq3awnT784x38pzf/6PG1daQ9LsLT3F6Y8",
	"hlbEEgmLiGImkL6csLAAC7oA4VfKsZzBOwisa2zggzmslC6FGrsMfObH38FLvvDcq7yen9trGUmipZEF",
	"yteVwjf5pQHn+V4KWVV4/o3zYiVvAGnt8pWwpgIxV7pUesnUplx85Ff0qWNxafwKbPyEGUgttbEdBlqB",
	"LMG2J/BfZ2H3Z5df7z2GWnoPFh/xv/9+fvZXebb46dfPz6eff/HhXzKH8gEf5WqjHbDiMXpRqYIotTDa",
	"g6b/lXVdqYJY4cnPDk/s186S/2JhMXk6+R9PWpX2hD91T55ba+yrsAQv2D95PE8LhbGlKFZSL6EUTjHF",
	"gLgB65B18f+LSiGpOED5jn/YWOVBbExTlaJseIN0FfBeOY93YDRMBd0g7MoCJ2RlQZZbUVTGQTkT70rw",
	"UlVuVoQzcO9EpZx3/PPSsdwrKulWUIp/RS36b/G7f5pNPkwn3xg7V2UJ+uGO7xmTIr5P41fIV3gKpZg3",
	"XqxMVTqhDRPmiPhLB0RfKg044tKlldozBcuCjoxfeBFfkd/4UiOxyYr2+XBv/VajNVIhg0pVNRbwJaSo",
	"pVZFKzpVgeTgNmCd2Ci/4veXaxCACwjQN1CZGoR0KIfs1q+QaqByMBXOCBlpbiUdqT+3kjWgkK6ldfAV",
	"PW8Nzskl4A2UUKk5WOmh2oolaLCqEFKXfLwgK1HIxoFY4iF7Q3+uzDKcrApHyQf7wvhvTKPLhzvTF0a4",
	"plhFZhzTluIVaSLAbzgPskTZ/+X5n0lU8m8DpxAb0mluVmD5SPkkeBMtsVm4wdPxK1iHw9DGXy3w/dNp",
	"XK7rCtagPZQPK5xMjVeKHEAv5OLJ4A6sLDyzmiRGU3GT/IMt+M77qPYN/jQTX0NRSQtoXjPxdRaaAxOK",
	"7xCycmIOSJ5olPu0+tlCWeeftrRaSC1WqoR2j6bqXpVbmQ0+BuUkvv6UKPRam41jdlcuuAOBtWbib3hP",
	"ciO3okZVn7aJbCOLFbGGciSPPWi6sNemsQW81fJGqkrOK3i4O7vQoqmdtyDXwkHRWLQ0vDGVKFXJr0Yy",
	"geXEjlrwDqoFvozSHu8WDV8L3m5JTGpprdnQybKvxJfr6GWvmvZtmWrfapTJxqr/flCaNegOKifWyjml",
	"l1OxlhUaR1BOBbyvFRGdFU4tkYvnWySFRiMFaPQsw0s1nc3z6/wgK1XSlh9Y2r9i24ulLqu2G2XQ4UAv",
	"1jYVRFe3NGupNLuEGrnROKfmFaCv6hsnvJU6+rwSuWOh0GjEq0cFYRov4EaVaLHiF9LBRVebj+YmHQQe",
	"zIdofZEBdVH4nOP+48og84SnSR2VanBem7VEoWJNs2QtdfHyckpfWyJP20YnNZ3kAZMqPocsHSEFbqNs",
	"KvIJQKM9//eJ1LLaOvQE6FHoEWydh/Xkp4ExGJ3v4e4vovQ/c4WpoTza2xY9n02sYT0H61aqRvp0Hi1e",
	"4aCWrDNx37VF+eIVm6OyLKG8ulFEQ7Kqvl9Mnv79ADXRO3xv1VLpyYefphmHq+OBbKQTldLXUCaFrJwn",
	"5dbZOJF/IbXRqpDV1TVkzugFuh8VcotQZXh6o9UvDRBpKd0JWeDBzyaZCyiVqyu5vWKjf3eJb+UcquCS",
	"gHh7ORPfyKpyYi6La9x+b4diswIt5BztZVxLN1UQxOwxDNYmRXLlgK3X/srPpa0UsWBwkNhtIzWPGk0Z",
	"7TrHiusld6yUHs68WsMxm1AH3czu5fG5cowr+fIH/MDppJKj7/ktypT7f8s1eFlKLwOJk0CS1csO6fMP",
	"d3xUUjNnroZCLdCy9N6qeePBdWjJzHHnuAj+4QrlVeY6WzIU+I02iNc67KUiCSXtdpZ1plsP9O+TdM68",
	"3i6v/JTZHW/hmbSZC4+e7gbNGFIx7z2RfeKgoaSAJLpOERMZAfGmpS8yhwqJxrATcm4aT4KAqMJdkezL",
	"nC19KmRhjXNd2uxSrpfX4FCfeaH0TLwEe1ZIhy/b6BgQ0OKdKYrG0nW4d51bSLGZ6USDWq7mhqPGmUtW",
	"4PAENdvw823UeVBSYI8oh0JPFDroneh+WXTpnah25dExtN+GWgfPxKMPL9RY8sSGfDbG1BSAVEaPUHwQ",
	"+9tusJKUby0taH+VNFhllksor5Setud25Q1aTlA0Hm0oC85UN+HP6E5eoTo8zCX9IHN3uz+NsO/k6URa",
	"K7f47w4tZG6jq612NRqvO2UXmEUa09mey99P4ylqaRZoh/BD0Wa+wYPZEZFDoh2EVrOUsKOBj6ABr3w1",
	"Qqr0UfJAg1FEvtLPTbkkkoAbiXIv2oGmBk1xvCNuNhMr5r3sCIvD95wlmd3H9Ilhn3T1sDQ2Y6x8I9eq",
	"ouvrWCQOSR5NbAGaDVHK8WzxP2hDo4sLG/4q8RFZZ11jMxo+KAfAb4y9xg+JcXDd6aQG69C+0gWejXQO",
	"6G38Cuweg/SZBekzF3uRDCp0qi0LuJXU5VTMYWFwh3obKD7pb77PPrV/tGnXFe33Y9uRNx+3KTL23dCU",
	"OshlfePcG5IbvXcxR/Hd7cyZC92Jt4mNsX6FytZu8W8omilqFGK3JbqWxopCrtlaoVzCI7B8Mpx/Czso",
	"uCtZQdu6DfTy3og5sOmQSXJ1uZEIH0W8KTruX3QIx9ntpVxmTu57DZRATkJD8en3OSmpkxGjCu0REzMj",
	"cgk9FXSMvTZUjJ2Ud8aUlM6h4HoXc+LeiCWwLYY/DDnxC2IjETIN6CCk3R0waHbpgd5l/KJfSl+sMvJY",
	"QVVSTJhzIDORuMOslUdjBSUxvYryQrmZuCw7+W/cNdF0jDb3RQV+JYT1oFQkzYdXt18+vYBN1t67I2Hw",
	"CupKFsAGcwgMtP6N2KxMBU6iCseXWINdko/OgnGdkQIfRq/gDf15n2BIYbwoeC9eXuaURqtdT/E5klYe",
	"+h7/bo0sxYKVc7rTOVRGL5E6ZuJbCPkozrUWpjKNTQbttdKlE7JS160dc6053ssxZpRLHM3Iiscf0dV9",
	"lyTYO4or6U66tpvkDfklJC6OBzUObCcqBGupqk5wSNXTEKCbisZWU7FQFVxFVMax1tx/NGupzyzIkm5I",
	"k0LYR5I7HBokc7TP0i1mebYXmRxs5d9NyTYUHa02+uyL9+9TemMmnlFE3om5lZrC5OIdnSoTcRA2//Hm",
	"zcsQnnwaqJ9ClQ7ZfYP3sZJ1DZoYIvqT3hSmEhXcQDUNgf4Scj8Jtgkfe8ZrjoHcobiOiTWOM87EC4Ic",
	"oIJGGR6TVSIkTRkA8Jfz8wyfZCntO1mslIb2Ii1IZ/Q0GZvsP6NdLh24mXjXRl3ficLcgHVibvyqF6ad",
	"443865fn538iSSjFBqrqLH7YoLdNj6GUxb9++cUXf5qJdzu5mXdiDTIEej4y98PR3VsmZrqqvBuMZ4ss",
	"5Jmnk5QpQ2KO2fvppD2tyXQyTFCEH3Zem4AHfKlZ2yBc9Gli/fl7b2UK4XjVOqUkiMQPIb+fUu4Ufg3p",
	"fulIAaqSjv1dm5b/SrRvF+nUsSTAXy5QmWYNw5CrPShU4H1dSS05T+DkghQB3s9MfMNhqET/nEkmnZzP",
	"/0b1PJ7/PVpmxe3/lNN2PbeR2Dor0W4g59BfaKHW64ZZrxf9PDGETy42MlfwuuQWrdU2HrFuKq/qase7",
	"dyPxPJWLdfy4MsIbc802MLK50iz1ClnLQvntTBDdUcir5EiS0ktczmh0EUnKEkt85sRa1jV+o7YG9dG+",
	"mMj+yBVuRxWqlv5uQ1eX3vUAHHyyJFoKb+xU8O1OhbPFVJQRo8Q4B1bceA2oEaQVfqNCkEOUakEuj2do",
	"0n0HsBi96LPWV8fDDjH3bQ1TxiNIF02IK0acGotcw77ObRMItMgt8wdMS1BeSZ+jTuhe0wYN9vD90XzB",
	"Qdf9tIifCgG5HikfDp7tulXpSq5ON+ffrFoJUNcEckhyf71GdRqhN0jHrgkUzEnRDkWzKUTfMTHKSB57",
	"S7vemMqRcp3T02sCVaBYcCBtsYK8KggRtD2XqFozakrAh1ZsIIcxUoLkDlnqag2V0vgNiybf9vjbtnJz",
	"iyPmkIGswpZELbeVkQGhTdBFPCdSpwnht8efbU8mGAtjDoIqVoymUL6NxvAVKVhPBZR2KjT+R+mFlVkm",
	"DUskPPMRHNtFJUm+9Zl4HWzFkHVGN2BpCCPTiZqZcFD7dkJO2yAkp/Q1ChuGetCypoZgGYZT523dIk5Q",
	"TvonPTyUnsTsE2xfBo3q+QvvZbEK6InRTJU3QUIR06AgQf0pC19tSZObhbCwcPQpHwXhXucgHGRiqR8V",
	"dow7OkoOM+J5COUlxFp4tG20kEuJZjYj+Jh/R9KH+fDvD7JqGPWnbthva0sO0OjsuLwD/MN30qMISnvo",
	"mR5mo9lYdVnaRMbKUKXZgBVztPgjb6BgERulS7NBriuqxqkbOF4AVS02PUDEPz8/HwJNa3z1hPAzom6q",
	"im2NlbSlKEBVZGo59ANJYhayIrZLaPO/4HOHCaEjRE7gN2+YBvPM3MzDP4YBNgtwxnlkK5drVhxijbcz",
	"JblRoJcpJIXLCqkpVPa+xsvMByfMcI23db33ZuD9iTezIzO6p5TjefagM3zeejPRYA+xhx6vnrHCJgGQ",
	"N1MXGTvkVaCHQPlocSsLKDxm4i3+cxMNoph0Q3c5Yq9rVZDZsoK1MA1jkTmvEaFPheL4n6SqI3J095jo",
	"x+oujly1euWWWsq7kBAiTdXTTSfd5nCt3P2u5ftLfu0uG+UThwMpfFBJOGL8bECQDOSmqhJAX2XIJwPe",
	"oidDOap5NGyqLWcR2xSXgymSAFVIRC0ntNlQ9DGQDWEV87nlVAjgxqEZ4Sn9LHkfCEr247VC2zW/DqEn",
	"rgrKTObekMpfwsfoc+JiKB1t03e1uo8MLu8VRO91H6gjPNpY0dSlTAYfJzY2QZXOxDNGlMRnx/i5Tm73",
	"cB8WGpddO5ZV9AIE8Rr3nGZumR16TbTSu8Hsmeye/ShlH85jdQ33o3NZTEVTYaoSjSaCzR2fxsIfv27W",
	"a2kfOpkVIlHSh3JPLWBd+y19NkWtvTIboXwKeOrS3Wn+q/vm+UNNOQsSzHKTfJpR0XKsC47Sq5Mw2mF2",
	"xtUz8HMmCOyKa20jibQxrxC5X+wEYtq6kptYLiI7LuoNGZCEAOXKL5Ryx5tn6WXnJ+SaGIc8TDEREDmc",
	"ho8HQnj3XbzrR0Xgfh9RtEcX8nq8IS11BCMdT9IPE1y6h8DP8UGdOzXGD6IqbxO0uc/QzK1iLTshlp1C",
	"NHYAC6OdqeAxRly4bmQsw0KeTOD1qfBWrddsLpHgpNLjG9AEQaylhoryTY796wUa3/E4uBQx1CNTWVYm",
	"nDF6fW+6su+gXNgnwH7sJpqnopU6ZVP4z5y4MYWcN5UccdYfiA8fkDFO8gZ/a3boEP2tmSLHBtRcIqft",
	"qFOEDrBzEQpqg4E3FeyRUfsDXYLNUDT+bMzPco29UTdoMHQAFLgYod2JLcVCVR6sO9pST10ycoqdgmwl",
	"XLlm7i1kKYs92GKlqp1iIic2YGEHw0QdBgJupCWWuTEVSH0rNCc+krE6HfzQMTxPTT2yFjqBXMoOVLKM",
	"2VS+VFxoMxV11TihnGFMktFw4qEjrRxERmeAl7zx4B6OEyfdaU4+H+ptIt5qQlbF7i3T1B4lZJ821gTo",
	"6opITgZSnIb/gzKhXCJOLyLnKUnjkSlyAJpIxHmAqGsCTJZlL1i01GbiVVOBY0StkGKh3kMZPBGUpbap",
	"4Ks2zIZnuaaCSuUpMN0L237eaRFyPippdINuEoHL2DU/4J3hyaFNGb59vEyPJZoHyxNiPiGuRsHEmfhf",
	"YA13gKjMJjT5wJPgAGXsrhL/uuw7Ct2ATdxHFJYjyNeO5nczcVFVgSVjsIRcx75LGr1KtI7nkiD5C2ML",
	"up/UmwDpNcSqUUwwWK/1MD9z9POPSwMf6XyUSzjS0ThVjIWrO1GI3Q6F+jIwUFtjR2EnNxUwW87EhswF",
	"qjemtA3nD8YSzAnSfZzDPlqxSh47b6yMyCi1ToA8Csm6qWhYOLHEmbU7yBsYbPkQUCek+iLFBS74zMW0",
	"vFAlYwzxxT9zhNxK1cipPvmzrvEzE2/MkhUgIU14J6m9wMpsEv0qKsomVRJytiiAGO12lOdjATd5NeZv",
	"/bjaRt8V918K01APC9YknGzgR1CpPAUzfMrsr6lOT4Zv4CYZytk4WDRVtMUs1Mb6I3e7N0qRwu3xe7iT",
	"Oy1Tm+K1srwyi6lYGJaBV/PtPiM19l/K2nX9DRNGxyU7+iCnMsEezydJh7/mH+YYJtaNMIk5LzVjCC3c",
	"KNgQc3hpl+APvJjyojYqpKQj9K/RnOEibV61YsrYsgOQ1YZgpKEd3sFTCDH8vc4QRXJjCoYg/VrUVhZe",
	"FZwzSVEafs9TVGpotJTBODfrutukJNYnvIZgwbBJsTUN7w8N+chVuAmll18JKdbKkbAM2Fpn1kDCpyI4",
	"JNG8hTaWPtS1m1UmavyykkqfVVIvG7kE8XPjUP5wE4qZ+E7qUnpjtz1V/pTvkCCeSgMKcUIiC9csI0ZQ",
	"pbY0CjaxWuIW4YaMkbrDUANC3BURiUGSRmkva2AJ7bV5R6vo+mQc07TSOSAkE/gNoMm2MW1jLTKOT7NU",
	"v69ZB4sSlhYo/VKA9VJpv52JCzTYGlmxsqfzt2tZVdv4pX326MD+PMYwC8lA1DrRcQyK9blEOmWMS2um",
	"7cbIiQML5Rmy3bO6Qm9Han/XOCg/zgI7oDJexctL6b9O/Zq49E6UsdMQ6JLEWagToVdkrqREWHR6ptyf",
	"bqNcFO0caqIXYj34G+mK04X2MU/Nipb/7MqSaaowCXABkaiZO1tFzqcyiCWE2uqjAABHS4K9zB2jj3sC",
	"fq51V9ENoogdBxYlEa9fSWrpNKfuA6XLx2DGg4r4ZL8Cl5ZzTR3tosN+wXjdYNd72sm6MqtGlcvdW/R1",
	"z5IcxsmOzNN2o7kHy7RTf9Px/Ofgqi7Kch8mD18bryicYuzGGiVw9LjycV+378myLNkLHci4rCsqWwd6",
	"Jr7X0OmcSDez273yaEG3VjrgWT4/dL7ptfae7BGFq7HnxfFVqxTZulXJ6t4I4u+karVztkcVruJmyLAr",
	"jyhi/Uq8C6bMOw7HbPDTJEudIZ0UjFnrYqzD3IDl3p/cfQ6l12m2yCu4UQRVy5gip9gZd1frynGGW9S5",
	"HusAp16LK1OVow7w7GE8tIuigJoKObh5W+O79teruJtICuyB4+sJSVEgFYpYR72WH4Z9Y5N3QsZmdEeQ",
	"7MSX53+la9/TBXnESoiE1Pc8Dqr+uO+9HPc6HftwTdhwQDkeVmznIyxQA7xAVbHpqbKBi4QlnF+3tBC5",
	"xjiI5YPUG2gSqaoHr2opog3T51rFkYkZDp8yEATUR4sTrSjoQMvbuuK2ZAzNag7Azo1fxWCsBjXC5vtb",
	"d3DJ9WfRn6DLij08OtXUgUYWpttK2MXoJinFlUGniKtSZeTMkP+5i8ZHqUsPMiTZgFT8rdweEMzhNQ/n",
	"gbMrcuXf97pKMfTamrXxXbAFJ5dQLUlOC7WVjs6LSt1AJIIuxO7kVzguAH2LpuP3Fq+mwzgxXk2tFTK3",
	"RGWzRpRWbkT38fGsIdJ36N7AVbBUqO9WaDY6Rtz1UEKzsbRfyvQfJ+hRAlA3hVwMjuLLi+RZcp0DpwiR",
	"xBaqqtBgPAoJ0OKbIiBgJhgxyFk6o6uP6MZ3t5H6JnTNpmvqSUH2kddXyrkG8kb66++/E/TxoKKPCPyj",
	"4gh7uuL8T8UlC60MUqwbKQheq+I6NEEvjJ6J0Cqjf/R3Ex1ribAT7uqfWU5n9ngwm9uVLnCFZkD5aluj",
	"3eiU2zcWYkfVUKP4gxC52E/+WQUUdVGLfP95C4ZJ+daEe3RiuDBcFEQLz8R3HJheNNzMRXZOYyqstFBt",
	"ReM46iuFNcYnxOrtU8Km0XG6zQ7Nq/9OYGy6J4JDLStJTXhd25W1tWE1oN8ZqtEom202mftaqaq0uTaf",
	"X1MAPw/OiJIVLycdDDjR6BLCLAijYT+CP7ciuu2Fb7sgJUB7DNyZFDkZyzbHWUFZx76PzBwienOPjLbf",
	"1V50zUZylJMbvHMG5SCgPx1+2njneAYr55j6KBBBn6uQ/Q4wVaavRefB2bIxfE7qYcGNySRFQ6kMZZr+",
	"yTDyYgVU0yQ1Olfb2d3ZOKc3RLwzzUa5A2NDWb50be9wn8bU/NY552MOOqRRj2o5mXgdDUqlwc3Ei6aq",
	"QgaLk8Qd6fiVkL2Gdv2v9fQN+q9CikraZa4Y4FjLOCiq7Nu8TD1npRdmEyCEtJR4HhJ5LPxWYBUjkBod",
	"kosBYELBCIH+TceaZdheqyKH0QL0105qxfs6/iLfrXsuS76KyphrNxOvwceuHt4queSmZzZ44jTKI0D+",
	"pLXqBu8tBMoa7VWVco/U+JP7QQbDbGPstatlscc4S18ZGGgD7ry9pXZqwKVn/uxLizMiw9hr7t2iqirU",
	"y6NZd6lLqEGXFFJcxPE7pSp4ugS1J2acG6lGii1oE78jtuAZPoH2Ty94Q+pyvKHXjz3x2R4j2lDf7Jgn",
	"CULSZvf5Z57MuqmoV1Y6jh3KtDVGcTjQaFyEQmyVp95T8/AnZdjLMFjpuFv9Ifwg36K6NekSeW9WqoK8",
	"rcl3jffWyVV5w7YqnoVg4UzJ/NDcNYDjmCgoBB7LMuMldKSf2L0oaggBIMJbzDpHMBqqfMUxvphrC1/f",
	"G6w8KCTvAdhANHIErgFKyo8oP45ryLlFHbHetqlLIIA29z+UWD2bqUfLHfv7oP80jhPQsAkFusGV2uT0",
	"Wn/+VqbP5D6D69mYmYUcvZA2mFWSfQDH1tZY4PojtX1n1CVJvB1X6DCy6S414aVWXsmKYBnOrSk+94zF",
	"cVR9lfTBCjtdmaUuHCZVEN+VQptOuFdyyPUhn95GGSTzbyj2g2P6LeilX02efvGXvxyKP/DqB1nhcELx",
	"UBuzPZnFHb/zVinGfuDj95tm3Dn1u+mRezi9iEqU+qhzX9y9GUbhVAXa56bU3EMc5qQ05F6J+gI2ovOX",
	"+7fZXyVLPEoqZJRV15JX7lgx9cys6wo8YWwrWVCvymQg9DjoMyd6Mo3kmbtzuXU/tvkzssMG70Qyj+OE",
	"BJg2HJSj1rJsZLMWTKbuV+HbFIioQNrk34zIW6QO+ugIGXqvNuwd259H2Zs/rra7xmXH7jyId3u47PMJ",
	"6eMcvY1Wp425gq9RUGrDwpUG33BItPGFWbeNJKIjFg31TlYZiRCtTiLZbA65t9E32SK6i5hfFYtKek8N",
	"jRecLD6rJXUH1iXYYP4d27zDbkfmQoe1CFUNZwTnnjJEEY8hDRAlmotdkXsANEVgy9qvUti60/pXsWcd",
	"W1xsZEW4U7ZRM8LqFuJl8mE6GOKD28mHo6nUuB1/YIwPlVEJ69h50UlWBY0RKK86JM+fcvBWY4430dtb",
	"Ypg7AVOZKo4wyXd2GVfeh9p7YcpR4DQXa5iYGt/JjM/E39QN9OAOnXSoKl0qNungcNssfAyN1lLZlIkL",
	"Db5VO3MT3U4/2s7u1lgD8YqzQKheQrFBSlygcK6bPsJDyMabtfSqIMw2QwaVTcBTCsSdUHF+W8TCd3iU",
	"EZ64D719dCXsPabEVTcfzv7MUt2EAarHJ4ozrltnEPvd2j87HNQe0BjvHPagRkoJ9jhOMfF8W0hmvr74",
	"d+MrJRLLC6TehAaXcFfoLUUEDH3EaYnj5nh+lWqeO7/tdUAdwwf15tH0hllljYKxOTiDGkhe9WmanRrG",
	"oA5HqIoSPFjUXc6roteGjcNYnRmrHY8SvcC04Hyb1kFONVaLRreD9FCMr6QLk3m6tVfDIay4bhrGkzuB",
	"VxG8NDKVoakq4YBcqlTnoQKav9MXZFQl0PSuPALEdeeBcTcnHduGU0ergUA5POyEZeGeopaR/cSqFter",
	"seeapF5JUhIfR20qPnZsW0zTOXnbHSSdBt6FfEhIvVMZi/haOeRybnxAyjJEJ47eJM/5PHI2XDjAwYm2",
	"75KTIb1z2FcRFk+fOsjT6XNHmp1SInzNVDDLcnltKOiBt8aDg57yAEYnt8GEQdPGJRUwKHutYCmreNc5",
	"i9osFmAJgNT7bZg+v1C+X9bUKfFvwT48KbrspLGDz+daKKPU22yTnX0jdHqlO2mMDp5kOzTnt6rpjeWr",
	"435hW86aBu6WoaYq+jqxuFW8HZbDMj2UVm7asdp4+NaazQpkGRK2suw0zlPskMptvv1JKJZCarsTYywi",
	"3vSgJm3NAw+tD2VpbdnZ/SyueEoGc5M3s9NGH03DMRuNymwOLg6YifVBJw1D6p5y/7U7VJOXJ6j0xjuN",
	"U6bdG7Q0oPadPkDUoptLAKaCRshzDh9VGQ1r55EAM3FBPS5CF++OEV3RWJ7YkVwbfUZdLUeCtHY9urlu",
	"6Svtksw9oHFEyq1gX9vhfTVxR3kaJ4eSnNzMxN8aSa2XQ0pb7sazj8047osnDRU3fTJ+xfyFkIy24KXS",
	"ob42V4VwXwc6nmL+OTSH52/M7uw2TjzrtMWjZsKOMly+a/NlaG49p6CCLHzDpdQJ3lNXyqNZGyJ6o9wy",
	"3tqYdOwcqGda+vLHFjr/PKKXhkt2A7O3XXEgC/dWv7Rn/7qTLck0HmqKlSjlWi6hhbQWpqlKnv7EACYk",
	"oha8JMufG4pj9dBLRdGsm0qGKafRl6jMhkZBlapZT6aTlVquKPGvKPiS9SmCQZmLr3bN2n1W7TM2SKho",
	"Gzz6WqHBmgVC4MkqKP3uCCweTptCWYFjyGDjvIU3XK8QnclY7UNiRBar/LDePWZXp5Xdu2BpBdOLnNfQ",
	"qpaisTTxouMtDU7tNHXPZ4yaPZvekY6riWhsydfBJYUYzGMgcyiRIBM6gJXQs+TJ5eLtpVha09SxpNmd",
	"aCm0KFLnZVWF/BL1NfrH5Dv5/qWkgXSvL59/94/J0ZZDNBVG8+mdcxkm9+Kx9Mmw096wX0UTWcApWFOf",
	"NzuZTjT9l2bNoAUjdTk37/cOlf6hzWLty0lF04pD5BvTNrRUURi5Ffl3Os6cExedjBRlrWj8U0Eo1alY",
	"yMrBVW2c8uqGSzyv5GLBxrOx+E2TpneIiy64Jj4sCalp25No8Ms3rTND+BjXwTN1B5Hs5k95Z21GxFuA",
	"gAXtbCXkyOcQE5LSMUfxa/bmgYe/ocbuvXsYPxhfni6wfYPjSxEpd8208xoZkSXEHKQFe9Fw5oP/9U3U",
	"Df/545tJrh7VIZVdg+awKgV93PzcXktqRjUT/3UWMLVnl18H/9F1+yx/FdMTZP6QQbqSN4SHunyVWk+z",
	"QCOhQR4O7a1ltpX39eTDByo8W2RGjLx6/vqNuHh5STma198/2wWRBFeWIu9BjVAYjjRIpQoIc0x5xu/k",
	"opbFCs6+mJ1PppPGVmEH7umTJ5vNZibp45mxyyfht+7Jt5fPnr94/Zx+08qfyWs+qp2pZBcvLzsmz9PJ",
	"+ex89jnBxGvQslaTp5M/z85nf0YZL/2KLu9Jt4iillaugetGRgRw+5Un4YIuWQTXJueKcDLHccNdnmKQ",
	"ygJp8AH7HinbR95pGq3cG6tMCHXNqbuAE8vC9NMQ0csybeB5jIUGDfTvptwGu8uH/sHkDXFF8ZOfgzHL",
	"2ua40FtIW33oS+4AY0gjwfBZX5x/fsdr86p7E0884INLptD66U60iBkc6gqF9PIl7zC3cHqTJ2+7Q1Lp",
	"R38+/KNv0ihV+sWXh3/xwvhvaN4q/uCLLw7/4Ic0rJTmCePv/nJ+fvh3l2HGaOdXnx+1vcvOVNeuiCQe",
	"6grHv/+EjOLiUIbJRVl2xj3Pt2IlQyRg6VLIEVnzJ3xs4tQnv6Z84wfmuApyCdOv6e9D3puJV+Abq534",
	"8vyvwXPkwokWY7876J75tduHNlp5Q5bjdTss16P9L8c2Wj5qyjv/6+EfPIvzgB8vyfFRd6guIRICjeTJ",
	"bzpZgs+590xH4bdnG1XGymFKcVGepEdFXHusi9CdOuTOQC1Xc2NdhJt0avD7pPU38HGquy2HtHV+1zId",
	"VxmRrQV99ngp9pESYKhmLvj+sqR2aytkevDLvHq0WPLA17eE43eht1unzB8JNragmYk3WSOF2zPF2c5D",
	"AuaHP4A5wqjeo6yR8weyRuLgrJCY/mRnPBjPlcq3Iv80A+NJ3+V58utuG4G9JsgrWJubwEt9TYCmxrSL",
	"nQjzA3SnvQ671juOA7fccX0jRlG3tji5KaigZK+44Afumin47VPMFGto/k1SmWq3HOCT9XLP1os1dc52",
	"6V/Eb6lWDn+357OTJiLWS90G7t4Hv6Tgq+sN9Ib3KOOVb2FFiVe4mw3/mSKlPcebZodmHISZGJtXyDMd",
	"qDGreAU1e538sE4vw6+o6Rh3Pl3LrQgjP4T0Ym2cpxm3bbuGPifzTM3nse/BvSjV4YDnh/b0B9NDM2q2",
	"Pz80Iqr+UKLpd6Cb8WdHbJJj9W+1vJGKoYonCcOXeMVxoInOsGRXEDJvBDVP/3jya8T+nhpEYOzvMTGE",
	"7aHoXAgV3HDQ+mgV/EnXPmikgKypfYGCSF0HwgTcTq0/h3HanTzKc4BZ9cRZfMMAQJ5azu9W0o6GVGOH",
	"4k9+/0nk9H3qOBn6YOfp5z6NNFxlx+DqCMFH5OgE72XEz2mTkp324v1ug1lH51Qh+8nP+e39nL7kPajd",
	"H4Z/buvj9BkMTzCvLWJK34n5VpSwkE3lUzuCstNLzoIWZsEVutQ81WgQFdxAxU3tvArVkwtIUxcsdNDU",
	"qQaVey+lkkQXKrGGvPStcr6fdZ0MDj2n/Mb2nhl0obTzIMs07tUY3+mOEasFCfNQqTALHRciX20yjcnm",
	"thvHtKP3DpbsDSoVAGrGEFFZtAkI8IBFGPZjyG0ldVM5Tv9ma7j37Wy3tUM41lhmP7qtCCw7dmNtFf5w",
	"N6+bOR9iKC1MvXhDsXduA7/0Vs5cxQE2+1atlT+GH59xlRUKmXuzmoadPDIW1Hgvj4dUK3+s6C6KpN3D",
	"bHXDzgcfpSNGI0wBhzXogyVjq77Y/s4Num7k0BqXO3ruPgI6uR5MDxzR2Skmz/sbg9ZAD29/3Y1Thfzw",
	"Kqwz9rKhOh/FIyFHkw5re9FSsysRpxumzoh/PLb+nrqQZGAYPXQgt8k1Gvax/ND4OtG7iUGgoXcTTKYp",
	"NWNgJ6eUXoZaexeDxoaxm2U7GqlMFe4z8bLn+KTPtqHsNI5ZGAsfDcXFHwBw8uijQmPOSEbhZM38Yb8J",
	"AgFSW6jQPI9nO0eQf4JYKh+w5hGvTR9zU5WNxAf0WycPIkgHCOb8YSX878a7fsSRpROI8R495KHbexBk",
	"ksppXROq8bgsoW051RnK0+k6NTqyh2pHFsquqZdQV1V0S0N3E+UhwvTFF8yE70rwUlVuxs/8tzTgMRpH",
	"72biIusDcqUwvhTV5nN38EybrJ0+RjmQzINbgb8JZOYoERGRM3/cQNwfzHhjCj5JTR5lpD1JkwNGdSoX",
	"+srKaJiir60093Z+E7q4Ud+AuYxlKqFE9JcGmhArU5XnmrA4NGAqnLG+2+xjHSABIRLN4GBuJK/FvKmu",
	"84GzNGvrYNCMm/dQeJsGb5EJGSABM/E1xwRdd5MxrN5WRsL7uqLaNaqF2ReZgn5s6rRpgzFAlesrvqVi",
	"jYWx68m++BVfGYV5Q7t3Gos/E9/QXSjuqsR9U9I89zinj/u0C+kZ1o93GkYsU3//OGR5NDjXzn05Sl7F",
	"mQWH34f7V3AxMvX2q9rWtpl9DOYw7wuM7V/Zm6ZYpYU1DTNQOjY94Cjsnp20E2E/Im5KIXxIte7xTqn+",
	"ogLnuEtpbPYn2Z8d29Fa4bGkrqfdjR3ZtfT3Fk3sDxk9EElkofgJT/pweNJlO61vTMFRMOA3sbgPFKL1",
	"06ecem3bkaAM5RgTYRHCNOBOjSzV/FGrDk7nUkceNIfTIMPwzbP40LPwdW9VzU0aYj53LADajrK9H7N3",
	"d0j9Awc+O5N6x4OeECb5fjJxH2uOWm5Sl6Vh7Vpk/xPM2ie/hsHexwHSwtL57HjbDi8XMezz16do4QNg",
	"yPiwh8phrx/ThgTb4F/ppqF9OwcpRC01VNk4355rPn84YfbYBdljBoyNUc1DmhSHf5JI4LiYX3C5Q/+R",
	"VPJIxsirfZG916FrS7AnuK1b7Bx4TN3Zg9kVv0ko7SAnpgK0T6bF469XM+P8fyub4klUIePAsw5MOfZm",
	"UrttoiL+KrZG2xPlen6T/PX7p/m02Fi5Mr1JQAp+0kankmQqrCGzxFI91SNwd2+hm/IAnrLchSHGTL3j",
	"V44M0KnzSjwxKObKlGiVZZ4v7lEJxXUuyvI3U0WH2LJtP7fwoROsLEv16PM7fyyF80x54A7KaXjy3eqc",
	"I4utYhUB6b4ud6FhuDY3obMnd8Hs4CFgzW7woDagk9k96AuPq6svx3ZafqLRB6PR197UqMUprx/E8+9N",
	"/5xapHMEw3W6l2WNuudxjkp3fvBg7peGDbjO4NChVfe8M0x9X+ayk4uKK0c8+rXSZYA0OT8VjQM7Faqe",
	"ioWq4Gol3Wos/+O3NdwiLzaCSd9pWBLasXdbnfxTANZjn5Qj8kvx7j9JuwdtE6QOZ5keqsPDMRVNWfmU",
	"+jrkpRMb2XtlE00G4J5roX1WeSVDc91yJl615bNhkl8sJ29D407pZQVnjPaK1U8jci4aQMdKOX6DrowL",
	"bW7DoIUr7u5vrNDgN8ZeXzlwbk/6nS0lEi63RQF0Gl2gKRUydzQjW8F6KqC0U6HxP9TIdrRAqG1v/JFb",
	"obOJs15oPHqNh6J0i8vpNB6W2m3AOvGPCYF1VrImGB3Lb/yDcZ6bBmfPLw0j+ygAw7dmA1bMUb6ItnMb",
	"kt6UkTguzBjL7QGPPr/8nqHtwz28revRPcD7A3vw5g52MFChN8FLC3XsDspUvI70VZj1GjmzUhrcVFCb",
	"1TTfCdw/h2JFmj9Gr3KB3BrwsD7p1gfTrW/CkR/UrQ9SVnxbzcoOz5hifRFGEMXBJ1wmzFWzsUH+WipN",
	"M1mRvV1jFzLEd+cmdCNOE0qCjUwQvJikicX7pHRXRF2dguU4fslTLyO2sKkwBsU6tQkPmEWSYyWU/5iI",
	"eeNFaajMqagaHwNCtSp8Y2E8xXlIW19UzoRQQDsqjs4klOX1q3gFHx5tvQZ7hoeWBkJRg2ZUQGFUmRNG",
	"F4Df24kf4ilTB31uGcXTCM5oYM58K5JH02+heHUNo+W6Af55FUqOehIzHHrCeu5ONLorfJ546yDOD/cr",
	"pQnSHkH1SBzHYS7vBs93t5DZr0SY8RtpO3QIq7ZUvgVh4hgNgm1o4FrjHyHM9t5BiWORXJZHn7TYQ2kx",
	"uoxHCkI8ToPRmLy9WP4wSG8Hy88wfWPDMC7k4loV12AddXq3PAiHRldyRWY0UAlNI6uKETUk+zY0KWdO",
	"A549ira8V0ga4cTQ1zZOjrUdV6gzQHIMeT3w/I4b+3Z0+ItQmzQi8Z/CGk9jgQ8Y40yNn+TXQ8kvNrJ+",
	"pyBq3Rnj0fL1TFwuWhaLUyUITe2mKRdFWfSYQ44zbnMo6Bccd7mPHHFnzvxvgX3mkdgj2GcqV/k0seNR",
	"Mu1LNPWZvLvz+G+dLyah++TXUHF0dIe51EcObsBy1VNb9KTSzOA+h85hpagrA3l2LrjBKtQgO/zTPybo",
	"e26M9SvhVmZD3k3nPf8xmYYRaqkMba2cl9eAj0gzyXm9JXjqT2E0jOWeE4f/AdLNjzXYI68hkexisZdm",
	"p/stUSQFtBzNRucg2KE3CUVIC2nLbLwif+PnDyteP5HRrdDYOkwvfuSIA7z9E7wwRmN/VOf1uzSxfiQH",
	"TopVs5Y6jUY2loIujmJNFIfhf9I00yWlmELYCcqZuKiIGbXxqBCe8nSELeOE4kBxiVqgoiYMacYud0Hk",
	"KbZUsbtoHAS38cvzv9JqqTVEEfDH7p3Qch2RSVSegd8Li1PFuVXeA0cEHbWpNrVXqDhUId5eUssIa6qK",
	"qtJFbaFQDqrM9B+ewturIr8P47A/XfuBkYO9ScP7OrzzNYUZw5/Q7I9XdPKNtlFXDryERgm3thwpBD4e",
	"Oxp0FU3WIrMl9w1TfioWlUTuDA3XLJwR3iDEikQJtafISZgPDGs2LsNwYQvzRlVh/DX3TtXcw0A6tjC1",
	"ERZPyqkb4D6sSi8Pd2V6wxH+h2m7QouN2Asx2/DJZDjZ8tztq/uI+jIhj6WRJwcLQiJwY1sDxTFCyRX9",
	"u02iLBsLZTstOkPhr9KK96pA4iIZikbLoFTU/YLmKj8gWT9a6RyOq38uLam2ZPJxvVN5V/Ym/pTn/z6R",
	"tXpy8zkZhGHFQdCNWmGTTUX2XerpxVSWsqM7DWDfnwVE54vsF4bh8pc7Y3vSbONhP/vuwgkxv7tgqjUa",
	"XShi/OC9t5KSjjybKEDKrJBlGYeNUiK+t24LyB2s3OI1h7OQBkXiHPmexmQ+6clQ69KuFl3m3aVi1i8L",
	"Ox6IjH3SIrXBaWXE7mLtZx9++vD/AwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
