// Package spec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package spec

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7L39jts41id8K4TfBXoGcLnS/XQD7yRYLKqTdE/t0/lAVTK92Jl+q2iJtjklkRqSsuMJAuxF7BU+V/KC",
	"55AUJVG2XB9O0l3/zHTKkvh1eL7P73ycZLKspGDC6MnTj5OKKloywxT863mttFT2v3KmM8Urw6WYPJ28",
	"qei/akZu2FYzQzJ4ihh6wwRZKFmSa8E+mCv8+zWRC2JWjFSKrbmsNanoks3IS5HJnGlCSSU1tx+eEiEN",
	"oeRfNVNb8l//5/+SXMKf5jUvciIFI/MtWVGRz8ibkhvCDTGSaEOVwXHtMHO25EJwsZxNphNuZwvfm0wn",
	"gpZs8nSC05pMJzpbsZLa1ZltZX/RRnGxnHz6NJ28FIab7XneX/t5zoThC86UXRgVhMGjMF9KVlKbKaFZ",
	"JmthpqRSMmNaTwnNc8W0JlKRFdWrMLeKmlUzNfzUFc8n04li/6q5YvnkqVE1i2e7kKqkZvJ0UtfwZGL2",
	"aybMuMnbJwkXsHWaFSwzLLfT/ifLzNAs7Tt3n+TPilarl/mSjZtovmSwx5YMsoJye9rUELOxNAKEpBhR",
	"rKCG5UMTz5fs7vP+67aSZsU01yMmTlbhaSI3guWWhO1ec7Fm2vAlte/5A7DTHZh78527r+A8HnvU7idn",
	"O5JcWu/effK/8JKb/pT/KjekpGJLuGGltnxBMVMrMSPvYKpqzRQp6db9mSzYhqkpEQz+LhUbYhcFjBfP",
	"MWcLWhdm8vSHJ9NJST/wsi4nT797Yv/FBf7r2zB1LgxbMgVzfy3zMdROlvZqAFnPiL0hmii2YIqJjBGz",
	"4ho5pT0Dx3ykcjd5zlZc5IQPHYb95t3P4C0eeGopl/Mn6oZ6kmhoZGElxIrblfyrZtrMyLkhOpMV0+T8",
	"guTU0KkTE/DmN5qwD4YpQYsTLWuVMZJJseDLWlEUFlQEyiOXLFPM6LDoFaM5U82y/9eJm/LJ+Yuda6+o",
	"sYNOnk7+v78/OfkLPVn89vHbJ9Nvv/v03xI78cl+SldSaIbyUopFwTMgz0wKwwT8J62qgmcw7dN/artN",
	"H6Mh/5tii8nTyf9z2kjiU/xVn75USqoLNwQO2N5uS9yKZVLlJFtRsWQ50RzJhJE1U9reV/vfWcEtfWhm",
	"xZL9w0Zxw8hG1kVO8honyIDTfuDacLG0nHZK4Nh67EoTWihG8y3JCqlZPiPXOTOUF3qWuT3Q16Tg2mh8",
	"PdfIrrOC6hXLyZ+s8P/v/tk/zyafppOfpJrzPGfieNv3nBYFU7Ce2qzsZbK7kJN5bUhGBegjmZXgSYb3",
	"jSZVQY29LyfI3BVztIrrW/gV4QLPBRI0TOt4i3wvrM5U2EtIeVErZg+VkooKnjXskWf29PWGKU023Kxw",
	"xbRkhNkBCBNrVsiKEaotr1Fbs7JEwgrNpkRLQj2JragGIa1XtGKWEVdUafYMvlcyremS2Q3PWcHnTFHD",
	"ii1ZMsEUz+BOGyBpWpCM1pqRpWTAzu2fC7l0O8vdVuLGvpbmJ1mL/Hh7+loSXWcrf/eGJCK5AGnD7BPa",
	"MJpb/v79k/8AdojvuosBtw52c7NiCrcUdwInQXK7D5YgFVvb3TErVrrNENJcLez6w26cl1XBSiYMy4/L",
	"i2TFkD/jgrTfGTsDRTMDN8tSiJCE+0niC1tmovXwZgV/npEXLCuoYtYIQOKLBpozJBQTETLXZM4seVrT",
	"wYTRTxZcafO0odWMCrLiOWvmKIv4qPRKbuxnLFu0y0epcyPkRqM049oZLe5qzcjP9pzohm5JZcV5mKa9",
	"NjRbwdXgGtivYQIO7BJ4xntB15QXdF6w453ZmSB1pY1itCSgqbjZSkW40Z6OT0BQ520JbFdRN3NGTtKR",
	"E0azYmEf5MLY08fzRR55Fb2MhPteWC4sFf/3UclWWruVa1JyrblYTklJC8vTWT4l7EPFge4U0Xzp9Hcq",
	"SC0sEQhrArtF1dHkcTl/owXPYcpHZvgXqGIh40VhtubSWkbW3FZ1wbxNnsuScoG2q7AXUmrN5wWzRrWp",
	"NTGKCm+cUzx+qxvas7UyQtaGsDXPrWJqHwgb530CuDXrsBF2Yz55fQtUprPMpDwMv66kvT/ua1QQmsGo",
	"zsquS2r5ipL1EgXV2dvzKTy2tNda1SJoLoElIC3a74BuQyix08jrAlR/Jqza/vcJFbTYaqvww6es4r/V",
	"hpWT33rq33RyZh+xCjqojspedsNRFYS9go2x/wpWwreRjfAkfFHU5dyaCNOJ380rNLIVW8DXwKhxH/qF",
	"iaVZTZ5++93/Cx8L/05MsOTiHF9tfqVKUWvf1IL/q2buZ6sHgzZboJlmzw3G2/19d5OBWA+enKFqycwt",
	"X96stnvn9ynW9P8eT7Y1eHfZ+PH0WTRUIOeWMzZUAIbYJSgAHG9zj9M6Y82piE51CDqDcwwgBVMw4jSZ",
	"U5OtTgqZ0aKxAS29tqntdnvoNuSws258VAduP251PGbim8P7a89gz/au0cL5yvbTe9PucTv9Jwd387Wb",
	"YmcPCfIEEvYH9o19oJkptqC54LV5GlyHp56m/cl4Ryx3ez3tPeotR2oMtQwYlXvQESLdAfh3bI0KmTPU",
	"JruP9o+vRaPtNeI9Je/fn78YORP7+T0ukakf0dFNe8hfwm62HMaDW2YHPJDyYiLqrBcuxb0v13PEEauN",
	"buX9LNb7sPa7qqa3usiJizZ4kS6Yrgvzo11JXwdg+ZK1xfcuta5RJj7BljjJ/MOTJ086stvTGz/46x0h",
	"1Rrou/RAax8aOmCYNq/uLqc/CDjwDxsDOFh7/slPa1leca1rSzHtIfbSzmHKU0/ZiMcN+xidnF/21NFJ",
	"isaeW3vhgwn2Q1fHRC7enzm6WRLeWbpgRNdlSdU2aPCZYuB/poWeQvCNMw3sd81ELhWp6LaQNAfvauKC",
	"GbX1Nqv7dS5lwahohFw6xtbXzSbTiZNkfgXxADs26LyspHKXccc9TKjewT3fvlN7ngyXYvdzCy5yLpYj",
	"ngw3YPdjmmnNpRjx5IYq4YcepAHONHiicD812aykZiRY5eARYR+MNY4rqiyFgIfd36C+Rt+6fJ0jDpsR",
	"LWPMvYjWsoMCdqiG6F5xHloeQi26URW5ID9TwzZ0OyNnhhSMaoOOGsNKQjMltSa0KMhC1orA8sD145f3",
	"LFiaTBFn7TLn2KPLpWJLahgY3gO6yiGc3DFxWNQFW+xl4mlL70C+jiw9PeYPI4eMb8OoQXG8N3DUvVG/",
	"HTmqZixvRe0WtNCs6zJ5RdWNJjlXDFTdQBm4TYT6AAD8Cc1CPF5ZMUtWvRjJjLxgiq+jTyjmo41U3bDc",
	"ftN+L+KqMd+MLvqx9uqW93XXpQQvElI5ulfszAtmLGN3HCXpWEEaT1koHY/k2HwL0op5k5KVc6b0ilf2",
	"GmsjFbOWeEUxHtG/pTTPWX615uCco0XxZjF5+vcx9/SN4ksuJp9+myYC1lEEd0M1Kbi48Wo5g+gZ8KaW",
	"cv5pOsmokIJntLi6YYk9em31moL/OzA7s/V2nZX4XEQ2iN34pFjPua4Kur3C+GlPx6dzVriQLiPvz2fk",
	"J1oUVqPPbuz0WzMkmxUThM41ExCVFnXhnNwYfO2NDU76K81Ygpe/pKrg4Nt0kV80L+AqlnZRUuhoW1vG",
	"jGXKJ4aXbMwk+N4wfXx4uK9R+HqUFVXQwXX+YgXIw6+yZIbm1FBH4uDppcXbiPTxxaRA1RXL+IJn1qBU",
	"fF4bFquIDTNA3S6hiVx4B4xueCmahm5f3Z4aKQurnDBlJTJcFQh3tZSRsSKzr6fgv4PbJukvsE8Q+0ST",
	"aNakZOQcNA+qtrPJPmsyUIL32bRvc7NbKbaKk3lOVYI4fYLDhueN4rZwTpRAJik/yaEsLcHM3jV3Ac4v",
	"oyqHqPpc1mbWqMxXwKcHvBTaa1rRPYpvmaE3DBVRwsWMvGXqJKPaLrb2ApYLci2zrFZIVtfRecTKNuPL",
	"1VwqPXDcVi3OpBDBj+gCH1aYW5W0RXftHd3NN8+NJkWXd465pzscWnbr3YJqBRH5Pk8Y9o503P1JEbWN",
	"U+sgAlNRxYS5CtK2kMsly6+4mDb7dmXklLAPLKsNy6eQGVGs3Z81LdmVFd3770s7JTKebuqCdC92RAuJ",
	"04gla1f64rhTTIVA9ot0tuPwd9N4yFCTC3BFO72Qi7XdmA477xNtL40uSQmHu/IMN8UAqcJPIRPBRcYg",
	"Zv7POl8CSbA1tRzQuxIsB7c0yEecbCIvEOfSYRb7zzlJMt3PtIlhF3c1bClVQrH6iZa8gOOLtCdtSZ4q",
	"bQ8Po5GQkby1/2NNaKqJYBt8FO4RaJJxxNEraZYPMLOR6sb+CBfHjjudVExpqwsKcJBQrRmsxqyY2qE8",
	"P1eMGrYrDsWEYQoZ3IqKfErmbCHtDMXWUXzQNfA8O96nu6qhMWt/GD0Usjr8NElCF70nhehMRNlQZCOV",
	"WVkRqLb2b5Zhou6CRmLOM2qkIhktUZuAbM4B3emImsmwUjJ8WZx1k+R1jZUBKzWSzBlK70ROcXwhgPYs",
	"l5VZFIb3gflhin+bdHm+EQwqDsK9tdLd55m5NAVLQVZl4qJuuNewm2ZA97Eflk6BhRqHw9TTlPyK6igS",
	"Gh/V4Jm49oUWRpIlQ5XJvugKLc6A2onLA7U2R5jdHr0jxVf5Tub51gdCOpyTsyKHLD5MUp2RcGNkyY1V",
	"KyzPhNVwQ7iekfM8qqsAI8DSeTi31qW2j7hELJZz4Lv9A9zNSV6zTVIzuycGccGqgqKdw7y7obGayGYl",
	"C6apFbZ2ESVTS7D8kYWVCc7wafAILoPHvb3+BTPZiuVX1KSybVjwgBLFaO5TtT0fCawFrZNBg3NfSLyT",
	"fWu5lrOkrY2HVqCuq6rgLI8twdlkZELCsMGuvETG8iJLN7WOE9Njm5MamNCuYdPBTy5u7FA4RjBqY2M9",
	"5IpiFogf5rCruCeLYhqf9m97SOUCF9Kmlp3n5ikl5OXnbAr7yD7QsioYqcxJST9U1ChZnGiOFHyL9JIO",
	"JwdhQwu/kT73tjlkqpskvTa13iJP6JAUFdzPd/DnXXK6Ca047eTs7XlKs2pU0EMM86C69g30H5WkOVmg",
	"BhvY6ZwVUiwtY56RX5jL1cfik0wWslbB6rvhIteEFvymUfZvBCbHYkKu3S50TyZp5ld7F66DjnENGXgi",
	"ql+Jq17ISlp5Yfk6OnhrzVTk5mUl5UXk7eXV1KUyTkmtiilZ8IJd+UK7sSbPX+uSihPL/uCEBOhnu6RB",
	"h24cwXgjJpxikmBaOZy9qfwoczQ0YGuFFCffffgQcsFn5DmkL2syV1RATjG5hl1F+eFE/V/fvXvrEjmf",
	"OsEDSZ3aStqNPY8VrTB8QY13uhiZyYIUbM2KqcuKzlnqFcfGcNsT+pIPWfeVJV+FgBmZM/IaoiJWX7Ya",
	"lM/sJ66gBCuifnjyJHFPkpT2imYrLlhzkIpRLcU0WGToZLLGK9VMz8h1k596TTK5ZkqTuTSrVkLr3J7I",
	"n75/8uTPoIRQsmFFceJ/rI1VZ+1nIGz4p++/++7PM3LdSWS/JiWjThjcMVEe82BvmcUeK9tx2jJKdVeD",
	"M52EsgIIy7vKpumk2a2GO0ap3O7FaNlQlIWHmtTe3UEfplG9/GAUDX5OwxvPDTAi8jdX+xTKkSCe4kqh",
	"qAbdk+ew7ddNydIz0qzO06lGTmDfXFg9NmmnDWZcdJgK+1AVVLgMN00XIAjs+czIT+irDfSPZTegDqeL",
	"ZbxmPFwsM5pn+en/llI0WzYAXOskR1uzlNfrTBBeljVevVY448CYHPih7OVyrgm6tfZk47Qr68Jwq3y0",
	"7Ep9iCX360pafewGrVRIGRXI9TJa0czqoQToDvzCObpbuVja4aRoKx3faFLSqrJPVEpaebTLcbjbvQuR",
	"0oxX1Nyvf/fcaKJkwTzvwZ0F1pIZqaYuL2RKtMqmJNfGVYtBURgKbnsMViJQRcyGO08gyfkCLAcDn9cP",
	"7eXFbEST1L4iN5QLom0rNsXiLaq9CnGFIAJS2VuD3ojbRgRhkFsGBJGWdhlp0RDWVnbPj7fHuk7Xw9zi",
	"3HmtW6S838Pcy/bzR3J1uCX9btVwgKqCirDA98vSilNfp2jpWNeOgrF8JKJoVIXgGeld8WDlNrSLYUcr",
	"XOfw9Qoq0Cxb0Iwqa14lRYFzM+84RN6oUVOoEotsFfLOlZUB3wFNnZes4MI+oazKt70n6/vXFc9WaHdz",
	"03gjcU84K6eE5WpKhP0fLhaK7jTCBxOQ+1ckrpn0hja5dMqZy9uwevdSQgVf5MuVzgK8X7u8VY8xKhw3",
	"YEBEvEavpDIh01L5KtD5NiSajYsU787v70RMkAW2KbDNVAYF937faYsUb+E/DflmqcjvlMgiZ9oQyP0Y",
	"7ziFrDTc5CO7T532RY1DrRGElZXZwm9Te39XckO4CUq+wPzZAz2uuGmDp/ZFOnAGOUHjv0HQmeP4bXbV",
	"wrToZ6B0wns7gHPRjc+GTqSIubKKscK7qosi8vJ2SmexfBlzwGYE8t7sWFt/FRtt2dn8i44K15Tvr31V",
	"Po2E25oWNSh+VEAkkWRUH+DXDYudH+ClwlrPvnMKij3dbhi/If26lE6K9sG6+9ehf39xyvKXqwzzERfp",
	"ANVYXzW5wp2x4IY0+i8YqK1c4EUSJ6V9iUGza1yu/edP8ONW424QftopgM5nlswZPo5e/QA67+gjQk9e",
	"glM3XhXvOHDyemh/R6l5t1GfH1JJvpXW21F2O4AlAVlJy4J9Ybqvv5BH0oLxJg+5sUjGQz3AlBjFyxKt",
	"YpAxAHi1ZgKSoSoqWAFOPY0Ok0VdFGHjERzHoWABUMiAsjwojoKYGFmmmeb1v8be/ClpGHReA7LRWmZ0",
	"Xhfp1JGj3fgjXkGjY5X0S7t4KcvgapSJOHgpUtfgJyz66KtIHe123Ok59/wVeI3H17K0qh4TKoz/rA7l",
	"JSO+5mpR7OuQGXfYSnIs5hkIaOGmgTKScw0hJJaTzYpD9EnLYo3hF9S0Q3ERbntamLdG+bifLfvSpSvI",
	"L0ylhzPtgRBKRgUXy0VdYD6cqzTxeCqp3Kz+BNv5JCNVrHFF20kn5e39jTcckcF2EYmj+/+0j7ZVKS1o",
	"pVfS7FOn9ulE43aoESMHj+c40YFFYpqtmXJFALtexZcu/dM9BticiuKjdKtwd8drHL1f6io/8Can9AxE",
	"0gAqaVSJsC9dRSKi+zSdtA6xx6x6TLHFj1pL2sGf/9ORtI/ias7KKy4yEGB29vbfmVTePAQkTPtRQ7Ob",
	"ZBDWfdj7ATu5Y4dWbnoxst8nd5jYCxNJ7Q0ACqc009xlfELxBnHwhM6PMyUIigGAsSJnKqGN+fLxjtEB",
	"X9O1WnNg71GGhR2sAYAiC14YpvRot2ZARk7tHxdZUefsStdzoxgbNlezFS865YOabJhinfxCSPRziSVJ",
	"Tr+/8qAdyIVPYjJPlGA0Rl8NVfA9RxxkweRRanPwFeKh2oE2U1IVtSZcS0xakoIduOkeVWJnfUGicGE/",
	"kkNzpinbYh+eNXkvIPXK46lMAyS2C09tlHSp5isgOepIcer+C7BJMQ3G++59/Ymxx2/spUhl2MQoZv0c",
	"b127tHa0G5iyOtCMXNQF05gBTyhZ8A8sdw5HaweoumDPGrA2u5cl1MtzAyDZDhImCZg2wC4aALW2cjfk",
	"hLU7Z7U19/R4eyRggu0r8nG7G0az5qOekf/NlET43EJuXPap3QlMbvd41P6vy7Y/sIVA0cImSwZyrWoa",
	"Wa16Rs6Kwl1J738CD3HbaeWdxzk1dE6hsGUhVQbnE5BeLb06gFzLJjCbr3Ekf6Ph9bvFiUf6GPMlG+lP",
	"PJSNuaM7kIndLkP8rbtATVUt+2AU1VPCZsuZtSWyFUI3QhISKakZjkCHqoxxfvnBGnVwzOPEcp86xcuQ",
	"sQe5/HpKamROyHFmzQzSxjFa7ZDJ44DFPMW5W/CN9nF7wnNMQrQL/0a7QJVztQaox29iw31G3sklCkBI",
	"RcGZBLDWldwE+uWAbwmixMWYLQPCdLhRrjDF7CSvhrySv6623kVt558TWQMiMEoSNL3wE4A6ihB1IfRf",
	"QrUrdU/YSWKuZ62ZNdycH0GxSiozcrY7gxG/+nwD/5ydyb0We07tsSK/kospWUjkgVfznen9EdpXX69r",
	"TxiSeHTwAe29qY0NMu6eBBnufQmJC+PrvJDEtKECkwwVW3O2mUW4l7sXxg2pJAcRIkNuYC3QzAdpXjRs",
	"Sqo8yqAV0lv4o3ahbUSlHXkQ9vYA81BuI0ilaGZ4xqZIyZ7SYZ2HiFSHUp9Igq7LKoZ89rVDl8xpMKhS",
	"bGWN84PCFXer7CS4WD4jlJRcA7N0ybdalgyYTwH5kkDzijWJBwkopVUiOPy2oFycFFQsa7pk5J+1tvwn",
	"c9gvr6jIqZFq2xLlT/EMIQeUC2aZOKQqE10vfRIhDyDfnG18JdNhRhI6z/tKaudC9Qixj4MabFYnUZrD",
	"6mlCO3XewVrUNhn7CmOqNYNUJ2Y2zKpsG9nGgdSHaapvKpTBJGdLxSCbJWPKUC7MdkbOrMJW0wKFPey/",
	"NeqLrX9olz66D8A3qZg5tAMrdbzh6ATrS2rptNampaZ1Q+FwAzNuYqei07pCeFKxRa1ZfjcNbI/IuPCH",
	"F8rDonpTcm40yT1uOxM5sDNXSAJLxFsJeUXe6JkSWM2Ga8/aMUwCC0I5+JlkxeFMe8xXk6zlf8a8ZBpC",
	"yy4/jQRqxj4B/uZDncSSOYSCUZkyoznBzsvtI2dneT5I6kaCJWLFhq4rq7J4dFB/rb0anw6E6V1fpnmO",
	"pk3v4iTtG9pYZTPyRrColwkYS4AjshRSHXp7hvEih6I3e1wFIwqa0aN1eDZe2qX1LvhTblXHvNNv9WWV",
	"Mu/304wsZbaTAXUiH1HW/IxcOwF6jU6Ajf013GAtgRM6FUppb2HLNVPYrgc7SFgWeZgEvGBrrlmeFICH",
	"SLf7q35G6/YWlc9jza7QL2Uli3zQ7Jodxy44yzJWQX0Bdl+oTSz1L/xsPCmg3WeXRyj4HrirrRzUlf/W",
	"b/UUdGJQcbwSbMmOfP/kLy65crBb2YBs8oTU1nf3Chw/7503rkEL7I/JNujG9JvloZiIYtDBwlGVb1zE",
	"lbtF1hStCxNXvNlbIzXzVW2A6zTxVMXyZHSkcQ6nIAlBsXGbD35vSGe3eo7LqQ3w6U25a1PJZJU5dPvN",
	"pVl5F6BgfOCa74ZdwUrgb7wWC4fl8VeiIl9HIwsZd//S3qcGUtOa7AH71N9MF3W4D9CqgLBkLyRoHlCT",
	"3Kr578rc/WPuz5xJjogFaW9EETy3lZKlNHEiHIY0rFiiGIxoCvC0IQVfM08EPk/+VksY5/a8RXPAB/OS",
	"wmYc6CUFsI3EKUE1pyS5ohsSf97vNfP07fA8sDgT6sfbeWdxCupsKNgUcqPGMXrLAaDIP+X5Aa/mItgz",
	"C1QUIDBlSWzBi8JqlKNyp5rkWZ9CNSOYjo6xISmKO6A+3q9/GGQZmM05a3PBJP56B0ryzSsCP/cKzYDA",
	"72S97sBO+k8u8gbIa+rc6971WvHsxvUtzKSYEYfg0N76+/HJNEQYOVnae5aSmU0P2pRAslci9KCDbl5r",
	"l34nNwjPFk/kG030Coz0Bc1MTQsvw85DD8QVXTMXT/Z9aK2tPq8dJmnUm86uPzNuQ5kr7vFp++C7bwK2",
	"aKZxo/2Ir0JRg4bKUjvvglYJIXirFK5WRtWAi2gjFThlfGU5VhIYJnKWkzVTQekh2rBKz8Zz9HtnvYjW",
	"7s4OhRPcnKjlsKMBPYol3xtbAHefVFg9QF6hdw2ODOxvb/WYWgntnX4zl/0Eqj0fxjd1aZUbl1XZMe1F",
	"Hq1+dkgK+QXTsgDEPYIlW7RgM+Kz5uyld/l8LsUDsyYgyjEy+uJCIimeHw1uqfeAcW8nAECVLpOJzu+i",
	"vrEIQAKuSihkMKHYOOqn8t0PP9yDCdUwtEEb6jmAN5qYvO1lXVj5irbB7VLCRlhVchGP6iQ7NE6oDC+5",
	"NjwjhQRvbszEfITU97HnIlOw7c4ns6dbdE9+RNcj7eAPx9reu8iR78g/6dEfykNrE+9ucdR4+jvoa7dh",
	"voPG+S1o11t9M/JjQcUNoQtjZaLiZQkSUXsAlxR5H1SFGOa3e6cGstVefrDGGDeOoZeRRJQLsBrbDG5c",
	"qpr/KIQ43Dej1LUjpK21+9f382aiSw1iLV44VaEMqsP17s+K8UIFQ42haAVPoUnUvnUKmz8B0JLd4qYE",
	"k/mQAF3SmouDQCbbsqaKCsOiAIpuYKHCJPFzwYV+z+lu7ZOb3i79rTnfdIZpo1YO04ZVvlXuIWsbboU6",
	"Wj4lgm0OryGPVOnbeq2d391I73ZnjRcFLxHLIcn+cLsh2pd92zoSefON80w7KQZYxbVwsf0ZOROAUWRp",
	"tdi6mvbokyQrGFWacPMsqmyI3JZCihN8C0VNAohzlyjw/sWuJMCgf6iyx92CZdn5pPGmD1P2sOEggaTp",
	"zOnXVu/ywaFY6zpEKPkV9QTT/UuiB1G7XrNNV88i70Jb4AZr2QtY4NYBRuzIXusD3M69pUfp9JGLmGaG",
	"r1mkAyX9wy1pkjLJIRGIFlD6JyVEAtCehg4Gg+3jI9Znt9WjYUW2PUpt9Bk7ICaeKH0l3mvbsaMLu8y9",
	"Fdb42Iw8t5eN5YQvEiOAZYLtkG5vmYxOOHadH6z81Dj63dKGZS2sspPwUPF/B/wTGBTKPZcFhZ7XuunV",
	"03hBhBXY1IHNQMaz3CT23p6/SjV/eQFJXskE/h5J2PFw8jkkBAykCw/iJryA+HtmGghrFhDOXFqHVccc",
	"y5rs7oaXjNC3y/NT7UZ3N87rCjSlzUlWWNHrC14Agz/UuuCNwFIX3TQ7Hd4cf9uvdhZ6bCgm3Fizzyfz",
	"7WvRNzx1h/RP/NP759kF7vPUMz2gsV5npSm2OCp/vn3xLYfYc+8Pc8b9pBgDaM3ghUMMfQqJQNB4fxr+",
	"ieZdtmLZjUPn2qy2s/sLtBzeUeNB/GjTPkgOtBv83OnWYzbaZRAnvXrwE4LPkNd1UQSIVMzXpigu7e/P",
	"CHUZn51HBOEiZxUTdlbFlpRU0CXLIwF7qzjc4c5IXMVLl6yKzHvFFMcqm6BkuyIKSH0AuRyDgkBpWoOS",
	"0tfwonrNceTV1Gwme9DNPdp7IeWNtoq28dCWRnG6RLAv5bRYqhvME6oUXzMd0nJqYXgR8muhRQx2DnFh",
	"IMvwdEWzHaGg8EgvHNS7hrePCx2qJLeUu12p31h1YNk6AJjyonAYdlLMyHlDo561rJnKeWaeWrMD1Bms",
	"5YI2aJDJIKR/hmyZwRIBq4u1bC4p0PM5AMzh8vqhKZeO2RlLO8gPTQc/KNHbLmX8xv/NvZDuN9Yof4EC",
	"0WJLqqZ4HHZro5RJsB+tesPNjFxIia6Ehm9oUuvIlo8hMZr1DCYiBbdmBPrb0iTdB0bx0AfIkoeTHpEk",
	"z3LIi+RmOEl+r7c6lFV7R3Tjdu6zhl2u6KCop5SX1k0dTjoXbNOIFeJhl/eLkAP8GM+HFBfL+xdUOUWF",
	"orGgUX8ZykcbJz+x1IAIlmgbCl4fe4JWwlj2EsnVcaUy9yl2zgU3nBaQ5691Cak3z5H3eTlTUON0m8Ml",
	"h5EgPHwKsD3tO0iPw7rA72bDQV2NuPCYeFq3U5O/TL2t2Xsp9qcUdwrGD88tbn9gRJu6W2Ybt30uX3rG",
	"cWdXRhzU/XRS2p9ybOWoC61aTr8z65hoXgCHvEOp+GGem56nZifbfc02sbf64TXoi6AXe1YGweJYr+Z6",
	"LB977ppjE4UJ0yWmaCaQBb/RpMX0gOHpO6jFA73TH0RTfg4qV29NYGmiBxFKdMGZbJVb8typvCgqqdeb",
	"nrmnwf73YYldqrClDvhpVArDPaqrzzskD2nBkN/rBbFM4nXcu5p5eOrD53DNp8hoEOZkyN66tHxOSOSN",
	"0IcYM+Bqk8mygW+GKvBVa5N8FMDSFsQ7ryoll4pp0EyBLpNBgNfo07tEH9wjhNohEGrOcbkXQm0keNqx",
	"wdAgPXDXbuxvev/VwKndBzbaHwnmTB16UY6Dd5YAOosm+7lxzl7LfLBqHD1a0ldodAo0ZuRnvmatqpso",
	"K5/nOiBtREXITTGId45XlKuQEO7an3lHOtfANYa6xN6h5IVcUMWKLWg6Dmmh6VmrGCTbxyn2hNZGltTw",
	"DArWsbSVK5/6hh7aA6Bib1s488pupc+U2FW6PjqH6gErM3hcloH2+JKvXa7C+HqFhJuh6WB4z6p45xo3",
	"GzR0d/bb+SLA4h1m3n9eq3owwe6dKxS6S+nyqHQ4HH9o398NYy23GlzqUB+IKVdNhQkq1IiXExpeBvAd",
	"3x9HKrKievUsIMJF77b62QzVsbUabrca5id1245cjHJluFjIyXRSyA30kct5XU6mkxVfroDlc+BNQNTg",
	"/0x/faCNeA9/Ctf01G5QXVIBbZ0AQQOVNddRdUooyZlhytojmJzNBaSTqdoneokmoBn5UIQ0zYDzbRjH",
	"MgqpBKlFKBnFYgOqXWPzGPfGb41vWT6d2HFDL/PUDlz4Er4BhOG6KIhm4FwIGBtQUMNFjCc+KJHsgDpd",
	"B6WbQii0iDK7OZhKRLWrdTywlzmy4h2AIgPzuYhyOBp8Q8SDacHBBBSYUZPynx2aFt6YFLtnWa1gY6AX",
	"mBOrLk7nElsAQoS84NqyLQSdBFnt/HGjJ+kad+/jP60D7e1os5YUh2rtwy40Hr/70N4Pdh+R7DswLnaZ",
	"AawMuW4pwc1nTw0bqkPr2a1VoZwGZTUr3UigLuRYwZa08GcdEqyiTqdysWAKK2PidzUS74KbNqRMBK/Y",
	"GI/Q49CJPsyjcJAAuinopWKbBOff1d+4BZsSehzbnWw6Gn8uPDUPHbarwYmHEvPFsyHp3GOLeWAx8r4P",
	"RYb0kCu6EaFrkt18peRmxWjuEgloHvUmQidYuydEZFc748sjeN9ZF/R1n6KHB2QpHZtAIiRQA/nzMINz",
	"bGGKt8nI2WF9qadum6WwwmzOtO/+62sADupUHe9ye9kR1aT5iRV6Fyh7hhLnjLR6DKtMhMFsZADCmFpZ",
	"A/3+HTCzUVRo7Nc4I2eAL6pN144roGeyA/xpks4HwhKqHJxcDDsGswT9lUGvaK5XHf7diXTlwxA6owyd",
	"g72vmm5m5OeaKst8l5QLO+1uBGdsgH6XC7YvuOGX4SPGB4LDzlAuHLZZCovjoTZ0OOHfl0I3VQn3cxoH",
	"7nWY4v5N/7Tjwtl9TCUvIkHPwaeBxdyFzwjJp0RXBTdWrXVO8MHbkhIS/r5Qe+Og10p4+K4gc/8ckEv9",
	"IWMQuNuO2OOFOzFgmr13fv10/dJhqPbtLOFR2mEnuLBvVeH76ZU0ZlwCvrrOViSnJV224rU1JMLUmmGK",
	"IJQUhPRAmv+zBrd5Kz8wy+qyLnymmbeK9liKKevoUpY/SqrylM56Q8Xc6uP2d8IFSELajo4mchRGpf76",
	"b9qvjXNc0ZIlU+wDUkmS8cRh4YR2FoK8zZwOAltJ8aPWkG7iSVKR5Uux5kqKkgkzFIt7LqnSLkX4RNXC",
	"F5S6kE+ED0mZ6yXnPxnwWv50DZQSFGPnSL7+c+L0NDqVk8EkVbNexfyC8qJVuRV3N9BXqhbCNT0a8TH3",
	"dPprhcxocRWtL3mkL/rbwHNfqCyLYmSVqx44jms3xesoIRI3l2Qy52J5Aid1qpmpq9PMzr2uvI/JLrH5",
	"APqZsMUtuARYTrbMPCPXuKfXAfzXvub/JhW5vgG8m+tn5DpzaQ2dh5s/x9zBn8V0En63WwEfTvCGDm0n",
	"tz9s1ACBn2tdJ83h4OxFe5EYqqGLdA8GBGVU8CllAGwJxlufeOECJ6kCWBzmRcCgByIq7S6pqIsC54/l",
	"lD8BFJ0QYFFoe1YuoR7tVEzO0EbVmbetfQXAhheFszXvs8oCVnwAq0UfvUsLSvht/lXbIWhB8JG4CWlL",
	"LiTKgVy2pQsCDOZcwm62ci57dHHLugMu09K5VksIw1iROSUoQS092qNoUqAhRGOIZuMSizW31yxdlN82",
	"PHnumhH8Y3J+cfL9d/+YzCbjG0QGfHnYN65HNoEM16Vz5PHE/Zi77vcvPGWhnmMoxyEroGz1GIJYVucQ",
	"9tEd7IizK43sN0YrcoHhpBCrpKHFUGuRd/ZHH3xy1gjMeEoUW1KVFxAYWJCKLtvyadAywZm3x921iRe1",
	"GDT2fcbz+QWheR4a3Ko6UQK+BwwiZDRh8W2MvWIkJvx0cppvGDBh1uAJ10JnsmK5nUAwlY13pbfLA0JA",
	"5EHQ8ZBt6hVo0Ewonq1m5C3V2le3+Eec8ura6ZSVIVra9d0IudH2YisGzhRIIyILWYs8BHpF3rjE96c0",
	"y5wVAzvPxHNAqLCPWKWEC3JdKWl1enUKf722TK8EXOoNVblT+kHcSXUF5tRy5odo8AZcw3FNrmXFhJK1",
	"Yeo0Z6zSjN2E/zhZf3+yKKheXadNdKo4TV0Or1G5aRD3oGNYL17+dPb+l3fNZGrtfD/+hW+ssrqgdWH8",
	"qyP4U5cY9l6dtNn+Vyrs3Q3gm5iFgZGp8wuENu2msnEsLbDKIqgpLknU6deehWnLtPXhOkgslJ/Bf9ox",
	"WupqKNCqRc48AMNIqT3k5kElwHENSAXze7HAjiz7USVHqd+RReNhRDxDdRu4ktqMdDhVcpeKb3/XHDpB",
	"oEO9GTle38jECC3LvYvrnpQLA/sIqN9d33/cbvktbEh/ji0BPaR992c9cFOCqTukjTcJz2uuuVVKQpNy",
	"y3Zq1YAn+OD5bY3/ZqiDtNKriilthdeePvLcl4wWBbPcx7+W1E5b5qrd+UqxBf+QTGxc8A+WvQHnxguF",
	"ihKmPgX9bUB5u6UHQxd1wnx+f/ELsb/0tjRdeKiZulIypTs+b07XUoE72W90dEj2RWCJZy9enb+2/PDV",
	"y1c/vrwYqWbCut062sfY2fJ4nmkqhihuCgIkjiXvCiU/xyggGBHMWG3GQXMplqNR4yJtrOBzpqhhxZZQ",
	"VP99+ppzU0OUFNPmjUSoXJ8f4oGmwXdvFYpUss+uWGfUd/ramY0u3rn2ubVcYP7skkHmeEhR6J39YTE2",
	"3GPs1ZuoLqCoBkPnbvLC5YEwn8CHqBwO/Qji1poJjW7MldzA7r0/J0sl60q7vdIHhuca7ABtaFG48gZ3",
	"917RD2+pUbIgl+cvXyXvYTpc1+pQO0x7vjfswLa0yTDqRd52N8SdZQHZy5pcAv6Xi4Wi9rJQkc+lvRJQ",
	"GzTguW2n4vbFlUEXBM7BI5WH4PzcarkQYwYGtOEil5tngJLpWyUFdPN+7ssHw5SgXtXdg52EgjLkHd6u",
	"tS7+w3nfkzvS6Wi/D9AJnwZCctlBCYO7ZFeKCoxL7Lo473jJLuDBgY4wjtLirZi2trE1WooGmyH6XYSV",
	"LA/Igpa3zHGGYeD91Pz+1lT19GSML8+Ri15ZDkI7RNg7AImM0U2o6m0QFFUELoY9HBR1cr9bTOCrTlrx",
	"kYjWFrTQ7Ao0SAShEtJc0cUCg1TQC9jNes3SzlF/2y8tBTjln1HF1FltVs2/fvLb/D9/fTdJNa/Qli/c",
	"MKdSgDNEz5+oGwr9EmHdgFkGunTwoMDDakponXMGeEk3bAt+JLjf8EHIJI7UN+ekixTGGflfJw5w4+T8",
	"hUviQfWpDH3WvNYHVr/dTqB5UJ5ghQ3ZrIypJp8+gTW/kIlY8cvLd+Ts7Tn49i7fPB+oiIUsaxfpAgcC",
	"HGLBMytNIAYIqtTkrKLZip18N3tidQdVuBnop6enm81mRuHnmVTLU/euPv3l/PnL15cv4Z1G7kwuccPP",
	"29M5e3sexZefTp7Mnsy+BVCYigla8cnTyX/Mnsz+w3JHalZAAqc+qfz0Y8hY/4Q7UbBUyv0L+LsmNOxz",
	"SFh3MM7fP/mLizbw2Do0sldBg2V+cRtnrzPYDbQMAx47z8O4L31+qu9TDYv47sn3QxOFHv7fP/l2iB+G",
	"75y+F9jvk//bv/Qf+1/6yaPb4Rvf73/jtTQ/WUmGL/xl/wtW4y04sqwfnjzZ/8K5QCYdKr5+GLP819Kc",
	"W+PAXjO7ARHHAC0s5hV//80qWy5cF7YaDg9ldojyORqBXKKlDkmLVgz89mk6WbIkTCLSkXv3ZMNz3wIB",
	"lH1IdW1RETZREJnLYnfJ1YwvV3OpHDxzaLnSJ62fmUG6ek5V3qetJy4dwjhQR0hSQtf+6T9djgmK1XEZ",
	"sTAKcJ0Ekgn89uVS7BdKgK4tQ4bnlyS1iipaMgT2GzAqmkdOnZA5t4ve+zCOfo4mSJWu1n8PRU7atUaM",
	"+pVg4SH20pqRd1YEgoXne/uAnIRGdGVZG98GtE3A+PGIN4J59aPMt/dMughF8KmtZ7kK8Qe+NUM3xlWP",
	"ucv9RXP7777b/8LfUHXiUkS358u8czk3DctPX7tP08kpujdOP/qyskO1CywrG6NcbPsFZkkdYo0q9QgV",
	"QsmqelQhjqxCgKTfpUEgnOVe/SFqMdgUrZKfqWEbuo1cU87hYCkprRuk6eUeGRwMMMDfsBDrUSU4lKDe",
	"hK56XECkN01BD6kW2FFAK7Bs0EOznn50/+VZoaPhHtn9hI89JOH5IYaUUZdJHt0eN3fiS79nvzfKPITE",
	"fmYmBun0mxMRWsDjvSupcXsm1mj3AYqnk4aMJl1tbBqd/75oHhBnH6grzVk9UJy2trqLkgdY2DzCqlZM",
	"uFQa10rR7lPB1qxA0Gzw2v7X//m/BLAFMBlIsaiqbOMBhhEb1TWbBEcvFMT3OfUvXJu2Q2TS2/OUoBia",
	"e6LZOhfaMBqC4kpKo5vkEw/PBFnSvscDHBwEGpqTa0D8Djmoaa9ik7EKwzoAlCRdJZyDS+qAhQ9MJUA0",
	"jGMYSVSnXTProru5bfVIE4PTipAoRk2sgenoz+aynrsmEYjwEDpzOvin1AT+1Ro5cRR7bu8vvORmjJB4",
	"joUClrE8GJvvw/4lGP4w8N8xWfzvy0SyLKm7mY1w6OIA3kVE/DadVDJZeAdIsD0MXBq3oQCGBZ56bjTE",
	"MAq+YNk2K9jU465Pyb9qVrOpS4KcNo62GTkjgaO5JBrdZMI2QZNnUcfIdg8LdNjFnSxcAlyYnXOJYIsD",
	"YSgXvSaUfYmAqDFtcMiH8Y6k0GZHeUm+fZgpDGl0PQDU46tv92Mx2St84cYZWiwSpWuBykVEpKE9B+SI",
	"YpypaZE5+x1yojcR0m8aYHAXY+qriKcfuymPO906l3JhTnLn2+mDcnvtDurHigJEkNHx3SYumuNy2OLQ",
	"GzKPnBra6QA/r43ri0IKKZZMEbqmHFLguzAhM/I2djdheTL6lP2A+O0hn1KfyfwOwlNfvKtoNAEPeIre",
	"9RuYeCnowcXBSFn5WsgQ5uXG5Tn5XCH4GYEnN9R+oN0cpmfd7yGYJ8eVC59ZJvwunE0HEOMDOp1axz0u",
	"JBXwU3Tt4BcwJa5B242a+rVgZMlZ0tpEbBb7VUBDwoZACYjeGGy123OhYzi2my+4RhialVQYnumhiNjR",
	"Vb/PEh8bdcN9mOyruekHBzZ+ZxobUvBBUm6UmnbqSrOhAgWBN47MjZJ26gXiGuk2ZJ0OipoP24BSl+eO",
	"a0X9SR1Yb4NlGOBlIjzQ1/irYoQao/i8Nt3Kq+ZN12oYO1lG0pz8IjNaEMUWOmDwBTSpWD3FqfiqEt/Y",
	"0TIwQOXoM62zPD+zk7hwZ/MwDCsa4sfx7Or+DFVXHXheVlK5eaSYFv4e9LDHwP7h8YlLumau3ZtrOQ0l",
	"Ewh2CBuPlHh3nuKcRF8eN2n1Ut3NWqa+vA7NyjjoJVXpOknK0uPr5nkAiKsLqDONCjADUq+vrUoUmRKI",
	"DxIrG0IyaZihg1GDnudzBjD1MdwkolQBn0qykbY/yh3Ow7ATDwgPmxwUkEd28vtjJ2d5IL2TcKe8XM4C",
	"kd2RlYTOq4MWuxPPhRRsihXu0DuJvHPFdABDOYeWr3hBAXEM3NcYcoQ+7HGj6inRljgip1AJ3S+Fv3SY",
	"qIyNMQWZ18VNOv4I2MGAVbUv9ohQ1IAHCZ20gVVwkRV1zmbkBYZWdbubtjWOYqAty9ahdgSKA3YF+Fg7",
	"xDceB9mupen10G+fuIV0dMsgJ7vCgHhkkNPjAuZ5nTE1Iz/BWbgG7q72XYNDhXocXYXtKAk15J+1q9wv",
	"abbigkG/0uXSUtCOGKdrwjo2lOh7sO5fD8KhYikttLwumqZiiXm0EEH3xRd3j2xkna3CwAKas3LhMTQx",
	"mL1jJgAaftfw8wslKz+dVXOmUMwM+BPQ5sm3W6HoYx+aUcnFVdQ2Kp7YyHZQX1tQNlyvMQFZZIqPMut4",
	"ua3LBoVhyP4GNe6z+POSOu/zEHltNEVAywS45gbd1vJQjHuBxllXFcq+UHkJoRVAfkV8WgB4npEzktdI",
	"7P7JE//RE/e4UbxCzE+fqzsUlA3U/0Baafj+5wnGNsvbEYhl8PujB+6LjTMpugmg3fMtWVGRJ67/AWrt",
	"6Uf7f6Nz4N3QIRV6AKooFY9s36/HWOQR0tZxs/vCYacd0wQcm9BirqcOTC5nhvKCVFSwIhlF3HHMT47H",
	"zL50RvYlZ6gPUc0xVYr9rwQSGBdRdCa3Q9YI5ZegjDj87XZU0UFxk0uHR+L0Cayh940oxtTAHU2v+CyR",
	"vr03MRTDPaoWX37tnBy+/7fSKU69CBnO348qozzqEO9idfs0do+0v8PL9XId7PU70Xyi9ASmhXOcElnk",
	"TBuy4Eqb8e2H3ORe+gKqDkp6uuQlGvdRpB1M1wHZFXQbxbTR5AuwmW8h4JIm9lmed0tCfNBH45L9LZqR",
	"lx5+NFwsaMyNYmwppErVsJzlefpyPaAk8+Oc5flDyLPdd4zQhXHthnzr12Ne96ZBQW8aj962o3GN59ww",
	"7BbmGO99C8SRxecXrJRrhq2HWrfWaq2lXHvQTOj4EqWCshJt9K7nrXGEfffdXkN9WJZ+PzTT/JFGj0aj",
	"l0ZWlnMB7q5j+1+bXDu0ZHnEhfNQD0Ma50ufCNHgNPQ8WVMi2KbF8Psqp//OvrBqFCjzI/uawxsucpfN",
	"rc2U1JqpKeHVlCx4wa5WVK+GglNWktwiaDdQd9hBdnHohnkHV/V3X5ToAWVGBL/82T9yu6PiKfH9IbBj",
	"ISzdJgrWhqfDDA4Ae7fiPeASQj6mSaIuuRQQVNuxuUBvL4biW0fAYvo8ka3dYExRV3vIROCIbQ55GwFe",
	"XYX28PYZ9nitj3atMYPL34h+SKuD3DRe/o8Fj/Qadj+aZW/ZNG6L7rKdsAmuS3WESHbnXmNdnm4jRPEF",
	"tGCC9hje1myQJrUDuO7q4/bpQwAmER1qID73CBp1jAitrFKok59bXDWAgLcRbSOvHprKg4o3uld2qt3Q",
	"4BlxVx2EZn5FHVz7AMDKS2+gj9XCcRqxDu7Qz6PefgpqkgW2tfSI2UNKMFryDo/6dil0OKeQjejSXqxp",
	"oDkrp4TlakqE/R/ANx8EKWkBZd9lKrA3vu8+vWGaVHZTuGiSWiM8eir0hilN/jGBTNcVraDADu0L+wep",
	"DWLJJ/fPM+q7Zf/9IjdMISY7aSBYLf1MMY1V8/WgIeNwuRPD78T27ocbq8E5sA975mDkPcygZ+KtnRfR",
	"VQ9olpOKbgtJ0fTMZFna61VwwfSUAArz1FcRMf3HMPwszY+x+xCkp2R2sx6VxKMJ1Xduy/fafkcB0bub",
	"eDzQ8XsvaqnTNQe00q6LOOMeEmMQ9xzU0kMxSx+10s+vlbaBTD/vPQqe3Ye7cgHscAjU0iqQP/mHeqtN",
	"l0zE3UcOArXEnkABO/GuAHPYt6YNM5f6sKuDujoQWM9X0UWQel+TTHd7PkaqO23bE8vsUbIfXokHuHJ+",
	"Bxs3R6LDxkNgkT4w++gB5A5JbWtGaVfshBW54OrBMOq0CdDKjfDNRaA7VbNhbqBTZ3IiqF14D1rnzbeR",
	"xEY9YKDsFgX1IGpvMu0a5/FHxtDFPSA0IAuD98HoxoArtiRniq9Znigy/WxEfWxM3tSNwaDzkAfodQcJ",
	"w3W2BgAf3xsQ4NI2UkE/UF2rBXUJgHPp4iO+1tzHKaFG02fxshgrYwVEFgEDP7UvbIk2dOvRLwCljWry",
	"j0m2YtmNK2qFo85Z/o8JwHvkErD5sqI2Pimn4pmpFRvOgd/nkTortHTpGA0eCOxJCm7IA4XA1CumTuym",
	"TYmWTchoJe2mVBUAGUnLLiqmOsaD3WVoHggVxa4R4wkAW863JESV25Gnqxs2CIvr6oOvHF5eS7twmx6K",
	"gbv9Qu+rgJO812xRFy5NlAsAdLKPUIHEMa4o934KPu+3pvoZqajWrtDb0naDLmMk0YxhabndH1UXLLfL",
	"/gLrsB+8anUo+of86FGfO5ahCYfxhVapjpNgDcLnqJz1CD84KHV9mPZOPlHcqtHKqR7Y8BTFTUIOoELo",
	"5FFFleEZr6hhXpy12b1lyemoSTOD8ZGTaK0enxZ5yD1Bufs5cf21Gp3NCsbYnRGpPXKo21mc8fVb7DI1",
	"o73+8hKDRACxQWCQsCzgI41q4G4bOTe6xzOwW78mrKxch2KuyYJD5+4YWthhoMPrEZQ6YElFMHwksIxB",
	"FPOG2B8oqagZ4PMkFkULHMLz9iezih59vMqHXuW3uI2Exvs4cHcPleKnH5tvHoQJHjBom/fx5oWgC6j1",
	"JbO6P8KieYu0NR9rfKyoCr4a7Pasb48M7u0cHc9sIJe/c0f/oFX3tymfH0GK08FGWbu2/ckR+dPXwZYe",
	"+kitzjXmNL+sOonmdHdXuJ8BQrbuQmVjPrGsDC+5NjwjhcxuuFjOyFlRyE3QJohRVGjuAB9jgFkjCc0M",
	"XzNMVAb4ynzq/2Zk/DffWX5tWRnNbpqXZwSRLzvl9UKKE1RVsNB+AIvb9ahvfd/wkmlDy2pGzuwiCoDf",
	"1tjSPmrJ6fOpMxeftZ+OFat8qGL/iIrNZ6nZ3883fNH+V6LWfMml+7cB2D6CGvR5Mbdvw/2SJtR7a/l1",
	"4aODHub0rk4nADR5XBPALjh3H757vo2wuJe0bZ1F2t+zkBl2EidStrB30W+D2TnxV2ptyJx51hoaDQJr",
	"plnokIUMPlmj3ezXI1731wiw+3thYQDwPQjujcg7VHhKPwKf+0w44PfG4dq44bRkpAtvTWgiTfAEO5ty",
	"uAKW17W5Se1gkXyKoAMgn/pEBJ1mmtPQTE8qCI+nbVvnTvJ45Hb9YFRBXnR4OPJdAXhs7DzHm+tqBGID",
	"/KeQYiJy4pIkgi3tZtk0yKKQXAGRQhzT8WuvlLK4W1+AU4bB9R42+whh/shhvxzMc0/53lV0FBUy4KJ/",
	"lYzVe9+b2oiBfgZN/k/A1xB73XyuUjfVniF8EzJaQntp1EQTLK+FcotDtKE8nvzlmePbkOMbUH7sQ7Hv",
	"sFFWydv37xoP/05uiHxzo7hhIyIBjyC6m9YZuVSP0Gvn0aA+Kq9EvNy2juLO5YgschzGbgP14+IOnfDC",
	"jLx0rOIEIhCpwEN/oa5H6K4bHrGFoWveDSaMhvF91XxbfQUAQcco9ziEfpEm2rDL9Kv3Zd8C+65OCPDz",
	"nJWVtEzdS9cOPHU3C6cbievJ4N7Fuuu9aVkMoy/Nu1hJCPpBfN9Bxj/epFvgTHjlKGKRRh5HFuzOjfZJ",
	"ZcF3gufdc1D6uvVYQ8TW4ljT6zQOTbiWBTjxex9q0Tx8kUFLfvdgDIrcvL4jq7opCaexUQ+Vx1IkQeIh",
	"c7mTO9z0QLcK2jaZWd3RNPflrkE+cWsBm5XUUWJxk+9rpz9nBdS0c03WtKjZ8TOFo7k+RMKw+xDmCp/I",
	"2pCsoLzUf7CU4S4V7Y2e9zxWj1k+h7Pgn7teP7n4HSgzv91ZLgBj/rojcJEP5bXMnXEOTilFM/Djot/Y",
	"u40hASC/iyOFG52Ow/neQg5YySMtSeXRTCDY5uG+LMfHTm8IePKBQj+9GE7t/pwjrxGW5SH8Is2ufxaX",
	"CKxsgIu6w4TzFnLz6BL5vFz4efciRkgSx/KKAMc7/eh6/h3iFWldddB8YrPIt6WzNGZ1sxBBaphNQnOO",
	"CbTRsx/GcRJYwKPj5CiOEzzVP4zfxJLXgS6TaIf2e0wS0Yl7dJCMvhzv2sEMMOr14/24szsESOFe3SFB",
	"tx1sOebcEp3WydgVWSpIwkKvRcWzG6Y0ILkqBnS4qIvCm2bO/QFZn7QoMGCHJr+si5zMGdlQbdiiLtIV",
	"cVBffSCYt88fg3ZSPucL/7az0e1B6DF2Yu/sC+MBveEgCzrHHm2/e/w2u0NjCu6QGh9N92NVAyNkwVfa",
	"s1ZEMN3NvZ6R80VzxbwZiRJoGkLyEL7zvBVeGzAO/5gmIXYHf0Tk/iIv7dvaeK1QRsgkt+6Acwtjr7lf",
	"AH7E1NZHalyPee5yqLs3dM5WHJJ1ACdFO1AZ7sxHbf/0j4mQhmykMiuiV3IDWCHROv8xsZTJs1XT9b/k",
	"2tAbZj9RKVnK0CuKLJnRpBa5FGzI9hut1H4FDXS+VHhQehNMPblY7KTZ6W5N1JKC1RzlRqQ63gJfIiuI",
	"bGVU5ckYVfrEnxyXvT6S0a2a3wo8uy+9h1Kw88exYGx+e+wQw6CK9SsYcJSs6hJKATJWGbChVF1YfbE2",
	"iGqE/wzIBAHEieVQxAgI7dJYgfAU2ytssfNZRpXiUGXYrg60fGGzkgUjczCWuCaKLQBTD8zG75/8BUa7",
	"xiuvZ75yUF8TQUvfaw26Ydvn3OD2OxvFjWGIr6UB8zCqvHx/TjIqiJJFgcWRlWIZ1ywV476AowrR0oeq",
	"4MFhLvDLx64/9IMPZZWHlp14TNmKiuXvzP/5O9MZ8USblATvhSfzuri5teboyzt2ovde+odGofc+guze",
	"6012mz/G9xIQTv2pPsLs3hb0yLUlacqfRsLthvv0hUKv+fmdfnT/9VXC7bo78Qi3eyjcrjuDA+F2PxtR",
	"p+F2G8o9BtwuQK4OR1e64bzGn4KKay1y8L9NyaKgVn/FrIxKsRNoxOSiKSRnlYHYArMnZXVsdL8gfCxR",
	"bF7zwlU3QSYnF5D4CamIViUWkihLD/Y0yYIZ8OIkjefWNr9DRNl7bPb9EpxJ7U1xeSg+CzXegCmiqtm9",
	"CnAiTh1nOVFSmhl56fck2B2WeGHLWp3CaVG8WQySpZeo553WGB8nVqliyre0he8mGAnXhlqWFXo74OT+",
	"N1PS4UXhn+zkWLGwM0ukp3Jh2BLzUyPi/bsb9bfwHNb5ImMf09TcowM/OiUO9m0Fm7VBWPasr80fPo9U",
	"D4l2+xPbXTOxbcUgUlI4iFL77yaHeVkrqyNCRwad5BAXYcQHNVH9IAmKPisKknPIYaXquF2Av1j7z21X",
	"e18aUm3I5E5UCiQ3qCYOobENamT3GIFGldyPNMAGoRkcBBKhFdu/We51+ROv/GhBK72SZvZHVgl/Zgb1",
	"B4dO0TF4HkL7e2BVTsvydC6pyvXpR/h/UN+41vWO9Ji3Sn6w+sTlm1fk+ueX78jp+lv3zv/wH/nvs9ns",
	"ekbO4a8IilHPT7j7p2JE1UIAimQHGZrqG/C5rpniC0f0RBtWOfDpJtknnS5zKUsc9CGvlR/kF67T+BO4",
	"TpdhAHvyqGM4AM8fnoxwYVyCoH0vAtjoYRe12X8KVIonEF1PWd75ZnYSnvworpIronTE6woJT+3L7O/L",
	"/VxlJtZcSVFiQ79CZrS4iv7WEUgdp1jFhCYUNKBtMHpdZmWkA+WUlVK4rh6Af0hzTa7fvrl8R05pxduT",
	"wDPhTF+TP9nri/yi99hHnn+69gFuWVpLRdXCmn9L/ecZeUUrTa4Lapg2V1E7XFPra8IFpAZmkirNPHqk",
	"ty3OL8j7cyhLk0VBamF44RaUc7E8QRAo90Wy4ILr1YB+dynLl82UH5i7RCMFH2yPyzx3YjvaSbf8R2Zz",
	"RGaDB9QwG6Qp1qKVh2M8L/A6xjTAc5fwhV5CVQsvrwaYUIpR3A9DQjZ4+hH+H2O+tbhrwLfPeeHzAP1a",
	"i9Bdh0Sdsdvr9bO52xqHwshvVLZi2ihM17NTeuqYJERpYargDrl882pK5OFsd+ox9Wn73IMryG0H+2A8",
	"BlulZFkZV7NWcHHjcgGjtz08bvMBLuwUZ0DUzrukSa0xxzlAPDll+BtNMvRd08wy0xMjb5ggmmWKmRm5",
	"XlPFqTDXGMkuZc6KK55fg4RcSLWhKrfvar/Qa/aBZbWRCiual9cz8qtdX6tkZ9pJ++8iVs7ZQioGEXj2",
	"ATkKyWhR6GfRrrjDsTInbkLgldYSfb6u+t3jBRoZvxDAEDYrXgACEuUixOVb+Hcbnje9mmfEMg8GLaTQ",
	"Hxki9xVTGoE+fVsp0JntoZxfPPMBf+8k9MwMttP+ARujUJEXLncoEdJv+MIDRfP95y9qcVBI/9uHmcFQ",
	"XP+d29oN1XizXPG6vSeP8X31uxTaF21B4UQ3d5ehLa69MLO2vq5otrMFUyFBHX7x8tWbq8s3r67Onj9/",
	"eXl59e7Nf758fd24wRPs8xJYpXZI5iA9uGlKkU9KVkq1RS6LAcEqZYg3s7wetJB/bVZyRz12FMhCPOJk",
	"hGu+mR5Zc82h14QTiLQomPp9OjaPpK2+eUUaEvEuikjR8M4tmgF85n0qr7/1b9Lpx/DfoB6iM+ow1xO+",
	"8z/iD4H7qVGIhpWVgYs6eHN+xPkd6db86D1H+24MTsuf5ia+bI924JFuVnMGKEyaU3hox1MYyTmf8ELs",
	"dz7FN+aO9h5slFr7BdWqmDydgJ9n/S3kerkd6AlMKdGNhE0FM6qZnmI8H4P8VuPNWcUE1M0XfMGybVZg",
	"CQbo6bO46Wsr8DidfDjJua4Kun2dfKC/m/a5Pg40Ni0BWCKYZdsH7QZfxZ0LuwO3WuolmBpw3AiZ36wY",
	"7/bIBbMtGhAfTwzmfhgc6ERnsgrRzHR39E6X317f5tS44ae9I+/MFBscWjcpld2hw087dtc3O2AfAP2F",
	"5aiNuV2XyuVpQToWoOy2Ntu9ndpu/1N/7PM+whgWe049blmU1hWN5qtEukP5trG99JFkDHtX+NoNpKKg",
	"dXew5rc017mhYk4FWdCM5tgn2zu9dRPdQQUbojrxScoydYiytDrC/x8AAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
