/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/artifact-analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze an artifact */
        post: operations["createArtifactAnalysis"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifact-analyses/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an artifact analysis */
        get: operations["getArtifactAnalysis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/endpoints/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search endpoints */
        post: operations["searchEndpoints"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{source}/endpoints/{external_id}/response-actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List endpoint response actions */
        get: operations["listResponseActions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entities/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Look up an entity */
        post: operations["lookupEntity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search normalized events */
        post: operations["searchEvents"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/context/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve selected source records */
        post: operations["resolveContext"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check process health */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ping */
        get: operations["ping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List registered sources */
        get: operations["listSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Cryptographic checksums available for an artifact. */
        Hashes: {
            /** @description MD5 checksum in hexadecimal form. */
            md5?: string;
            /** @description SHA-1 checksum in hexadecimal form. */
            sha1?: string;
            /** @description SHA-256 checksum in hexadecimal form. */
            sha256?: string;
        };
        /** @description File or payload submitted to or produced by an analysis. */
        Artifact: {
            /**
             * Format: uuid
             * @description Deterministic Gateway identifier of the artifact.
             */
            id: string;
            /** @description File name reported by the source or caller. */
            name: string;
            /** @description Reported or detected MIME type. */
            mime?: string;
            /**
             * Format: int64
             * @description Artifact size in bytes.
             */
            size?: number;
            /** @description Checksums known for the artifact. */
            hashes: components["schemas"]["Hashes"];
        };
        /** @description Normalized result of an artifact analysis. */
        Analysis: {
            /**
             * Format: uuid
             * @description Gateway identifier of the analysis.
             */
            id: string;
            /**
             * @description Current processing state of the analysis.
             * @enum {string}
             */
            status: "completed";
            /** @description Primary artifact that was analyzed. */
            artifact: components["schemas"]["Artifact"];
            /** @description Final normalized assessment of the primary artifact. */
            verdict: components["schemas"]["Verdict"];
            /** @description Additional artifacts extracted or discovered during analysis. */
            artifacts: components["schemas"]["Artifact"][];
            /** @description Selected engine and behavior details from the analysis provider. */
            attributes?: {
                [key: string]: unknown;
            };
            /** @description Source task from which this result was normalized. */
            provenance: components["schemas"]["Provenance"];
        };
        /** @description Request to analyze a known artifact with one source. */
        CreateArtifactAnalysisRequest: {
            /** @description Source code of the artifact-analysis provider. */
            source: string;
            /** @description Metadata used to identify the artifact for analysis. */
            artifact: {
                /** @description File name of the artifact. */
                name: string;
                /** @description MIME type when known by the caller. */
                mime?: string;
                /** @description Checksums known by the caller. */
                hashes?: components["schemas"]["Hashes"];
            };
        };
        /** @description Error returned when a request cannot be completed. */
        ErrorEnvelope: {
            /** @description Structured error details. */
            error: {
                /** @description Stable machine-readable error code. */
                code: string;
                /** @description Safe human-readable error summary. */
                message: string;
            };
        };
        /** @description Normalized security assessment returned by a source. */
        Verdict: {
            /**
             * @description Normalized assessment of the object.
             * @enum {string}
             */
            value: "malicious" | "suspicious" | "clean" | "unknown";
            /**
             * Format: double
             * @description Provider confidence from 0 to 1.
             */
            confidence: number;
            /** @description Provider classifications preserved as short labels. */
            labels: string[];
            /** @description Source code of the provider that produced the verdict. */
            provider: string;
        };
        /** @description Origin of a normalized record. */
        Provenance: {
            /** @description Source code that supplied the record. */
            source: string;
            /** @description Identifier of the record in the source system. */
            external_id: string;
            /**
             * Format: uri
             * @description Optional link to the record in the source system.
             */
            source_url?: string;
            /**
             * Format: date-time
             * @description Time when the Gateway obtained the source data.
             */
            fetched_at: string;
        };
        /** @description Endpoint asset reported by an endpoint-security source. */
        Endpoint: {
            /**
             * Format: uuid
             * @description Deterministic identifier derived from the source and external endpoint ID.
             */
            id: string;
            /** @description Endpoint or agent identifier in the source system. */
            external_id: string;
            /** @description Host name reported for the endpoint. */
            hostname: string;
            /** @description IP addresses currently associated with the endpoint. */
            ip_addresses?: string[];
            /**
             * @description Normalized endpoint connectivity state.
             * @enum {string}
             */
            status: "online" | "offline" | "unknown";
            /** @description Selected inventory and agent fields from the source. */
            attributes: {
                [key: string]: unknown;
            };
            /** @description Source record from which the endpoint was normalized. */
            provenance: components["schemas"]["Provenance"];
        };
        /** @description Response operation advertised for an endpoint; the Gateway does not execute it. */
        ResponseAction: {
            /** @description Stable source action code. */
            code: string;
            /** @description Human-readable action name. */
            title: string;
            /** @description Whether executing the action may disrupt or alter the endpoint. */
            destructive: boolean;
            /** @description Whether the source currently allows the action for the endpoint. */
            enabled: boolean;
        };
        /** @description Filters for endpoint inventory search. */
        SearchEndpointsRequest: {
            /** @description Source codes to query; omit to use every allowed endpoint source. */
            sources?: string[];
            /** @description Free-text query matched against endpoint inventory fields. */
            query?: string;
            /**
             * @description Maximum number of endpoints returned after merging all sources.
             * @default 50
             */
            limit: number;
            /** @description Opaque next_cursor from the previous response with the same filters. */
            cursor?: string;
        };
        /** @description Merged endpoint inventory page. */
        SearchEndpointsResponse: {
            /** @description Normalized endpoints in the current page. */
            items: components["schemas"]["Endpoint"][];
            /** @description Opaque cursor for the next page; absent when the search is exhausted. */
            next_cursor?: string;
            /** @description Per-source failures when at least one selected source succeeded. */
            source_errors: components["schemas"]["SourceError"][];
        };
        /** @description Failure reported by one source during a multi-source request. */
        SourceError: {
            /** @description Source code that failed. */
            source: string;
            /** @description Stable machine-readable failure code. */
            code: string;
            /** @description Safe human-readable failure summary. */
            message: string;
            /** @description Whether repeating the source request may succeed without changing it. */
            retryable: boolean;
        };
        /** @description Request to enrich one entity from one or more sources. */
        LookupEntityRequest: {
            /** @description Source codes to query; omit to use every allowed source with entity lookup. */
            sources?: string[];
            /** @description Entity to normalize and enrich. */
            entity: components["schemas"]["EntityRef"];
        };
        /** @description Entity enrichment merged from the selected sources. */
        LookupEntityResponse: {
            /** @description Matched entity and related canonical entities. */
            entities: components["schemas"]["Entity"][];
            /** @description Relationships between entities in this response. */
            relations: components["schemas"]["Relation"][];
            /** @description Security assessments returned for the requested entity. */
            verdicts: components["schemas"]["Verdict"][];
            /** @description Per-source failures when at least one selected source succeeded. */
            source_errors: components["schemas"]["SourceError"][];
        };
        /** @description Entity value used as a search or lookup condition. */
        EntityRef: {
            /** @description Canonical entity kind, such as ip, domain, hostname, email, or hash. */
            type: string;
            /** @description Entity value to normalize and look up. */
            value: string;
        };
        /** @description Source record in which a canonical entity was observed. */
        EntitySource: {
            source_code: string;
            source_entity_id: string;
            /** Format: uri */
            source_ref?: string;
            /** Format: date-time */
            fetched_at: string;
        };
        /** @description Canonical representation of an observable or asset. */
        Entity: {
            /** @description Canonical entity kind. */
            type: string;
            /** @description Normalized entity value used for deduplication. */
            value: string;
            /** @description Selected source-specific fields; never the complete vendor response. */
            attributes: {
                [key: string]: unknown;
            };
            /** @description Source records in which this entity was observed. */
            sources: components["schemas"]["EntitySource"][];
        };
        /** @description Normalized relationship between two canonical entities. */
        Relation: {
            /** @description Normalized relationship type, such as connected_to or resolves_to. */
            type: string;
            /** @description Canonical entity from which the relationship starts. */
            source_entity: components["schemas"]["EntityRef"];
            /** @description Canonical entity at which the relationship ends. */
            target_entity: components["schemas"]["EntityRef"];
            /**
             * Format: date-time
             * @description Optional time when the relationship was observed.
             */
            occurred_at?: string;
            /** @description Code of the source that supplied the relationship. */
            source_code: string;
            /** @description Original relationship identifier assigned by that source. */
            source_relation_id: string;
            /** Format: uri */
            source_ref?: string;
            /** Format: date-time */
            fetched_at: string;
        };
        /** @description Security event normalized from one source record. */
        Event: {
            /** @description Code of the source that owns the event. */
            source_code: string;
            /** @description Original event identifier assigned by that source. */
            source_event_id: string;
            /**
             * Format: uri
             * @description Optional link to the event in its source system.
             */
            source_ref?: string;
            /** @description Normalized event class. */
            type: string;
            /** @description Short human-readable event summary. */
            title: string;
            /**
             * @description Severity mapped to the Gateway scale.
             * @enum {string}
             */
            severity: "info" | "low" | "medium" | "high" | "critical" | "unknown";
            /**
             * Format: date-time
             * @description Time when the event occurred in the source system.
             */
            occurred_at: string;
            /** @description Canonical entities mentioned by the event. */
            entities: components["schemas"]["EntityRef"][];
            /** @description Selected event fields that have no canonical top-level property. */
            attributes: {
                [key: string]: unknown;
            };
            /**
             * Format: date-time
             * @description Time when the Gateway obtained the source data.
             */
            fetched_at: string;
        };
        /** @description Source records selected by a client for persistence in an investigation. */
        ResolveContextRequest: {
            events: components["schemas"]["EventSourceRef"][];
            entities: components["schemas"]["EntitySourceRef"][];
        };
        /** @description Normalized records and relationships resolved from source-owned identifiers. */
        ResolveContextResponse: {
            events: components["schemas"]["Event"][];
            entities: components["schemas"]["Entity"][];
            relations: components["schemas"]["Relation"][];
            source_errors: components["schemas"]["SourceError"][];
        };
        /** @description Inclusive event occurrence-time interval. */
        TimeRange: {
            /**
             * Format: date-time
             * @description Inclusive lower boundary of event occurrence time.
             */
            from: string;
            /**
             * Format: date-time
             * @description Inclusive upper boundary of event occurrence time.
             */
            to: string;
        };
        /** @description Filters for a normalized multi-source event search. */
        SearchEventsRequest: {
            /** @description Source codes to query; omit to use every allowed source with event search. */
            sources?: string[];
            /** @description Optional occurrence-time interval. */
            time_range?: components["schemas"]["TimeRange"];
            /** @description Free-text query interpreted by each selected source. */
            query?: string;
            /** @description Entity conditions; an event matches when it contains at least one listed entity. */
            entities?: components["schemas"]["EntityRef"][];
            /**
             * @description Maximum number of events returned after merging all sources.
             * @default 50
             */
            limit: number;
            /** @description Opaque next_cursor from the previous response with the same filters. */
            cursor?: string;
        };
        /** @description Merged event page with the entities and relations needed to interpret it. */
        SearchEventsResponse: {
            /** @description Normalized events in the current page. */
            events: components["schemas"]["Event"][];
            /** @description Canonical entities referenced by the returned events. */
            entities: components["schemas"]["Entity"][];
            /** @description Relationships whose endpoints are present in the returned entities. */
            relations: components["schemas"]["Relation"][];
            /** @description Opaque cursor for the next page; absent when the search is exhausted. */
            next_cursor?: string;
            /** @description Per-source failures when at least one selected source succeeded. */
            source_errors: components["schemas"]["SourceError"][];
        };
        /** @description Stable reference to an event in its source system. */
        EventSourceRef: {
            /** @description Code of the source that owns the event. */
            source_code: string;
            /** @description Original event identifier assigned by that source. */
            source_event_id: string;
        };
        /** @description Stable reference to an entity record in its source system. */
        EntitySourceRef: {
            /** @description Code of the source that owns the entity record. */
            source_code: string;
            /** @description Original entity identifier assigned by that source. */
            source_entity_id: string;
        };
        /** @description Service health response. */
        Health: {
            /**
             * @description Current health state of the checked component.
             * @enum {string}
             */
            status: "ok";
        };
        /**
         * @description Operation that a source can perform through the Gateway.
         * @enum {string}
         */
        Capability: "events" | "entity_lookup" | "artifact_analysis" | "endpoints" | "response_catalog";
        /** @description External security product registered in the Gateway. */
        Source: {
            /** @description Stable source identifier used in requests and provenance. */
            code: string;
            /** @description Human-readable product name. */
            name: string;
            /**
             * @description Functional class of the security product.
             * @enum {string}
             */
            kind: "siem" | "ndr" | "edr" | "sandbox" | "threat_intelligence";
            /**
             * @description Adapter mode currently backing the source.
             * @enum {string}
             */
            mode: "mock" | "proxy";
            /**
             * @description Whether the source is available for requests.
             * @enum {string}
             */
            status: "available" | "unavailable";
            /** @description Operations implemented by this source. */
            capabilities: components["schemas"]["Capability"][];
        };
    };
    responses: {
        /** @description Error response. */
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description The request is malformed or violates an input constraint. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description A valid bearer access token is required. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description The caller has no role in the project or the source is not allowed there. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description The selected source or requested record does not exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description The selected source cannot perform the requested operation. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description An unexpected internal failure occurred. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description The Gateway or selected source exceeded its deadline. */
        GatewayTimeout: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Every selected external source failed. */
        BadGateway: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Service health. */
        HealthResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Health"];
            };
        };
    };
    parameters: {
        /** @description Sb0rka project whose integration allowlist is used. */
        ProjectId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createArtifactAnalysis: {
        parameters: {
            query?: never;
            header: {
                /** @description Sb0rka project whose integration allowlist is used. */
                "X-Project-ID": components["parameters"]["ProjectId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateArtifactAnalysisRequest"];
            };
        };
        responses: {
            /** @description Completed mock analysis. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Analysis"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
            504: components["responses"]["GatewayTimeout"];
            default: components["responses"]["ErrorResponse"];
        };
    };
    getArtifactAnalysis: {
        parameters: {
            query?: never;
            header: {
                /** @description Sb0rka project whose integration allowlist is used. */
                "X-Project-ID": components["parameters"]["ProjectId"];
            };
            path: {
                /** @description Gateway identifier of the artifact analysis. */
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Artifact analysis. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Analysis"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
            504: components["responses"]["GatewayTimeout"];
            default: components["responses"]["ErrorResponse"];
        };
    };
    searchEndpoints: {
        parameters: {
            query?: never;
            header: {
                /** @description Sb0rka project whose integration allowlist is used. */
                "X-Project-ID": components["parameters"]["ProjectId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchEndpointsRequest"];
            };
        };
        responses: {
            /** @description EDR endpoints. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchEndpointsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
            502: components["responses"]["BadGateway"];
            504: components["responses"]["GatewayTimeout"];
            default: components["responses"]["ErrorResponse"];
        };
    };
    listResponseActions: {
        parameters: {
            query?: never;
            header: {
                /** @description Sb0rka project whose integration allowlist is used. */
                "X-Project-ID": components["parameters"]["ProjectId"];
            };
            path: {
                /** @description Source code of the endpoint-security product. */
                source: string;
                /** @description Endpoint identifier in the selected source system. */
                external_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Read-only response action catalogue. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Response operations currently advertised for the endpoint. */
                        items: components["schemas"]["ResponseAction"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
            504: components["responses"]["GatewayTimeout"];
            default: components["responses"]["ErrorResponse"];
        };
    };
    lookupEntity: {
        parameters: {
            query?: never;
            header: {
                /** @description Sb0rka project whose integration allowlist is used. */
                "X-Project-ID": components["parameters"]["ProjectId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LookupEntityRequest"];
            };
        };
        responses: {
            /** @description Context gathered for an entity. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LookupEntityResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
            502: components["responses"]["BadGateway"];
            504: components["responses"]["GatewayTimeout"];
            default: components["responses"]["ErrorResponse"];
        };
    };
    searchEvents: {
        parameters: {
            query?: never;
            header: {
                /** @description Sb0rka project whose integration allowlist is used. */
                "X-Project-ID": components["parameters"]["ProjectId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchEventsRequest"];
            };
        };
        responses: {
            /** @description Normalized events and their context. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchEventsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
            502: components["responses"]["BadGateway"];
            504: components["responses"]["GatewayTimeout"];
            default: components["responses"]["ErrorResponse"];
        };
    };
    resolveContext: {
        parameters: {
            query?: never;
            header: {
                /** @description Sb0rka project whose integration allowlist is used. */
                "X-Project-ID": components["parameters"]["ProjectId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveContextRequest"];
            };
        };
        responses: {
            /** @description Current normalized data for every selected source record. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveContextResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
            502: components["responses"]["BadGateway"];
            504: components["responses"]["GatewayTimeout"];
            default: components["responses"]["ErrorResponse"];
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["HealthResponse"];
        };
    };
    ping: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description pong */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example pong */
                    "text/plain": string;
                };
            };
        };
    };
    listSources: {
        parameters: {
            query?: never;
            header: {
                /** @description Sb0rka project whose integration allowlist is used. */
                "X-Project-ID": components["parameters"]["ProjectId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered sources. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description External security products registered for use through the Gateway. */
                        items: components["schemas"]["Source"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
            default: components["responses"]["ErrorResponse"];
        };
    };
}
