/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Источники улик
         * @description Доступно всем ролям — фронту нужен список для фильтров и лейблов.
         */
        get: operations["listSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/extensions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Расширения обогащения
         * @description Allowlist. Фронт показывает только разрешённые в карточке артефакта.
         */
        get: operations["listExtensions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/linking-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Правила связывания */
        get: operations["listLinkingRules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/linking-rules/{rule_code}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_code: components["parameters"]["RuleCode"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Изменить правило связывания
         * @description Правила — конфигурация, не код: набор признаков связывания задаёт заказчик.
         *     Изменение не переписывает уже созданные рёбра.
         */
        patch: operations["updateLinkingRule"];
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Роли субъектов тенанта */
        get: operations["listRoleBindings"];
        put?: never;
        /**
         * Назначить роль
         * @description Роли SOC (l1, l2, lead, admin) не совпадают с ролями проекта платформы —
         *     это отдельный вокабуляр, привязанный к субъекту в тенанте.
         */
        post: operations["createRoleBinding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{subject_id}/{role}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: components["parameters"]["SubjectId"];
                role: "l1" | "l2" | "lead" | "admin";
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Снять роль */
        delete: operations["deleteRoleBinding"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Журнал действий
         * @description Действия пользователей, агентов и системы. Append-only, только чтение.
         *     Фильтр по investigation_id — журнал одного расследования.
         */
        get: operations["listAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/investigations/{investigation_id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        /**
         * Метрики расследования
         * @description Счётчики из журнала действий для оценки сокращения ручных шагов.
         */
        get: operations["getInvestigationMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Состояние источников и расширений
         * @description Плашка в интерфейсе — недоступность источника видна аналитику, а не молча ломает выборку.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/investigations/{investigation_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        /** Артефакты расследования */
        get: operations["listArtifacts"];
        put?: never;
        /** Добавить артефакт */
        post: operations["createArtifact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: components["parameters"]["ArtifactId"];
            };
            cookie?: never;
        };
        /** Артефакт с вердиктами обогащений */
        get: operations["getArtifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artifacts/{artifact_id}/enrich": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: components["parameters"]["ArtifactId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Обогатить артефакт расширением
         * @description Репутация, декодирование, песочница. Расширение берётся из allowlist;
         *     каждый внешний вызов помечается в аудите как передача данных наружу.
         *     Недоступность расширения не ошибка запроса — вернётся вердикт status=error.
         */
        post: operations["enrichArtifact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/investigations/{investigation_id}/iocs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Массовый ввод индикаторов
         * @description Создаёт артефакты и сущности из списка индикаторов. С retro_search=true
         *     ищет их по источникам и затягивает найденное — оценка распространения
         *     по узлам инфраструктуры. Большая выборка уходит в фон (job_id).
         */
        post: operations["importIocs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/investigations/{investigation_id}/entities": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        /** Сущности расследования */
        get: operations["listEntities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: components["parameters"]["EntityId"];
            };
            cookie?: never;
        };
        /**
         * Карточка сущности
         * @description Историчность и окружение в текущем расследовании плюс кросс-кейсовые
         *     вхождения того же (type_code, canonical_key) в других расследованиях тенанта.
         */
        get: operations["getEntityCard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/investigations/{investigation_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        /**
         * События расследования (таймлайн)
         * @description Сортировка по occurred_at, id — стабильный keyset-курсор.
         */
        get: operations["listEvents"];
        put?: never;
        /**
         * Затянуть события в расследование
         * @description Принимает либо явные ссылки на записи источника, либо параметры выборки.
         *     Идемпотентно по dedup_key. Синхронно извлекает сущности, создаёт узлы
         *     графа и прогоняет правила связывания (до 500 событий; больше — 422,
         *     разбить выборку).
         */
        post: operations["attachEvents"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        /**
         * Событие целиком
         * @description Включая normalized_data, raw_data и source_ref для drill-down в консоль источника.
         */
        get: operations["getEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/investigations/{investigation_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        /**
         * Граф расследования
         * @description Узлы и рёбра одного расследования. include_subtree=true возвращает
         *     объединение подграфов поддерева как есть (узлы пер-кейсовые); клиент
         *     группирует дубликаты сущностей по (type_code, canonical_key) из полей
         *     узла. Rejected-рёбра по умолчанию скрыты.
         */
        get: operations["getGraph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/investigations/{investigation_id}/edges": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Создать ребро (аналитик)
         * @description origin=analyst, рождается confirmed. evidence_event_ids необязателен для
         *     аналитика, обязателен в internal-контуре агента. relation_code валидируется
         *     против RelationTypes (source_kind/target_kind должны совпасть с типами узлов).
         *     Повтор той же тройки (source, target, relation_code) — 409.
         */
        post: operations["createEdge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/edges/{edge_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                edge_id: components["parameters"]["EdgeId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Подтвердить или отклонить ребро
         * @description reject требует reject_reason. Версия обязательна (409 при расхождении).
         */
        patch: operations["updateEdge"];
        trace?: never;
    };
    "/investigations/{investigation_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Батч-ревизия proposed-рёбер
         * @description Одна транзакция: либо применяется весь батч, либо ничего.
         *     Конфликт версии любого элемента — 409 с details.conflicts=[edge_id,...],
         *     состояние БД не меняется.
         */
        post: operations["reviewEdges"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/investigations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список расследований
         * @description Без parent_id возвращает корневые. parent_id=<uuid> — прямых потомков.
         */
        get: operations["listInvestigations"];
        put?: never;
        /** Создать расследование или под-расследование */
        post: operations["createInvestigation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/investigations/{investigation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        /** Карточка расследования */
        get: operations["getInvestigation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Изменить расследование
         * @description Закрытие (status=closed) требует verdict; verdict=rejected требует
         *     verdict_reason. Для под-расследования verdict=confirmed требует хотя бы
         *     одного привязанного события — нарушение возвращает 422 с
         *     details.reason=evidence_required. Мутации в закрытом расследовании
         *     запрещены (409, code=conflict), кроме переоткрытия: PATCH со
         *     status=open очищает verdict/verdict_reason/closed_at и пишется в аудит.
         */
        patch: operations["updateInvestigation"];
        trace?: never;
    };
    "/investigations/{investigation_id}/tree": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        /**
         * Поддерево расследования
         * @description Плоский пре-ордер с depth; клиент собирает дерево по parent_id за один проход.
         */
        get: operations["getInvestigationTree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/investigations/{investigation_id}/response-packages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        /** Пакеты расследования */
        get: operations["listResponsePackages"];
        put?: never;
        /**
         * Собрать пакет реагирования
         * @description Включаются только подтверждённые артефакты. Пустой artifact_ids — все
         *     подтверждённые артефакты расследования и его поддерева.
         */
        post: operations["createResponsePackage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/response-packages/{package_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: components["parameters"]["PackageId"];
            };
            cookie?: never;
        };
        /** Пакет реагирования */
        get: operations["getResponsePackage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Зафиксировать пакет
         * @description Перевод в final. Финальный пакет неизменяем — повторный PATCH вернёт 409.
         */
        patch: operations["finalizeResponsePackage"];
        trace?: never;
    };
    "/response-packages/{package_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: components["parameters"]["PackageId"];
            };
            cookie?: never;
        };
        /**
         * Выгрузить пакет для EDR
         * @description Тело в формате пакета (json/csv/stix) для загрузки в средство защиты.
         */
        get: operations["exportResponsePackage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/investigations/{investigation_id}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        /** Отчёты расследования */
        get: operations["listReports"];
        put?: never;
        /**
         * Сгенерировать отчёт по инциденту
         * @description Генерация асинхронная: возвращается запись со status=pending, файл
         *     появляется в storage_ref. Содержимое собирается из подтверждённых данных;
         *     отклонённые ветки входят как «проверено и исключено».
         */
        post: operations["createReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: components["parameters"]["ReportId"];
            };
            cookie?: never;
        };
        /** Статус отчёта */
        get: operations["getReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{report_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: components["parameters"]["ReportId"];
            };
            cookie?: never;
        };
        /** Скачать отчёт */
        get: operations["downloadReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entity-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Типы сущностей */
        get: operations["listEntityTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/relation-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Типы связей */
        get: operations["listRelationTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/graph-nodes/{node_id}/issues": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        /** Задачи узла */
        get: operations["listNodeIssues"];
        put?: never;
        /**
         * Создать исследовательскую задачу по узлу
         * @description Создаёт issue в SOM («что происходило на узле», «проверить контекст по
         *     таймлайну») и связывает с узлом графа. Агенты работают в sub-issues SOM.
         */
        post: operations["createNodeIssue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/investigations/{investigation_id}/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        /** Workflows расследования */
        get: operations["listWorkflows"];
        put?: never;
        /** Привязать агентский workflow SOM */
        post: operations["linkWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Лента сработок источников
         * @description Триаж: сработки всех подключённых источников на лету, без персиста
         *     (единственное представление вне расследования). Из сработки заводится
         *     расследование через POST /investigations с from_alert.
         */
        get: operations["listAlerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Сквозной поиск по источникам
         * @description Поиск вне расследования — pivot по значению (хеш, адрес, имя узла) по всем
         *     включённым источникам. Отвечает на вопрос «где ещё это встречалось»
         *     до затягивания улик в кейс. Недоступные источники перечислены в partial,
         *     результат при этом возвращается.
         */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Журнал действий пользователя, агента и системы. Append-only.
         *     Источник метрики сокращения числа шагов.
         */
        AuditEntry: {
            /** Format: int64 */
            id: number;
            /** Format: uuid */
            investigation_id?: string | null;
            /** @enum {string} */
            actor_type: "user" | "agent" | "system";
            actor_id: string;
            action: string;
            payload?: {
                [key: string]: unknown;
            };
            /** @description Данные ушли во внешний сервис */
            external_call?: boolean;
            /** Format: date-time */
            ts: string;
        };
        AuditPage: {
            items: components["schemas"]["AuditEntry"][];
            next_cursor?: string | null;
        };
        /** @description Расширение обогащения (MCP/skill). По умолчанию выключено — allowlist. */
        Extension: {
            code: string;
            /** @enum {string} */
            kind: "mcp" | "skill" | "a2a";
            title: string;
            is_allowed: boolean;
            /** @description Признак «данные уходят наружу» — требует согласования (п.6.4 ТЗ) */
            sends_data_externally: boolean;
        };
        /**
         * @description Счётчики из журнала действий для метрики сокращения ручных шагов.
         *     baseline_steps задаётся при фиксации эталонного прогона.
         */
        InvestigationMetrics: {
            /** Format: uuid */
            investigation_id: string;
            /** @description Действий аналитика в расследовании */
            actions: number;
            elapsed_seconds: number;
            agent_actions?: number;
            events_attached?: number;
            edges_proposed?: number;
            edges_confirmed?: number;
            /** @description Шагов в исходных консолях, если эталон зафиксирован */
            baseline_steps?: number | null;
            /** @description (baseline_steps − actions) / baseline_steps */
            reduction?: number | null;
        };
        /**
         * @description Правило связывания — детерминированный не-LLM путь построения рёбер.
         *     Система строит граф без агента (инвариант И-4).
         */
        LinkingRule: {
            code: string;
            title: string;
            /** @enum {string} */
            kind: "chain-join" | "identity-join" | "temporal-join" | "pair-join";
            /** @description match, window_sec, relation_code, confidence */
            rule?: {
                [key: string]: unknown;
            };
            born_status: components["schemas"]["EdgeStatus"];
            is_enabled: boolean;
        };
        LinkingRulePatch: {
            title?: string;
            rule?: {
                [key: string]: unknown;
            };
            born_status?: components["schemas"]["EdgeStatus"];
            is_enabled?: boolean;
        };
        /** @description Роль субъекта платформы в тенанте. Вокабуляр SOC, не платформенный. */
        RoleBinding: {
            /** Format: uuid */
            subject_id: string;
            /** @enum {string} */
            role: "l1" | "l2" | "lead" | "admin";
            /** Format: uuid */
            granted_by_subject_id?: string | null;
            /** Format: date-time */
            created_at?: string;
        };
        RoleBindingCreate: {
            /** Format: uuid */
            subject_id: string;
            /** @enum {string} */
            role: "l1" | "l2" | "lead" | "admin";
        };
        /** @description Источник улик. Секреты не возвращаются — только ссылка secret_ref. */
        Source: {
            code: string;
            /** @enum {string} */
            kind: "siem" | "edr" | "ndr" | "infra" | "sandbox" | "other";
            title: string;
            secret_ref?: string | null;
            is_enabled: boolean;
        };
        SourceHealth: {
            code: string;
            /** @enum {string} */
            status: "ok" | "degraded" | "unavailable";
            /** Format: date-time */
            last_ok_at?: string | null;
            last_error?: string | null;
            /** Format: date-time */
            checked_at?: string;
        };
        ErrorResponse: {
            error: {
                /**
                 * @description not_implemented — ручка объявлена в контракте, но ещё не реализована.
                 *     Клиент может отличить её от настоящей поломки сервера и скрыть
                 *     элемент интерфейса, а не показывать ошибку.
                 * @enum {string}
                 */
                code: "unauthorized" | "forbidden" | "not_found" | "conflict" | "validation" | "source_unavailable" | "som_unavailable" | "not_implemented" | "internal";
                message: string;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        /** @enum {string} */
        EdgeStatus: "proposed" | "confirmed" | "rejected";
        /**
         * @description Индикатор компрометации в скоупе расследования: хеш, адрес, домен, файл.
         *     Накапливает вердикты обогащений от внешних расширений.
         */
        Artifact: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            investigation_id: string;
            /** @description Тип из справочника EntityType */
            type_code: string;
            value: string;
            /**
             * Format: uuid
             * @description Связанная сущность графа
             */
            entity_id?: string | null;
            /** @description Файл в object storage */
            storage_ref?: string | null;
            media_type?: string | null;
            checksum?: string | null;
            is_bundle?: boolean;
            /** @description Ключ — код расширения */
            enrichment_verdicts?: {
                [key: string]: components["schemas"]["EnrichmentVerdict"];
            };
            metadata?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
        };
        ArtifactCreate: {
            type_code: string;
            value: string;
            /** Format: uuid */
            entity_id?: string;
            metadata?: {
                [key: string]: unknown;
            };
        };
        ArtifactPage: {
            items: components["schemas"]["Artifact"][];
            next_cursor?: string | null;
        };
        EnrichRequest: {
            /** @description Код расширения из allowlist. Недоступность не валит запрос — вернётся status=error */
            extension_code: string;
        };
        EnrichmentVerdict: {
            extension_code: string;
            /** @enum {string} */
            status: "clean" | "suspicious" | "malicious" | "unknown" | "error";
            score?: number | null;
            detail?: {
                [key: string]: unknown;
            };
            /** @description Данные уходили наружу — отражено в аудите (п.6.4 ТЗ) */
            external_call?: boolean;
            cached?: boolean;
            /** Format: date-time */
            enriched_at: string;
        };
        /**
         * @description Массовый ввод индикаторов. Создаёт артефакты и сущности, запускает
         *     ретро-поиск по источникам — закрывает задачу оценки распространения.
         */
        IocImportRequest: {
            items: {
                type_code: string;
                value: string;
            }[];
            /**
             * @description Искать индикаторы по источникам и затягивать найденное в расследование
             * @default false
             */
            retro_search: boolean;
            /** Format: date-time */
            from?: string;
            /** Format: date-time */
            to?: string;
        };
        IocImportResult: {
            created: number;
            duplicates: number;
            /** @description Затянуто событий ретро-поиском */
            retro_events_attached?: number;
            /**
             * Format: uuid
             * @description Если ретро-поиск ушёл в фон
             */
            job_id?: string | null;
        };
        Entity: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            investigation_id: string;
            type_code: string;
            canonical_key: string;
            display_name?: string | null;
            metadata?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            first_seen?: string | null;
            /** Format: date-time */
            last_seen?: string | null;
        };
        EntityCard: {
            entity: components["schemas"]["Entity"];
            /** @description Событий с участием в текущем расследовании */
            events_count: number;
            /** @description Тот же (type_code, canonical_key) в других расследованиях тенанта */
            occurrences: {
                /** Format: uuid */
                investigation_id: string;
                title: string;
                events_count: number;
            }[];
            /** @description Соседи по подтверждённым рёбрам */
            neighbors?: {
                /** Format: uuid */
                entity_id: string;
                display_name?: string | null;
                relation_code: string;
            }[];
        };
        EntityPage: {
            items: components["schemas"]["Entity"][];
            next_cursor?: string | null;
        };
        Event: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            investigation_id: string;
            source_code: string;
            source_event_id: string;
            /** @description Ссылка/запрос для drill-down к исходной записи */
            source_ref?: string | null;
            event_type: string;
            /** Format: date-time */
            occurred_at: string;
            /** Format: date-time */
            ingested_at: string;
            /** @description Конверт subject-action-object-status */
            normalized_data?: {
                [key: string]: unknown;
            };
            raw_data?: {
                [key: string]: unknown;
            } | null;
            /** @description Участники события с ролями */
            entities?: {
                /** Format: uuid */
                entity_id: string;
                relation_code: string;
            }[];
        };
        /** @description Ровно одно из полей refs или query. */
        EventAttachRequest: {
            refs?: {
                source_code: string;
                source_event_id: string;
            }[];
            /** @description Выборка из источника (EvidenceSource.Search) */
            query?: {
                source_code: string;
                entity_key?: string;
                /** Format: date-time */
                from?: string;
                /** Format: date-time */
                to?: string;
                substring?: string;
                /** @default 100 */
                limit: number;
            };
            /** @description Зачем затянуто — нарратив расследования, идёт в аудит */
            reason?: string;
        };
        EventAttachResult: {
            attached: number;
            /** @description Отброшено по dedup_key */
            duplicates: number;
            entities_extracted: number;
            /** @description Рёбра от правил связывания */
            edges_created: number;
        };
        EventPage: {
            items: components["schemas"]["Event"][];
            next_cursor?: string | null;
        };
        Edge: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            investigation_id: string;
            /** Format: uuid */
            source_node_id: string;
            /** Format: uuid */
            target_node_id: string;
            relation_code: string;
            status: components["schemas"]["EdgeStatus"];
            reject_reason?: string | null;
            confidence?: number | null;
            /** @description Обоснование. Обязательно при origin=agent */
            why?: string | null;
            origin: components["schemas"]["Origin"];
            /** @description subject_id | код правила | id запуска */
            origin_ref?: string | null;
            evidence_count: number;
            evidence_event_ids?: string[];
            metadata?: {
                [key: string]: unknown;
            };
            version: number;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        EdgeCreate: {
            /** Format: uuid */
            source_node_id: string;
            /** Format: uuid */
            target_node_id: string;
            relation_code: string;
            confidence?: number;
            why?: string;
            /** @description События-основания того же расследования (иначе 422) */
            evidence_event_ids?: string[];
        };
        EdgePatch: {
            version: number;
            /** @enum {string} */
            status: "confirmed" | "rejected";
            /** @description Обязателен при status=rejected */
            reject_reason?: string;
        };
        Graph: {
            /** Format: uuid */
            investigation_id: string;
            include_subtree?: boolean;
            nodes: components["schemas"]["GraphNode"][];
            edges: components["schemas"]["Edge"][];
        };
        GraphNode: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            investigation_id: string;
            node_type: components["schemas"]["NodeType"];
            /** Format: uuid */
            entity_id?: string | null;
            /** Format: uuid */
            event_id?: string | null;
            origin: components["schemas"]["Origin"];
            /** @description display_name сущности или сводка события */
            label?: string;
            /** @description Тип сущности (иконка узла). Только для node_type=entity */
            type_code?: string | null;
            /** @description Ключ для группировки дубликатов при include_subtree */
            canonical_key?: string | null;
            /**
             * Format: date-time
             * @description Только для node_type=event
             */
            occurred_at?: string | null;
        };
        /** @description Хотя бы одно из полей непусто. */
        ReviewRequest: {
            confirm?: {
                /** Format: uuid */
                id: string;
                version: number;
            }[];
            reject?: {
                /** Format: uuid */
                id: string;
                version: number;
                reason: string;
            }[];
        };
        ReviewResult: {
            confirmed: string[];
            rejected: string[];
        };
        /** @enum {string} */
        NodeType: "entity" | "event";
        /** @enum {string} */
        Origin: "analyst" | "rule" | "agent";
        Investigation: {
            /** Format: uuid */
            id: string;
            project_id: string;
            /** Format: uuid */
            parent_id?: string | null;
            title: string;
            description?: string | null;
            status: components["schemas"]["InvestigationStatus"];
            severity?: (string & components["schemas"]["Severity"]) | null;
            verdict?: (string & components["schemas"]["Verdict"]) | null;
            verdict_reason?: string | null;
            confidence?: number | null;
            /** @description Кто создал: аналитик через API, правило или агент. Ставится сервером по способу создания, клиентом не задаётся. */
            origin?: components["schemas"]["Origin"];
            /** @description Кто именно — subject_id аналитика, код правила или id запуска */
            origin_ref?: string | null;
            version: number;
            counters: {
                children: number;
                events: number;
                entities: number;
                proposed_edges: number;
            };
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            closed_at?: string | null;
        };
        InvestigationCreate: {
            title: string;
            description?: string;
            /**
             * Format: uuid
             * @description Родитель. NULL — корневой кейс. Потомок наследует project_id родителя.
             */
            parent_id?: string;
            /** @description Тенант sb0rka. Обязателен для корня, запрещён для потомка. */
            project_id?: string;
            severity?: components["schemas"]["Severity"];
        };
        InvestigationPage: {
            items: components["schemas"]["Investigation"][];
            next_cursor?: string | null;
        };
        InvestigationPatch: {
            version: number;
            title?: string;
            description?: string;
            status?: components["schemas"]["InvestigationStatus"];
            verdict?: components["schemas"]["Verdict"];
            /** @description Обоснование вердикта. Обязателен при verdict=rejected */
            verdict_reason?: string;
            /** @description Уверенность в гипотезе. Осмысленна для под-расследования */
            confidence?: number;
            severity?: components["schemas"]["Severity"];
        };
        /** @enum {string} */
        InvestigationStatus: "open" | "closed";
        InvestigationTree: {
            /** Format: uuid */
            root_id: string;
            /** @description Плоский пре-ордер, включая корень (depth=0) */
            items: (components["schemas"]["Investigation"] & {
                depth: number;
            })[];
        };
        /**
         * @description Корень: incident | false_positive | not_affected | inconclusive.
         *     Под-расследование: confirmed | rejected | inconclusive.
         *     Сервис валидирует подмножество по позиции в дереве.
         * @enum {string}
         */
        Verdict: "incident" | "false_positive" | "not_affected" | "inconclusive" | "confirmed" | "rejected";
        /** @enum {string} */
        Severity: "low" | "medium" | "high" | "critical";
        /**
         * @description Отчёт по инциденту. Формируется из подтверждённых данных; отклонённые ветки
         *     входят как «проверено и исключено». snapshot фиксирует данные на момент
         *     генерации — отчёт воспроизводим.
         */
        Report: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            investigation_id: string;
            /** @enum {string} */
            format: "markdown" | "pdf";
            /** @enum {string} */
            status: "pending" | "ready" | "failed";
            /** @description Ссылка на файл в object storage */
            storage_ref?: string | null;
            error?: string | null;
            /** Format: uuid */
            created_by_subject_id?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            completed_at?: string | null;
        };
        ReportCreate: {
            /**
             * @default markdown
             * @enum {string}
             */
            format: "markdown" | "pdf";
            /**
             * @description Включить под-расследования с их вердиктами
             * @default true
             */
            include_subtree: boolean;
            /**
             * @description «Проверено и исключено» — отклонённые ветки с причинами
             * @default true
             */
            include_rejected: boolean;
        };
        ReportPage: {
            items: components["schemas"]["Report"][];
            next_cursor?: string | null;
        };
        /**
         * @description Пакет реагирования: только подтверждённые артефакты расследования,
         *     в формате, пригодном для загрузки в EDR заказчика.
         */
        ResponsePackage: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            investigation_id: string;
            /** @enum {string} */
            status: "draft" | "final";
            /** @enum {string} */
            format: "json" | "csv" | "stix";
            items?: components["schemas"]["ResponsePackageItem"][];
            /** Format: uuid */
            created_by_subject_id?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            exported_at?: string | null;
        };
        ResponsePackageCreate: {
            /**
             * @default json
             * @enum {string}
             */
            format: "json" | "csv" | "stix";
            /** @description Пусто — включить все подтверждённые артефакты расследования */
            artifact_ids?: string[];
        };
        ResponsePackageItem: {
            /** Format: uuid */
            artifact_id: string;
            type_code: string;
            value: string;
            /** @description Узел, на котором индикатор наблюдался */
            node?: string | null;
        };
        ResponsePackagePatch: {
            /**
             * @description Фиксация пакета. Final неизменяем
             * @enum {string}
             */
            status: "final";
        };
        EntityType: {
            code: string;
            title: string;
        };
        RelationType: {
            code: string;
            title: string;
            source_kind: components["schemas"]["NodeType"];
            target_kind: components["schemas"]["NodeType"];
            directed: boolean;
        };
        InvestigationWorkflow: {
            /** Format: uuid */
            workflow_id: string;
            /** Format: uuid */
            investigation_id: string;
            /** Format: date-time */
            created_at: string;
        };
        InvestigationWorkflowList: {
            items: components["schemas"]["InvestigationWorkflow"][];
        };
        NodeIssue: {
            /** Format: uuid */
            issue_id: string;
            /** Format: uuid */
            graph_node_id: string;
            /** @description Ссылка на issue в SOM */
            issue_url?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        NodeIssueCreate: {
            title: string;
            description?: string;
        };
        NodeIssueList: {
            items: components["schemas"]["NodeIssue"][];
        };
        WorkflowLinkCreate: {
            /** Format: uuid */
            workflow_id: string;
        };
        /**
         * @description Сработка источника. Лента триажа — единственное представление вне
         *     расследования; не персистится (инвариант И-1), читается из источника на лету.
         */
        Alert: {
            source_code: string;
            source_event_id: string;
            /** @description Ссылка на сработку в консоли источника */
            source_ref?: string | null;
            title: string;
            severity: components["schemas"]["Severity"];
            /** Format: date-time */
            occurred_at: string;
            /** @description Извлечённые сущности сработки (превью до затяжки в кейс) */
            entities?: {
                type_code: string;
                canonical_key: string;
                display_name?: string | null;
            }[];
            /**
             * Format: uuid
             * @description Заполнено, если по сработке уже заведено расследование
             */
            investigation_id?: string | null;
            /** @description Нормализованный конверт сработки */
            summary?: {
                [key: string]: unknown;
            };
        };
        AlertPage: {
            items: components["schemas"]["Alert"][];
            next_cursor?: string | null;
        };
        /** @description Результат сквозного поиска по источнику (вне расследования) */
        SearchHit: {
            source_code: string;
            source_event_id: string;
            source_ref?: string | null;
            event_type?: string;
            /** Format: date-time */
            occurred_at: string;
            summary?: {
                [key: string]: unknown;
            };
            /** @description Расследования тенанта, куда событие уже затянуто */
            attached_to?: string[];
        };
        SearchResult: {
            items: components["schemas"]["SearchHit"][];
            next_cursor?: string | null;
            /** @description Источники, не ответившие вовремя — результат неполон */
            partial?: {
                source_code: string;
                reason: string;
            }[];
        };
    };
    responses: {
        /** @description Нет или невалиден токен (code=unauthorized) */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Роль не даёт действия или чужой тенант (code=forbidden) */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Не найдено в тенанте субъекта (code=not_found) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Невалидные данные (code=validation) */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Конфликт версии, дубликат или закрытое расследование (code=conflict) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Источник улик недоступен (code=source_unavailable) */
        SourceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description SOM недоступен (code=som_unavailable) */
        SomUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        RuleCode: string;
        SubjectId: string;
        Limit: number;
        /** @description Непрозрачный keyset-курсор из next_cursor предыдущей страницы */
        Cursor: string;
        InvestigationId: string;
        ArtifactId: string;
        EntityId: string;
        EventId: string;
        EdgeId: string;
        PackageId: string;
        ReportId: string;
        NodeId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listSources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Источники */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Source"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listExtensions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Расширения */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Extension"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listLinkingRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Правила */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["LinkingRule"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    updateLinkingRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_code: components["parameters"]["RuleCode"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkingRulePatch"];
            };
        };
        responses: {
            /** @description Правило */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkingRule"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    listRoleBindings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Роли */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["RoleBinding"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createRoleBinding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleBindingCreate"];
            };
        };
        responses: {
            /** @description Назначено */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleBinding"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    deleteRoleBinding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: components["parameters"]["SubjectId"];
                role: "l1" | "l2" | "lead" | "admin";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Снято */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listAudit: {
        parameters: {
            query?: {
                investigation_id?: string;
                actor_type?: "user" | "agent" | "system";
                action?: string;
                /** @description Только вызовы наружу */
                external_call?: boolean;
                from?: string;
                to?: string;
                limit?: components["parameters"]["Limit"];
                /** @description Непрозрачный keyset-курсор из next_cursor предыдущей страницы */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Страница журнала */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
    getInvestigationMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Метрики */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationMetrics"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Состояние */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        sources: components["schemas"]["SourceHealth"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listArtifacts: {
        parameters: {
            query?: {
                type_code?: string;
                limit?: components["parameters"]["Limit"];
                /** @description Непрозрачный keyset-курсор из next_cursor предыдущей страницы */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Страница артефактов */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    createArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArtifactCreate"];
            };
        };
        responses: {
            /** @description Артефакт */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Artifact"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    getArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: components["parameters"]["ArtifactId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Артефакт */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Artifact"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    enrichArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: components["parameters"]["ArtifactId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrichRequest"];
            };
        };
        responses: {
            /** @description Вердикт */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrichmentVerdict"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Расширение не в allowlist или роль не даёт действия (code=forbidden) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    importIocs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IocImportRequest"];
            };
        };
        responses: {
            /** @description Итог импорта */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IocImportResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            502: components["responses"]["SourceUnavailable"];
        };
    };
    listEntities: {
        parameters: {
            query?: {
                type_code?: string;
                limit?: components["parameters"]["Limit"];
                /** @description Непрозрачный keyset-курсор из next_cursor предыдущей страницы */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Страница сущностей */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    getEntityCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: components["parameters"]["EntityId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Карточка */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityCard"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listEvents: {
        parameters: {
            query?: {
                event_type?: string;
                source_code?: string;
                /** @description Только события с участием сущности */
                entity_id?: string;
                from?: string;
                to?: string;
                /** @description Подстрока в normalized_data */
                q?: string;
                limit?: components["parameters"]["Limit"];
                /** @description Непрозрачный keyset-курсор из next_cursor предыдущей страницы */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Страница событий */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    attachEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventAttachRequest"];
            };
        };
        responses: {
            /** @description Итог затяжки */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventAttachResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            502: components["responses"]["SourceUnavailable"];
        };
    };
    getEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Событие */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getGraph: {
        parameters: {
            query?: {
                include_subtree?: boolean;
                min_confidence?: number;
                /** @description Фильтр статусов рёбер, по умолчанию proposed,confirmed */
                statuses?: components["schemas"]["EdgeStatus"][];
            };
            header?: never;
            path: {
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Граф */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Graph"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    createEdge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EdgeCreate"];
            };
        };
        responses: {
            /** @description Ребро */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Edge"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    updateEdge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                edge_id: components["parameters"]["EdgeId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EdgePatch"];
            };
        };
        responses: {
            /** @description Ребро */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Edge"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    reviewEdges: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Итог ревизии */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    listInvestigations: {
        parameters: {
            query?: {
                parent_id?: string;
                status?: components["schemas"]["InvestigationStatus"];
                severity?: components["schemas"]["Severity"];
                /** @description Подстрока в title */
                q?: string;
                limit?: components["parameters"]["Limit"];
                /** @description Непрозрачный keyset-курсор из next_cursor предыдущей страницы */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Страница */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
        };
    };
    createInvestigation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestigationCreate"];
            };
        };
        responses: {
            /** @description Создано */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Investigation"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description parent_id не существует */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    getInvestigation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Расследование со счётчиками */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Investigation"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateInvestigation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestigationPatch"];
            };
        };
        responses: {
            /** @description Обновлено */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Investigation"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    getInvestigationTree: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Поддерево */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationTree"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listResponsePackages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Пакеты */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ResponsePackage"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createResponsePackage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResponsePackageCreate"];
            };
        };
        responses: {
            /** @description Черновик пакета */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponsePackage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    getResponsePackage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: components["parameters"]["PackageId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Пакет */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponsePackage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    finalizeResponsePackage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: components["parameters"]["PackageId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResponsePackagePatch"];
            };
        };
        responses: {
            /** @description Пакет */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponsePackage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    exportResponsePackage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: components["parameters"]["PackageId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Выгрузка */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                    "text/csv": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listReports: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                /** @description Непрозрачный keyset-курсор из next_cursor предыдущей страницы */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Отчёты */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportCreate"];
            };
        };
        responses: {
            /** @description Принято в работу */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    getReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: components["parameters"]["ReportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Отчёт */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    downloadReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: components["parameters"]["ReportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Файл отчёта */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/markdown": string;
                    "application/pdf": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Отчёт ещё не готов или сборка упала (code=conflict) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listEntityTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Справочник */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["EntityType"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listRelationTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Справочник */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["RelationType"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listNodeIssues: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Связки */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeIssueList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createNodeIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NodeIssueCreate"];
            };
        };
        responses: {
            /** @description Связка узел—issue */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeIssue"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["SomUnavailable"];
        };
    };
    listWorkflows: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Привязки */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationWorkflowList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    linkWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowLinkCreate"];
            };
        };
        responses: {
            /** @description Привязано */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationWorkflow"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listAlerts: {
        parameters: {
            query?: {
                source_code?: string;
                severity?: components["schemas"]["Severity"];
                from?: string;
                to?: string;
                /** @description Скрыть сработки, по которым уже заведено расследование */
                only_new?: boolean;
                limit?: components["parameters"]["Limit"];
                /** @description Непрозрачный keyset-курсор из next_cursor предыдущей страницы */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Лента */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
            502: components["responses"]["SourceUnavailable"];
        };
    };
    search: {
        parameters: {
            query: {
                /** @description Значение или подстрока */
                q: string;
                /** @description Трактовать q как значение сущности этого типа */
                type_code?: string;
                /** @description Ограничить источниками; пусто — все включённые */
                source_codes?: string[];
                from?: string;
                to?: string;
                limit?: components["parameters"]["Limit"];
                /** @description Непрозрачный keyset-курсор из next_cursor предыдущей страницы */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Результаты */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
            502: components["responses"]["SourceUnavailable"];
        };
    };
}
