//go:build go1.22

// Package events provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package events

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorResponseErrorCode.
const (
	ErrorResponseErrorCodeConflict          ErrorResponseErrorCode = "conflict"
	ErrorResponseErrorCodeForbidden         ErrorResponseErrorCode = "forbidden"
	ErrorResponseErrorCodeInternal          ErrorResponseErrorCode = "internal"
	ErrorResponseErrorCodeNotFound          ErrorResponseErrorCode = "not_found"
	ErrorResponseErrorCodeNotImplemented    ErrorResponseErrorCode = "not_implemented"
	ErrorResponseErrorCodeSomUnavailable    ErrorResponseErrorCode = "som_unavailable"
	ErrorResponseErrorCodeSourceUnavailable ErrorResponseErrorCode = "source_unavailable"
	ErrorResponseErrorCodeUnauthorized      ErrorResponseErrorCode = "unauthorized"
	ErrorResponseErrorCodeValidation        ErrorResponseErrorCode = "validation"
)

// Valid indicates whether the value is a known member of the ErrorResponseErrorCode enum.
func (e ErrorResponseErrorCode) Valid() bool {
	switch e {
	case ErrorResponseErrorCodeConflict:
		return true
	case ErrorResponseErrorCodeForbidden:
		return true
	case ErrorResponseErrorCodeInternal:
		return true
	case ErrorResponseErrorCodeNotFound:
		return true
	case ErrorResponseErrorCodeNotImplemented:
		return true
	case ErrorResponseErrorCodeSomUnavailable:
		return true
	case ErrorResponseErrorCodeSourceUnavailable:
		return true
	case ErrorResponseErrorCodeUnauthorized:
		return true
	case ErrorResponseErrorCodeValidation:
		return true
	default:
		return false
	}
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		// Code not_implemented — ручка объявлена в контракте, но ещё не реализована.
		// Клиент может отличить её от настоящей поломки сервера и скрыть
		// элемент интерфейса, а не показывать ошибку.
		Code    ErrorResponseErrorCode  `json:"code"`
		Details *map[string]interface{} `json:"details,omitempty"`
		Message string                  `json:"message"`
	} `json:"error"`
}

// ErrorResponseErrorCode not_implemented — ручка объявлена в контракте, но ещё не реализована.
// Клиент может отличить её от настоящей поломки сервера и скрыть
// элемент интерфейса, а не показывать ошибку.
type ErrorResponseErrorCode string

// Event defines model for Event.
type Event struct {
	// Entities Участники события с ролями
	Entities *[]struct {
		EntityId     openapi_types.UUID `json:"entity_id"`
		RelationCode string             `json:"relation_code"`
	} `json:"entities,omitempty"`
	EventType       string             `json:"event_type"`
	Id              openapi_types.UUID `json:"id"`
	IngestedAt      time.Time          `json:"ingested_at"`
	InvestigationId openapi_types.UUID `json:"investigation_id"`

	// NormalizedData Конверт subject-action-object-status
	NormalizedData *map[string]interface{} `json:"normalized_data,omitempty"`
	OccurredAt     time.Time               `json:"occurred_at"`
	RawData        *map[string]interface{} `json:"raw_data,omitempty"`
	SourceCode     string                  `json:"source_code"`
	SourceEventId  string                  `json:"source_event_id"`

	// SourceRef Ссылка/запрос для drill-down к исходной записи
	SourceRef *string `json:"source_ref,omitempty"`
}

// EventAttachRequest Ровно одно из полей refs или query.
type EventAttachRequest struct {
	// Query Выборка из источника (EvidenceSource.Search)
	Query *struct {
		EntityKey  *string    `json:"entity_key,omitempty"`
		From       *time.Time `json:"from,omitempty"`
		Limit      *int       `json:"limit,omitempty"`
		SourceCode string     `json:"source_code"`
		Substring  *string    `json:"substring,omitempty"`
		To         *time.Time `json:"to,omitempty"`
	} `json:"query,omitempty"`

	// Reason Зачем затянуто — нарратив расследования, идёт в аудит
	Reason *string `json:"reason,omitempty"`
	Refs   *[]struct {
		SourceCode    string `json:"source_code"`
		SourceEventId string `json:"source_event_id"`
	} `json:"refs,omitempty"`
}

// EventAttachResult defines model for EventAttachResult.
type EventAttachResult struct {
	Attached int `json:"attached"`

	// Duplicates Отброшено по dedup_key
	Duplicates int `json:"duplicates"`

	// EdgesCreated Рёбра от правил связывания
	EdgesCreated      int `json:"edges_created"`
	EntitiesExtracted int `json:"entities_extracted"`
}

// EventPage defines model for EventPage.
type EventPage struct {
	Items      []EventSummary `json:"items"`
	NextCursor *string        `json:"next_cursor,omitempty"`
}

// EventSummary Событие без сырья: список тянет сотни записей, а raw_data у каждой —
// килобайты. Полное событие отдаёт GET /events/{event_id}.
type EventSummary struct {
	Entities *[]struct {
		EntityId     openapi_types.UUID `json:"entity_id"`
		RelationCode string             `json:"relation_code"`
	} `json:"entities,omitempty"`
	EventType       string                  `json:"event_type"`
	Id              openapi_types.UUID      `json:"id"`
	IngestedAt      time.Time               `json:"ingested_at"`
	InvestigationId openapi_types.UUID      `json:"investigation_id"`
	NormalizedData  *map[string]interface{} `json:"normalized_data,omitempty"`
	OccurredAt      time.Time               `json:"occurred_at"`
	SourceCode      string                  `json:"source_code"`
	SourceEventId   string                  `json:"source_event_id"`
	SourceRef       *string                 `json:"source_ref,omitempty"`
}

// Cursor defines model for Cursor.
type Cursor = string

// EventId defines model for EventId.
type EventId = openapi_types.UUID

// InvestigationId defines model for InvestigationId.
type InvestigationId = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// SourceUnavailable defines model for SourceUnavailable.
type SourceUnavailable = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// ValidationError defines model for ValidationError.
type ValidationError = ErrorResponse

// ListEventsParams defines parameters for ListEvents.
type ListEventsParams struct {
	EventType  *string `form:"event_type,omitempty" json:"event_type,omitempty"`
	SourceCode *string `form:"source_code,omitempty" json:"source_code,omitempty"`

	// EntityId Только события с участием сущности
	EntityId *openapi_types.UUID `form:"entity_id,omitempty" json:"entity_id,omitempty"`
	From     *time.Time          `form:"from,omitempty" json:"from,omitempty"`
	To       *time.Time          `form:"to,omitempty" json:"to,omitempty"`

	// Q Подстрока в normalized_data
	Q     *string `form:"q,omitempty" json:"q,omitempty"`
	Limit *Limit  `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Непрозрачный keyset-курсор из next_cursor предыдущей страницы
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// AttachEventsJSONRequestBody defines body for AttachEvents for application/json ContentType.
type AttachEventsJSONRequestBody = EventAttachRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetEvent Событие целиком
	// (GET /events/{event_id})
	GetEvent(w http.ResponseWriter, r *http.Request, eventId EventId)
	// ListEvents События расследования (таймлайн)
	// (GET /investigations/{investigation_id}/events)
	ListEvents(w http.ResponseWriter, r *http.Request, investigationId InvestigationId, params ListEventsParams)
	// AttachEvents Затянуть события в расследование
	// (POST /investigations/{investigation_id}/events)
	AttachEvents(w http.ResponseWriter, r *http.Request, investigationId InvestigationId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetEvent operation middleware
func (siw *ServerInterfaceWrapper) GetEvent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "event_id" -------------
	var eventId EventId

	err = runtime.BindStyledParameterWithOptions("simple", "event_id", r.PathValue("event_id"), &eventId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "event_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEvent(w, r, eventId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListEvents operation middleware
func (siw *ServerInterfaceWrapper) ListEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "investigation_id" -------------
	var investigationId InvestigationId

	err = runtime.BindStyledParameterWithOptions("simple", "investigation_id", r.PathValue("investigation_id"), &investigationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "investigation_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListEventsParams

	// ------------- Optional query parameter "event_type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "event_type", r.URL.Query(), &params.EventType, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "event_type"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "event_type", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "source_code" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "source_code", r.URL.Query(), &params.SourceCode, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "source_code"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "source_code", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "entity_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "entity_id", r.URL.Query(), &params.EntityId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "entity_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entity_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListEvents(w, r, investigationId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AttachEvents operation middleware
func (siw *ServerInterfaceWrapper) AttachEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "investigation_id" -------------
	var investigationId InvestigationId

	err = runtime.BindStyledParameterWithOptions("simple", "investigation_id", r.PathValue("investigation_id"), &investigationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "investigation_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AttachEvents(w, r, investigationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/investigations/{investigation_id}/events", wrapper.ListEvents)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/investigations/{investigation_id}/events", wrapper.AttachEvents)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/events/{event_id}", wrapper.GetEvent)

	return m
}

type ConflictJSONResponse ErrorResponse

type ForbiddenJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type SourceUnavailableJSONResponse ErrorResponse

type UnauthorizedJSONResponse ErrorResponse

type ValidationErrorJSONResponse ErrorResponse

type GetEventRequestObject struct {
	EventId EventId `json:"event_id"`
}

type GetEventResponseObject interface {
	VisitGetEventResponse(w http.ResponseWriter) error
}

type GetEvent200JSONResponse Event

func (response GetEvent200JSONResponse) VisitGetEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetEvent401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetEvent401JSONResponse) VisitGetEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetEvent403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetEvent403JSONResponse) VisitGetEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetEvent404JSONResponse struct{ NotFoundJSONResponse }

func (response GetEvent404JSONResponse) VisitGetEventResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListEventsRequestObject struct {
	InvestigationId InvestigationId `json:"investigation_id"`
	Params          ListEventsParams
}

type ListEventsResponseObject interface {
	VisitListEventsResponse(w http.ResponseWriter) error
}

type ListEvents200JSONResponse EventPage

func (response ListEvents200JSONResponse) VisitListEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListEvents401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListEvents401JSONResponse) VisitListEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListEvents403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListEvents403JSONResponse) VisitListEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListEvents404JSONResponse struct{ NotFoundJSONResponse }

func (response ListEvents404JSONResponse) VisitListEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListEvents422JSONResponse struct{ ValidationErrorJSONResponse }

func (response ListEvents422JSONResponse) VisitListEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type AttachEventsRequestObject struct {
	InvestigationId InvestigationId `json:"investigation_id"`
	Body            *AttachEventsJSONRequestBody
}

type AttachEventsResponseObject interface {
	VisitAttachEventsResponse(w http.ResponseWriter) error
}

type AttachEvents201JSONResponse EventAttachResult

func (response AttachEvents201JSONResponse) VisitAttachEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type AttachEvents401JSONResponse struct{ UnauthorizedJSONResponse }

func (response AttachEvents401JSONResponse) VisitAttachEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type AttachEvents403JSONResponse struct{ ForbiddenJSONResponse }

func (response AttachEvents403JSONResponse) VisitAttachEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type AttachEvents404JSONResponse struct{ NotFoundJSONResponse }

func (response AttachEvents404JSONResponse) VisitAttachEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type AttachEvents409JSONResponse struct{ ConflictJSONResponse }

func (response AttachEvents409JSONResponse) VisitAttachEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type AttachEvents422JSONResponse struct{ ValidationErrorJSONResponse }

func (response AttachEvents422JSONResponse) VisitAttachEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type AttachEvents502JSONResponse struct{ SourceUnavailableJSONResponse }

func (response AttachEvents502JSONResponse) VisitAttachEventsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetEvent Событие целиком
	// (GET /events/{event_id})
	GetEvent(ctx context.Context, request GetEventRequestObject) (GetEventResponseObject, error)
	// ListEvents События расследования (таймлайн)
	// (GET /investigations/{investigation_id}/events)
	ListEvents(ctx context.Context, request ListEventsRequestObject) (ListEventsResponseObject, error)
	// AttachEvents Затянуть события в расследование
	// (POST /investigations/{investigation_id}/events)
	AttachEvents(ctx context.Context, request AttachEventsRequestObject) (AttachEventsResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetEvent operation middleware
func (sh *strictHandler) GetEvent(w http.ResponseWriter, r *http.Request, eventId EventId) {
	var request GetEventRequestObject

	request.EventId = eventId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetEvent(ctx, request.(GetEventRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEvent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetEventResponseObject); ok {
		if err := validResponse.VisitGetEventResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListEvents operation middleware
func (sh *strictHandler) ListEvents(w http.ResponseWriter, r *http.Request, investigationId InvestigationId, params ListEventsParams) {
	var request ListEventsRequestObject

	request.InvestigationId = investigationId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListEvents(ctx, request.(ListEventsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListEvents")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListEventsResponseObject); ok {
		if err := validResponse.VisitListEventsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AttachEvents operation middleware
func (sh *strictHandler) AttachEvents(w http.ResponseWriter, r *http.Request, investigationId InvestigationId) {
	var request AttachEventsRequestObject

	request.InvestigationId = investigationId

	var body AttachEventsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AttachEvents(ctx, request.(AttachEventsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AttachEvents")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AttachEventsResponseObject); ok {
		if err := validResponse.VisitAttachEventsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
