get:
  summary: List registered sources
  operationId: listSources
  parameters:
    - $ref: '../shared/parameters.yaml#/ProjectId'
  responses:
    '200':
      description: Registered sources.
      content:
        application/json:
          schema:
            type: object
            required: [items]
            properties:
              items:
                type: array
                description: External security products registered for use through the Gateway.
                items:
                  $ref: '../shared/schemas.yaml#/Source'
    default:
      $ref: '../shared/responses.yaml#/ErrorResponse'
