/** Russian display titles for MaxPatrol SIEM event fields (taxonomy has no i18n; localization API is forbidden for Student). */
export const EVENT_FIELD_LABELS_RU: Record<string, string> = {
  time: 'Время',
  recv_time: 'Время получения',
  uuid: 'UUID',
  id: 'ID',
  text: 'Текст',
  importance: 'Важность',
  status: 'Статус',
  msgid: 'ID сообщения',
  protocol: 'Протокол',
  action: 'Действие',
  correlation_name: 'Имя корреляции',
  correlation_type: 'Тип корреляции',
  correlation_event_id: 'ID события корреляции',
  'incident.key': 'Ключ инцидента',
  'incident.type': 'Категория',
  'incident.external_key': 'Внешний ключ',
  'incident.verdict': 'Вердикт',
  'incident.damage': 'Ущерб',
  'incident.recommendation': 'Рекомендация',
  'incident.assigned_to': 'Назначен',

  'event_src.host': 'Хост источника события',
  'event_src.ip': 'IP-адрес источника события',
  'event_src.hostname': 'Имя хоста источника события',
  'event_src.fqdn': 'FQDN источника события',
  'event_src.title': 'Название источника события',
  'event_src.vendor': 'Вендор источника события',
  'event_src.subsys': 'Подсистема источника события',
  'event_src.asset': 'Актив источника события',

  'src.ip': 'IP-адрес источника',
  'src.host': 'Хост источника',
  'src.port': 'Порт источника',
  'src.mac': 'MAC источника',
  'src.hostname': 'Имя хоста источника',
  'src.fqdn': 'FQDN источника',
  'src.geo.country': 'Страна источника',

  'dst.ip': 'IP-адрес назначения',
  'dst.host': 'Хост назначения',
  'dst.port': 'Порт назначения',
  'dst.mac': 'MAC назначения',
  'dst.hostname': 'Имя хоста назначения',
  'dst.fqdn': 'FQDN назначения',

  'subject.account.name': 'Имя учётной записи субъекта',
  'subject.account.domain': 'Домен учётной записи субъекта',
  'subject.account.id': 'ID учётной записи субъекта',
  'subject.user.name': 'Имя пользователя субъекта',
  'subject.process.name': 'Имя процесса субъекта',
  'subject.process.id': 'ID процесса субъекта',
  'subject.process.fullpath': 'Полный путь процесса субъекта',
  'subject.process.cmdline': 'Командная строка процесса субъекта',
  'subject.process.hash.md5': 'MD5 процесса субъекта',
  'subject.process.hash.sha256': 'SHA256 процесса субъекта',
  'subject.process.chain': 'Цепочка процессов субъекта',

  'object.process.name': 'Имя процесса объекта',
  'object.process.id': 'ID процесса объекта',
  'object.process.fullpath': 'Полный путь процесса объекта',
  'object.process.cmdline': 'Командная строка процесса объекта',
  'object.process.chain': 'Цепочка процессов объекта',
  'object.process.parent.name': 'Имя родительского процесса объекта',
  'object.process.parent.id': 'ID родительского процесса объекта',
  'object.process.hash.md5': 'MD5 процесса объекта',
  'object.process.hash.sha256': 'SHA256 процесса объекта',

  'object.account.name': 'Имя учётной записи объекта',
  'object.account.domain': 'Домен учётной записи объекта',
  'object.file.name': 'Имя файла объекта',
  'object.file.path': 'Путь файла объекта',
  'object.file.hash.md5': 'MD5 файла объекта',
  'object.file.hash.sha256': 'SHA256 файла объекта',
  'object.registry.key': 'Ключ реестра объекта',
  'object.url': 'URL объекта',
  'object.value': 'Значение объекта',

  'category.generic': 'Категория (общая)',
  'category.high': 'Категория (высокая)',
  'category.low': 'Категория (низкая)',
}

export function eventFieldLabelRu(name: string): string {
  return EVENT_FIELD_LABELS_RU[name] ?? name
}
