/** Wazuh-native field catalog — mirrors Gateway wazuh/fields.go allowlist. */

export const WAZUH_EVENT_FIELDS = new Set<string>([
  'time',
  'uuid',
  'correlation_name',
  'correlation_type',
  'rule.id',
  'rule.level',
  'rule.groups',
  'rule.description',
  'rule.firedtimes',
  'rule.mitre.id',
  'rule.mitre.tactic',
  'rule.mitre.technique',
  'rule.frequency',
  'agent.id',
  'agent.name',
  'agent.ip',
  'manager.name',
  'decoder.name',
  'location',
  'data.srcip',
  'data.dstip',
  'data.srcport',
  'data.dstport',
  'data.srcuser',
  'data.dstuser',
  'data.protocol',
  'data.url',
  'data.id',
  'data.status',
  'data.system_name',
  'data.integration',
  'data.win.system.eventID',
  'data.win.system.computer',
  'data.win.system.channel',
  'data.win.eventdata.targetUserName',
  'data.win.eventdata.ipAddress',
  'data.win.eventdata.logonType',
  'syscheck.path',
  'syscheck.event',
  'syscheck.md5_after',
  'syscheck.sha1_after',
  'syscheck.sha256_after',
  'data.vulnerability.cve',
  'data.vulnerability.severity',
  'data.vulnerability.package.name',
  'data.vulnerability.package.version',
  'data.vulnerability.status',
  'data.vulnerability.cvss.cvss3.base_score',
  'data.virustotal.source.md5',
  'data.virustotal.source.sha1',
  'data.virustotal.source.file',
  'data.virustotal.positives',
  'data.aws.source',
  'data.aws.accountId',
  'data.aws.region',
  'data.aws.type',
  'data.aws.title',
  'data.office365.UserId',
  'data.office365.ClientIP',
  'data.office365.Operation',
  'data.office365.Workload',
  'data.github.actor',
  'data.github.org',
  'data.github.action',
  'data.github.repo',
  'data.gcp.jsonPayload.sourceIP',
  'data.gcp.jsonPayload.vmInstanceName',
  'data.gcp.resource.labels.project_id',
  'data.audit.command',
  'data.audit.exe',
  'data.audit.success',
  'data.audit.type',
  'data.docker.Action',
  'data.docker.Type',
  'data.osquery.name',
  'data.osquery.action',
  'data.osquery.pack',
  'GeoLocation.country_name',
  'GeoLocation.city_name',
  'data.ms-graph.ipAddress',
  'data.ms-graph.title',
  'data.ms-graph.severity',
  'data.ms-graph.category',
])

export const WAZUH_FIELD_LABELS_RU: Record<string, string> = {
  time: 'Время',
  uuid: 'ID документа',
  correlation_name: 'Имя корреляции',
  correlation_type: 'Тип корреляции',
  'rule.id': 'ID правила',
  'rule.level': 'Уровень правила',
  'rule.groups': 'Группы правила',
  'rule.description': 'Описание правила',
  'rule.firedtimes': 'Срабатываний',
  'rule.frequency': 'Частота правила',
  'rule.mitre.id': 'MITRE ID',
  'rule.mitre.tactic': 'MITRE тактика',
  'rule.mitre.technique': 'MITRE техника',
  'agent.id': 'ID агента',
  'agent.name': 'Имя агента',
  'agent.ip': 'IP агента',
  'manager.name': 'Менеджер',
  'decoder.name': 'Декодер',
  location: 'Источник лога',
  'data.srcip': 'IP источника',
  'data.dstip': 'IP назначения',
  'data.srcport': 'Порт источника',
  'data.dstport': 'Порт назначения',
  'data.srcuser': 'Пользователь источника',
  'data.dstuser': 'Пользователь назначения',
  'data.protocol': 'Протокол',
  'data.url': 'URL',
  'data.id': 'Код / ID',
  'data.status': 'Статус',
  'data.system_name': 'Имя системы',
  'data.integration': 'Интеграция',
  'data.win.system.eventID': 'Windows Event ID',
  'data.win.system.computer': 'Компьютер Windows',
  'data.win.system.channel': 'Канал Windows',
  'data.win.eventdata.targetUserName': 'Целевая учётная запись',
  'data.win.eventdata.ipAddress': 'IP Windows',
  'data.win.eventdata.logonType': 'Тип входа',
  'syscheck.path': 'Путь файла',
  'syscheck.event': 'Событие FIM',
  'syscheck.md5_after': 'MD5',
  'syscheck.sha1_after': 'SHA1',
  'syscheck.sha256_after': 'SHA256',
  'data.vulnerability.cve': 'CVE',
  'data.vulnerability.severity': 'Критичность уязвимости',
  'data.vulnerability.package.name': 'Пакет',
  'data.vulnerability.package.version': 'Версия пакета',
  'data.vulnerability.status': 'Статус уязвимости',
  'data.vulnerability.cvss.cvss3.base_score': 'CVSS3',
  'data.virustotal.source.md5': 'VT MD5',
  'data.virustotal.source.sha1': 'VT SHA1',
  'data.virustotal.source.file': 'VT файл',
  'data.virustotal.positives': 'VT positives',
  'data.aws.source': 'AWS source',
  'data.aws.accountId': 'AWS account',
  'data.aws.region': 'AWS region',
  'data.aws.type': 'AWS type',
  'data.aws.title': 'AWS title',
  'data.office365.UserId': 'O365 пользователь',
  'data.office365.ClientIP': 'O365 IP',
  'data.office365.Operation': 'O365 операция',
  'data.office365.Workload': 'O365 workload',
  'data.github.actor': 'GitHub actor',
  'data.github.org': 'GitHub org',
  'data.github.action': 'GitHub action',
  'data.github.repo': 'GitHub repo',
  'data.gcp.jsonPayload.sourceIP': 'GCP source IP',
  'data.gcp.jsonPayload.vmInstanceName': 'GCP VM',
  'data.gcp.resource.labels.project_id': 'GCP project',
  'data.audit.command': 'Команда',
  'data.audit.exe': 'Исполняемый файл',
  'data.audit.success': 'Успех audit',
  'data.audit.type': 'Тип audit',
  'data.docker.Action': 'Docker action',
  'data.docker.Type': 'Docker type',
  'data.osquery.name': 'Osquery name',
  'data.osquery.action': 'Osquery action',
  'data.osquery.pack': 'Osquery pack',
  'GeoLocation.country_name': 'Страна',
  'GeoLocation.city_name': 'Город',
  'data.ms-graph.ipAddress': 'MS Graph IP',
  'data.ms-graph.title': 'MS Graph title',
  'data.ms-graph.severity': 'MS Graph severity',
  'data.ms-graph.category': 'MS Graph category',
}

export const WAZUH_DEFAULT_FIELD_FREQ: Record<string, number> = {
  time: 100,
  'rule.level': 95,
  'rule.groups': 90,
  'rule.description': 85,
  'agent.name': 80,
  'data.srcip': 75,
  'agent.ip': 70,
  correlation_type: 65,
  'data.srcuser': 60,
  'rule.id': 55,
}

export const WAZUH_ENUM_VALUES: Record<string, string[]> = {
  correlation_type: ['wazuh_frequency', 'wazuh_rule'],
}

export function wazuhFieldLabelRu(name: string): string {
  return WAZUH_FIELD_LABELS_RU[name] ?? name
}
