/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/investigations/{investigation_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        /** Артефакты расследования */
        get: operations["listArtifacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artifacts/{artifact_id}/enrich": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: components["parameters"]["ArtifactId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Обогатить артефакт расширением
         * @description Репутация, декодирование, песочница. Расширение берётся из allowlist;
         *     каждый внешний вызов помечается в аудите как передача данных наружу.
         *     Недоступность расширения не ошибка запроса — вернётся вердикт status=error.
         */
        post: operations["enrichArtifact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/investigations/{investigation_id}/iocs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Массовый ввод индикаторов
         * @description Создаёт артефакты и сущности из списка индикаторов. С retro_search=true
         *     ищет их по источникам и затягивает найденное — оценка распространения
         *     по узлам инфраструктуры. Большая выборка уходит в фон (job_id).
         */
        post: operations["importIocs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Индикатор компрометации в скоупе расследования: хеш, адрес, домен, файл.
         *     Накапливает вердикты обогащений от внешних расширений.
         */
        Artifact: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            investigation_id: string;
            /** @description Тип из справочника EntityType */
            type_code: string;
            value: string;
            /**
             * Format: uuid
             * @description Связанная сущность графа
             */
            entity_id?: string | null;
            /** @description Файл в object storage */
            storage_ref?: string | null;
            media_type?: string | null;
            checksum?: string | null;
            is_bundle?: boolean;
            /** @description Ключ — код расширения */
            enrichment_verdicts?: {
                [key: string]: components["schemas"]["EnrichmentVerdict"];
            };
            metadata?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
        };
        ArtifactPage: {
            items: components["schemas"]["Artifact"][];
            next_cursor?: string | null;
        };
        EnrichRequest: {
            /** @description Код расширения из allowlist. Недоступность не валит запрос — вернётся status=error */
            extension_code: string;
        };
        EnrichmentVerdict: {
            extension_code: string;
            /** @enum {string} */
            status: "clean" | "suspicious" | "malicious" | "unknown" | "error";
            score?: number | null;
            detail?: {
                [key: string]: unknown;
            };
            /** @description Данные уходили наружу — отражено в аудите (п.6.4 ТЗ) */
            external_call?: boolean;
            cached?: boolean;
            /** Format: date-time */
            enriched_at: string;
        };
        /**
         * @description Массовый ввод индикаторов. Создаёт артефакты и сущности, запускает
         *     ретро-поиск по источникам — закрывает задачу оценки распространения.
         */
        IocImportRequest: {
            items: {
                type_code: string;
                value: string;
            }[];
            /**
             * @description Искать индикаторы по источникам и затягивать найденное в расследование
             * @default false
             */
            retro_search: boolean;
            /** Format: date-time */
            from?: string;
            /** Format: date-time */
            to?: string;
        };
        IocImportResult: {
            created: number;
            duplicates: number;
            /** @description Затянуто событий ретро-поиском */
            retro_events_attached?: number;
            /**
             * Format: uuid
             * @description Если ретро-поиск ушёл в фон
             */
            job_id?: string | null;
        };
        ErrorResponse: {
            error: {
                /**
                 * @description not_implemented — ручка объявлена в контракте, но ещё не реализована.
                 *     Клиент может отличить её от настоящей поломки сервера и скрыть
                 *     элемент интерфейса, а не показывать ошибку.
                 * @enum {string}
                 */
                code: "unauthorized" | "forbidden" | "not_found" | "conflict" | "validation" | "source_unavailable" | "som_unavailable" | "not_implemented" | "internal";
                message: string;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
    };
    responses: {
        /** @description Нет или невалиден токен (code=unauthorized) */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Роль не даёт действия или чужой тенант (code=forbidden) */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Не найдено в тенанте субъекта (code=not_found) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Невалидные данные (code=validation) */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Конфликт версии, дубликат или закрытое расследование (code=conflict) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Источник улик недоступен (code=source_unavailable) */
        SourceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        InvestigationId: string;
        Limit: number;
        /** @description Непрозрачный keyset-курсор из next_cursor предыдущей страницы */
        Cursor: string;
        ArtifactId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listArtifacts: {
        parameters: {
            query?: {
                type_code?: string;
                limit?: components["parameters"]["Limit"];
                /** @description Непрозрачный keyset-курсор из next_cursor предыдущей страницы */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Страница артефактов */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    enrichArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: components["parameters"]["ArtifactId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrichRequest"];
            };
        };
        responses: {
            /** @description Вердикт */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrichmentVerdict"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Расширение не в allowlist или роль не даёт действия (code=forbidden) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    importIocs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IocImportRequest"];
            };
        };
        responses: {
            /** @description Итог импорта */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IocImportResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            502: components["responses"]["SourceUnavailable"];
        };
    };
}
