/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/investigations/{investigation_id}/hypotheses": {
        parameters: {
            query?: never;
            header: {
                /** @description Sb0rka project selected for this request. It scopes IR data, the project's external-source configuration, and project Secrets. */
                "X-Project-ID": components["parameters"]["ProjectId"];
            };
            path: {
                /** @description Identifier of an investigation in the selected project. */
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        /**
         * List hypotheses of an investigation
         * @description Returns the hypotheses owned by this investigation, newest first. Hypotheses are graph projections, not child investigations, and do not participate in the investigation tree.
         */
        get: operations["listHypotheses"];
        put?: never;
        /**
         * Propose a hypothesis
         * @description Creates an analyst-origin hypothesis in proposed status. Its graph projection starts empty and is filled through the nested graph, context, and agent-result operations.
         */
        post: operations["createHypothesis"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/investigations/{investigation_id}/hypotheses/{hypothesis_id}": {
        parameters: {
            query?: never;
            header: {
                /** @description Sb0rka project selected for this request. It scopes IR data, the project's external-source configuration, and project Secrets. */
                "X-Project-ID": components["parameters"]["ProjectId"];
            };
            path: {
                /** @description Identifier of an investigation in the selected project. */
                investigation_id: components["parameters"]["InvestigationId"];
                /** @description Identifier of a hypothesis owned by the investigation in the path. */
                hypothesis_id: components["parameters"]["HypothesisId"];
            };
            cookie?: never;
        };
        /** One hypothesis */
        get: operations["getHypothesis"];
        put?: never;
        post?: never;
        /**
         * Delete a hypothesis
         * @description Deletes only the hypothesis and its node and edge memberships. The investigation's shared graph objects remain unchanged.
         */
        delete: operations["deleteHypothesis"];
        options?: never;
        head?: never;
        /**
         * Update a hypothesis
         * @description Applies supplied fields with optimistic locking. Allowed status transitions are proposed to active or resolved, active to resolved, and resolved back to active. Resolving requires a non-empty reason; reopening clears the reason and resolved timestamp. A stale version returns 409 with the conflicting hypothesis id.
         */
        patch: operations["updateHypothesis"];
        trace?: never;
    };
    "/investigations/{investigation_id}/hypotheses/{hypothesis_id}/nodes/{node_id}": {
        parameters: {
            query?: never;
            header: {
                /** @description Sb0rka project selected for this request. It scopes IR data, the project's external-source configuration, and project Secrets. */
                "X-Project-ID": components["parameters"]["ProjectId"];
            };
            path: {
                /** @description Identifier of an investigation in the selected project. */
                investigation_id: components["parameters"]["InvestigationId"];
                /** @description Identifier of a hypothesis owned by the investigation in the path. */
                hypothesis_id: components["parameters"]["HypothesisId"];
                /** @description Identifier of a graph node. Edges reference this, not the entity or event behind it. */
                node_id: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Add an existing graph node to a hypothesis
         * @description Idempotently adds a node from this investigation's shared graph to the hypothesis. Resolved hypotheses reject membership writes.
         */
        put: operations["addHypothesisNode"];
        post?: never;
        /**
         * Remove a node from a hypothesis
         * @description Removes only this membership and memberships of edges incident to the node in this hypothesis. The shared node and edges remain. Resolved hypotheses reject membership writes.
         */
        delete: operations["deleteHypothesisNode"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/investigations/{investigation_id}/hypotheses/{hypothesis_id}/edges/{edge_id}": {
        parameters: {
            query?: never;
            header: {
                /** @description Sb0rka project selected for this request. It scopes IR data, the project's external-source configuration, and project Secrets. */
                "X-Project-ID": components["parameters"]["ProjectId"];
            };
            path: {
                /** @description Identifier of an investigation in the selected project. */
                investigation_id: components["parameters"]["InvestigationId"];
                /** @description Identifier of a hypothesis owned by the investigation in the path. */
                hypothesis_id: components["parameters"]["HypothesisId"];
                /** @description Identifier of an edge — one claim that two nodes are related. */
                edge_id: components["parameters"]["GraphEdgeId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Add an existing graph edge to a hypothesis
         * @description Idempotently adds an edge from this investigation's shared graph and both endpoint-node memberships. Resolved hypotheses reject membership writes.
         */
        put: operations["addHypothesisEdge"];
        post?: never;
        /**
         * Remove an edge from a hypothesis
         * @description Removes only the edge membership. Endpoint-node memberships and the shared graph edge remain. Resolved hypotheses reject membership writes.
         */
        delete: operations["deleteHypothesisEdge"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description A named projection over the owning investigation's shared factual graph. It cannot have child hypotheses, but that does not restrict which events, entities, or edges belong to its graph. Memberships may overlap. */
        Hypothesis: {
            /** Format: uuid */
            id: string;
            /** @description Project that owns the investigation and hypothesis. */
            project_id: string;
            /**
             * Format: uuid
             * @description Investigation whose shared graph this hypothesis projects.
             */
            investigation_id: string;
            /** @description The version of events being tested. */
            statement: string;
            /** @description Optional working context and intended verification steps. */
            description: string | null;
            /** @description Current hypothesis workflow state. */
            status: components["schemas"]["HypothesisStatus"];
            /** @description Resolution rationale. Present only while status is resolved. */
            reason: string | null;
            /** @description Creator type. Manual creation always returns analyst. */
            origin: components["schemas"]["Origin"];
            /** @description Version of hypothesis fields for optimistic locking. Membership changes do not increment it. */
            version: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /**
             * Format: date-time
             * @description Resolution time. Present only while status is resolved.
             */
            resolved_at: string | null;
        };
        HypothesisCreate: {
            /** @description The version of events being proposed. Blank after trimming is invalid. */
            statement: string;
            /** @description Optional working context. */
            description?: string;
        };
        /** @description Fields to change. Omitted fields stay unchanged. An explicitly empty description clears it; resolving requires a non-empty reason. */
        HypothesisPatch: {
            /** @description Version the client last read. A mismatch is a 409. */
            version: number;
            /** @description Revised version of events. Blank after trimming is invalid. */
            statement?: string;
            /** @description Revised working context. Send an empty string to clear it. */
            description?: string;
            /** @description New workflow state. Transitions back to proposed are forbidden. */
            status?: components["schemas"]["HypothesisStatus"];
            /** @description Resolution rationale, or a correction while already resolved. */
            reason?: string;
        };
        /** @enum {string} */
        HypothesisStatus: "proposed" | "active" | "resolved";
        HypothesisPage: {
            /** @description Hypotheses ordered by created_at and id, newest first. */
            hypotheses: components["schemas"]["Hypothesis"][];
            /** @description Pass as cursor to continue the same filtered list. */
            next_cursor?: string | null;
        };
        /**
         * @description Who produced the record: a human acting through the API, a deterministic linking rule, or an agent run. Anything not produced by a human is born unconfirmed and has to be reviewed.
         * @enum {string}
         */
        Origin: "analyst" | "rule" | "agent";
        /** @description Body of every non-2xx response. Clients branch on `code`, not on the HTTP status: the status says what happened at the protocol level, the code says what happened in the domain. */
        ErrorResponse: {
            /** @description The failure itself. Never carries internal details of a 500. */
            error: {
                /**
                 * @description Machine-readable reason, stable across releases. `validation` covers both a malformed body (400) and a well-formed but invalid one (422). `not_implemented` means the operation exists in the contract but has no implementation yet — a client can hide the control instead of showing an error.
                 * @enum {string}
                 */
                code: "unauthorized" | "forbidden" | "not_found" | "conflict" | "validation" | "source_unavailable" | "not_implemented" | "internal";
                /** @description Human-readable explanation, safe to show. For an internal error it is deliberately generic — the real cause goes to the log. */
                message: string;
                /** @description Extra context tied to the code. Version conflicts list the clashing ids in `conflicts`; validation failures name the field. */
                details?: {
                    [key: string]: unknown;
                };
            };
        };
    };
    responses: {
        /** @description Token is missing, malformed, expired or signed by an unknown key (code=unauthorized). */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Caller is authenticated but cannot access the selected project's platform-owned resource (code=forbidden). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description No such record in the selected project. Returned instead of 403 for records that exist elsewhere, so the response does not reveal them (code=not_found). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Request parsed but violates a rule of the domain — an impossible status transition, a confirmation without evidence, a malformed cursor (code=validation). */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Unhandled failure or a panic. The service answers with the same error envelope as everything else, so a client has one shape to parse; the message is deliberately generic and the real cause goes to the log (code=internal). */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The record changed since the version the client sent, the write would duplicate an existing one, or the investigation is already closed. `details.conflicts` lists the ids that clashed (code=conflict). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Sb0rka project selected for this request. It scopes IR data, the project's external-source configuration, and project Secrets. */
        ProjectId: string;
        /** @description Identifier of an investigation in the selected project. */
        InvestigationId: string;
        /** @description How many items to return. The server may return fewer, never more. */
        Limit: number;
        /** @description Opaque keyset cursor taken from `next_cursor` of the previous page. Encodes a position, not a query — do not build one by hand. Omit it to start from the beginning. */
        Cursor: string;
        /** @description Identifier of a hypothesis owned by the investigation in the path. */
        HypothesisId: string;
        /** @description Identifier of a graph node. Edges reference this, not the entity or event behind it. */
        NodeId: string;
        /** @description Identifier of an edge — one claim that two nodes are related. */
        GraphEdgeId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listHypotheses: {
        parameters: {
            query?: {
                /** @description Keep only hypotheses in this status. */
                status?: components["schemas"]["HypothesisStatus"];
                /** @description How many items to return. The server may return fewer, never more. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque keyset cursor taken from `next_cursor` of the previous page. Encodes a position, not a query — do not build one by hand. Omit it to start from the beginning. */
                cursor?: components["parameters"]["Cursor"];
            };
            header: {
                /** @description Sb0rka project selected for this request. It scopes IR data, the project's external-source configuration, and project Secrets. */
                "X-Project-ID": components["parameters"]["ProjectId"];
            };
            path: {
                /** @description Identifier of an investigation in the selected project. */
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of hypotheses */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HypothesisPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
        };
    };
    createHypothesis: {
        parameters: {
            query?: never;
            header: {
                /** @description Sb0rka project selected for this request. It scopes IR data, the project's external-source configuration, and project Secrets. */
                "X-Project-ID": components["parameters"]["ProjectId"];
            };
            path: {
                /** @description Identifier of an investigation in the selected project. */
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HypothesisCreate"];
            };
        };
        responses: {
            /** @description The proposed hypothesis */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Hypothesis"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
        };
    };
    getHypothesis: {
        parameters: {
            query?: never;
            header: {
                /** @description Sb0rka project selected for this request. It scopes IR data, the project's external-source configuration, and project Secrets. */
                "X-Project-ID": components["parameters"]["ProjectId"];
            };
            path: {
                /** @description Identifier of an investigation in the selected project. */
                investigation_id: components["parameters"]["InvestigationId"];
                /** @description Identifier of a hypothesis owned by the investigation in the path. */
                hypothesis_id: components["parameters"]["HypothesisId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The hypothesis */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Hypothesis"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteHypothesis: {
        parameters: {
            query?: never;
            header: {
                /** @description Sb0rka project selected for this request. It scopes IR data, the project's external-source configuration, and project Secrets. */
                "X-Project-ID": components["parameters"]["ProjectId"];
            };
            path: {
                /** @description Identifier of an investigation in the selected project. */
                investigation_id: components["parameters"]["InvestigationId"];
                /** @description Identifier of a hypothesis owned by the investigation in the path. */
                hypothesis_id: components["parameters"]["HypothesisId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updateHypothesis: {
        parameters: {
            query?: never;
            header: {
                /** @description Sb0rka project selected for this request. It scopes IR data, the project's external-source configuration, and project Secrets. */
                "X-Project-ID": components["parameters"]["ProjectId"];
            };
            path: {
                /** @description Identifier of an investigation in the selected project. */
                investigation_id: components["parameters"]["InvestigationId"];
                /** @description Identifier of a hypothesis owned by the investigation in the path. */
                hypothesis_id: components["parameters"]["HypothesisId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HypothesisPatch"];
            };
        };
        responses: {
            /** @description The updated hypothesis */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Hypothesis"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
        };
    };
    addHypothesisNode: {
        parameters: {
            query?: never;
            header: {
                /** @description Sb0rka project selected for this request. It scopes IR data, the project's external-source configuration, and project Secrets. */
                "X-Project-ID": components["parameters"]["ProjectId"];
            };
            path: {
                /** @description Identifier of an investigation in the selected project. */
                investigation_id: components["parameters"]["InvestigationId"];
                /** @description Identifier of a hypothesis owned by the investigation in the path. */
                hypothesis_id: components["parameters"]["HypothesisId"];
                /** @description Identifier of a graph node. Edges reference this, not the entity or event behind it. */
                node_id: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The membership exists */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteHypothesisNode: {
        parameters: {
            query?: never;
            header: {
                /** @description Sb0rka project selected for this request. It scopes IR data, the project's external-source configuration, and project Secrets. */
                "X-Project-ID": components["parameters"]["ProjectId"];
            };
            path: {
                /** @description Identifier of an investigation in the selected project. */
                investigation_id: components["parameters"]["InvestigationId"];
                /** @description Identifier of a hypothesis owned by the investigation in the path. */
                hypothesis_id: components["parameters"]["HypothesisId"];
                /** @description Identifier of a graph node. Edges reference this, not the entity or event behind it. */
                node_id: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Membership removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    addHypothesisEdge: {
        parameters: {
            query?: never;
            header: {
                /** @description Sb0rka project selected for this request. It scopes IR data, the project's external-source configuration, and project Secrets. */
                "X-Project-ID": components["parameters"]["ProjectId"];
            };
            path: {
                /** @description Identifier of an investigation in the selected project. */
                investigation_id: components["parameters"]["InvestigationId"];
                /** @description Identifier of a hypothesis owned by the investigation in the path. */
                hypothesis_id: components["parameters"]["HypothesisId"];
                /** @description Identifier of an edge — one claim that two nodes are related. */
                edge_id: components["parameters"]["GraphEdgeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The edge and endpoint memberships exist */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteHypothesisEdge: {
        parameters: {
            query?: never;
            header: {
                /** @description Sb0rka project selected for this request. It scopes IR data, the project's external-source configuration, and project Secrets. */
                "X-Project-ID": components["parameters"]["ProjectId"];
            };
            path: {
                /** @description Identifier of an investigation in the selected project. */
                investigation_id: components["parameters"]["InvestigationId"];
                /** @description Identifier of a hypothesis owned by the investigation in the path. */
                hypothesis_id: components["parameters"]["HypothesisId"];
                /** @description Identifier of an edge — one claim that two nodes are related. */
                edge_id: components["parameters"]["GraphEdgeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Membership removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
}
