/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/investigations": {
        parameters: {
            query?: never;
            header: {
                /** @description Sb0rka project selected for this request. The caller must have an IR role binding in this project; roles from other projects are ignored. */
                "X-Project-ID": components["parameters"]["ProjectId"];
            };
            path?: never;
            cookie?: never;
        };
        /**
         * List investigations
         * @description Root cases by default, or the direct children of one. Only one level at a time — fetch the tree endpoint when the whole subtree is needed.
         */
        get: operations["listInvestigations"];
        put?: never;
        /**
         * Open an investigation or a hypothesis under one
         * @description A root investigation is a case; a child is a hypothesis.
         */
        post: operations["createInvestigation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/investigations/{investigation_id}": {
        parameters: {
            query?: never;
            header: {
                /** @description Sb0rka project selected for this request. The caller must have an IR role binding in this project; roles from other projects are ignored. */
                "X-Project-ID": components["parameters"]["ProjectId"];
            };
            path: {
                /** @description Identifier of an investigation in the selected project. */
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        /**
         * One investigation
         * @description The investigation with its counters — how much evidence it holds and how much still waits for review.
         */
        get: operations["getInvestigation"];
        put?: never;
        post?: never;
        /**
         * Delete an investigation
         * @description Deletes the investigation subtree, its graph data and its links to shared events and entities. Project event and entity records remain.
         */
        delete: operations["deleteInvestigation"];
        options?: never;
        head?: never;
        /**
         * Update an investigation
         * @description Updates only the supplied fields. Closing requires a verdict; rejecting requires a reason. Confirming a hypothesis without an attached event returns 422 with `details.reason=evidence_required`. A closed investigation can only be reopened; reopening clears the verdict.
         */
        patch: operations["updateInvestigation"];
        trace?: never;
    };
    "/investigations/{investigation_id}/tree": {
        parameters: {
            query?: never;
            header: {
                /** @description Sb0rka project selected for this request. The caller must have an IR role binding in this project; roles from other projects are ignored. */
                "X-Project-ID": components["parameters"]["ProjectId"];
            };
            path: {
                /** @description Identifier of an investigation in the selected project. */
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        /**
         * The whole subtree
         * @description This investigation and everything under it, flattened in pre-order with a depth on each item. The client rebuilds the tree in one pass — no recursive fetching.
         */
        get: operations["getInvestigationTree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description A case or a nested hypothesis in the selected project. */
        Investigation: {
            /**
             * Format: uuid
             * @description Identifier of the investigation.
             */
            id: string;
            /** @description Project that owns the case. Every child inherits it unchanged, so a whole tree belongs to one project. */
            project_id: string;
            /**
             * Format: uuid
             * @description The investigation this one refines. Null means it is a root case; anything else means it is a hypothesis inside a larger case.
             */
            parent_id?: string | null;
            /** @description What is being investigated. For a hypothesis this is the claim being tested, phrased so a verdict makes sense against it. */
            title: string;
            /** @description Free-form context — what is known, what is being checked and why. */
            description?: string | null;
            /** @description Whether work is still going on. Independent of the verdict: a case can be open with no verdict yet, and closing requires one. */
            status: components["schemas"]["InvestigationStatus"];
            /** @description How bad this looks. Set during triage and revised as evidence arrives. Absent until someone judges it. */
            severity?: components["schemas"]["Severity"];
            /** @description The conclusion. Absent while the investigation is still open, required to close it. Which values are allowed depends on whether this is a root case or a hypothesis — see Verdict. */
            verdict?: components["schemas"]["Verdict"];
            /** @description Reason for the verdict. Required when rejecting. */
            verdict_reason?: string | null;
            /** @description How sure the conclusion is. Meaningful for a hypothesis, rarely used on a root case. */
            confidence?: number | null;
            /** @description Creator type, assigned by the server. */
            origin?: components["schemas"]["Origin"];
            /** @description Which one exactly — the analyst's subject id, the rule's code, or the agent run's identifier. */
            origin_ref?: string | null;
            /** @description Bumped on every change. Send the value you last read when updating; a mismatch means someone else edited it first. */
            version: number;
            /** @description SOM workspaces linked to this investigation. */
            som_workspace_ids: string[];
            /** @description Size of the case at a glance, so the list does not need a query per row. */
            counters: {
                /** @description Direct child investigations — the open hypotheses under this one. */
                children: number;
                /** @description Events pulled into this investigation. */
                events: number;
                /** @description Distinct entities extracted from those events. */
                entities: number;
                /** @description Edges waiting for review. */
                proposed_edges: number;
            };
            /**
             * Format: date-time
             * @description When the investigation was opened.
             */
            created_at: string;
            /**
             * Format: date-time
             * @description When it last changed.
             */
            updated_at: string;
            /**
             * Format: date-time
             * @description When it was closed. Cleared if the investigation is reopened.
             */
            closed_at?: string | null;
        };
        /** @description A new case, or a new hypothesis inside an existing one. */
        InvestigationCreate: {
            /** @description What is being investigated, or the claim being tested. */
            title: string;
            /** @description Context — what is known so far and what needs checking. */
            description?: string;
            /**
             * Format: uuid
             * @description The investigation this one refines. Omit it to open a root case.
             */
            parent_id?: string;
            /** @description Initial assessment. Can be revised later. */
            severity?: components["schemas"]["Severity"];
            /** @description SOM workspaces to link to the new investigation. */
            som_workspace_ids?: string[];
        };
        /** @description Fields to change. Anything omitted stays as it is; `version` is always required so concurrent edits cannot overwrite each other silently. */
        InvestigationPatch: {
            /** @description Version the client last read. A mismatch is a 409. */
            version: number;
            /** @description New title. */
            title?: string;
            /** @description New description. */
            description?: string;
            /** @description Close the investigation, or reopen a closed one. Closing needs a verdict; reopening clears it. */
            status?: components["schemas"]["InvestigationStatus"];
            /** @description The conclusion. Which values are allowed depends on whether this is a root case or a hypothesis. */
            verdict?: components["schemas"]["Verdict"];
            /** @description Why. Required when the verdict is rejected. */
            verdict_reason?: string;
            /** @description How sure the conclusion is. Meaningful for a hypothesis. */
            confidence?: number;
            /** @description Revised assessment of how bad this is. */
            severity?: components["schemas"]["Severity"];
            /** @description Complete replacement for the investigation's SOM workspace links. */
            som_workspace_ids?: string[];
        };
        /**
         * @description Whether work is still going on. Says nothing about the outcome — that is the verdict.
         * @enum {string}
         */
        InvestigationStatus: "open" | "closed";
        /**
         * @description The conclusion, drawn from two vocabularies that share one field. A root case ends as incident, false_positive, not_affected or inconclusive. A hypothesis ends as confirmed, rejected or inconclusive. The server checks the value against the investigation's position in the tree, so a hypothesis cannot be closed as an incident.
         * @enum {string}
         */
        Verdict: "incident" | "false_positive" | "not_affected" | "inconclusive" | "confirmed" | "rejected";
        /** @description One page of investigations. */
        InvestigationPage: {
            /** @description The investigations on this page. */
            items: components["schemas"]["Investigation"][];
            /** @description Pass as `cursor` to get the next page. Absent on the last page. */
            next_cursor?: string | null;
        };
        /** @description A subtree flattened for one-pass rendering. */
        InvestigationTree: {
            /**
             * Format: uuid
             * @description The investigation the subtree was requested for.
             */
            root_id: string;
            /** @description Every investigation in the subtree in pre-order, starting with the root itself. Each carries its depth, so the client can indent without walking parent links. */
            items: (components["schemas"]["Investigation"] & {
                /** @description Distance from the root. Zero for the root itself. */
                depth: number;
            })[];
        };
        /**
         * @description How much damage the case could cause. Set on triage and adjusted as evidence accumulates.
         * @enum {string}
         */
        Severity: "low" | "medium" | "high" | "critical";
        /**
         * @description Who produced the record: a human acting through the API, a deterministic linking rule, or an agent run. Anything not produced by a human is born unconfirmed and has to be reviewed.
         * @enum {string}
         */
        Origin: "analyst" | "rule" | "agent";
        /** @description Body of every non-2xx response. Clients branch on `code`, not on the HTTP status: the status says what happened at the protocol level, the code says what happened in the domain. */
        ErrorResponse: {
            /** @description The failure itself. Never carries internal details of a 500. */
            error: {
                /**
                 * @description Machine-readable reason, stable across releases. `validation` covers both a malformed body (400) and a well-formed but invalid one (422). `not_implemented` means the operation exists in the contract but has no implementation yet — a client can hide the control instead of showing an error.
                 * @enum {string}
                 */
                code: "unauthorized" | "forbidden" | "not_found" | "conflict" | "validation" | "source_unavailable" | "not_implemented" | "internal";
                /** @description Human-readable explanation, safe to show. For an internal error it is deliberately generic — the real cause goes to the log. */
                message: string;
                /** @description Extra context tied to the code. Version conflicts list the clashing ids in `conflicts`; validation failures name the field. */
                details?: {
                    [key: string]: unknown;
                };
            };
        };
    };
    responses: {
        /** @description Token is missing, malformed, expired or signed by an unknown key (code=unauthorized). */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Caller is authenticated but holds no role in the selected project, or the role does not grant this action (code=forbidden). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Request parsed but violates a rule of the domain — an impossible status transition, a confirmation without evidence, a malformed cursor (code=validation). */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Unhandled failure or a panic. The service answers with the same error envelope as everything else, so a client has one shape to parse; the message is deliberately generic and the real cause goes to the log (code=internal). */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The operation exists in the contract but has no implementation yet (code=not_implemented). Declared on every operation because the service is being built contract-first: a client can hide the control instead of showing an error, and knows this is not a failure. Goes away per operation as each one is written. */
        NotImplemented: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description No such record in the selected project. Returned instead of 403 for records that exist elsewhere, so the response does not reveal them (code=not_found). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The record changed since the version the client sent, the write would duplicate an existing one, or the investigation is already closed. `details.conflicts` lists the ids that clashed (code=conflict). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Sb0rka project selected for this request. The caller must have an IR role binding in this project; roles from other projects are ignored. */
        ProjectId: string;
        /** @description How many items to return. The server may return fewer, never more. */
        Limit: number;
        /** @description Opaque keyset cursor taken from `next_cursor` of the previous page. Encodes a position, not a query — do not build one by hand. Omit it to start from the beginning. */
        Cursor: string;
        /** @description Identifier of an investigation in the selected project. */
        InvestigationId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listInvestigations: {
        parameters: {
            query?: {
                /** @description Return the direct children of this investigation instead of the roots. Omit it for the case list. */
                parent_id?: string;
                /** @description Keep only open or only closed investigations. */
                status?: components["schemas"]["InvestigationStatus"];
                /** @description Keep only investigations of this severity. */
                severity?: components["schemas"]["Severity"];
                /** @description Substring match on the title. */
                q?: string;
                /** @description How many items to return. The server may return fewer, never more. */
                limit?: components["parameters"]["Limit"];
                /** @description Opaque keyset cursor taken from `next_cursor` of the previous page. Encodes a position, not a query — do not build one by hand. Omit it to start from the beginning. */
                cursor?: components["parameters"]["Cursor"];
            };
            header: {
                /** @description Sb0rka project selected for this request. The caller must have an IR role binding in this project; roles from other projects are ignored. */
                "X-Project-ID": components["parameters"]["ProjectId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of investigations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
            501: components["responses"]["NotImplemented"];
        };
    };
    createInvestigation: {
        parameters: {
            query?: never;
            header: {
                /** @description Sb0rka project selected for this request. The caller must have an IR role binding in this project; roles from other projects are ignored. */
                "X-Project-ID": components["parameters"]["ProjectId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestigationCreate"];
            };
        };
        responses: {
            /** @description The new investigation */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Investigation"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description The parent named in parent_id does not exist in this project. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
            501: components["responses"]["NotImplemented"];
        };
    };
    getInvestigation: {
        parameters: {
            query?: never;
            header: {
                /** @description Sb0rka project selected for this request. The caller must have an IR role binding in this project; roles from other projects are ignored. */
                "X-Project-ID": components["parameters"]["ProjectId"];
            };
            path: {
                /** @description Identifier of an investigation in the selected project. */
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The investigation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Investigation"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
            501: components["responses"]["NotImplemented"];
        };
    };
    deleteInvestigation: {
        parameters: {
            query?: never;
            header: {
                /** @description Sb0rka project selected for this request. The caller must have an IR role binding in this project; roles from other projects are ignored. */
                "X-Project-ID": components["parameters"]["ProjectId"];
            };
            path: {
                /** @description Identifier of an investigation in the selected project. */
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
            501: components["responses"]["NotImplemented"];
        };
    };
    updateInvestigation: {
        parameters: {
            query?: never;
            header: {
                /** @description Sb0rka project selected for this request. The caller must have an IR role binding in this project; roles from other projects are ignored. */
                "X-Project-ID": components["parameters"]["ProjectId"];
            };
            path: {
                /** @description Identifier of an investigation in the selected project. */
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestigationPatch"];
            };
        };
        responses: {
            /** @description The updated investigation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Investigation"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
            501: components["responses"]["NotImplemented"];
        };
    };
    getInvestigationTree: {
        parameters: {
            query?: never;
            header: {
                /** @description Sb0rka project selected for this request. The caller must have an IR role binding in this project; roles from other projects are ignored. */
                "X-Project-ID": components["parameters"]["ProjectId"];
            };
            path: {
                /** @description Identifier of an investigation in the selected project. */
                investigation_id: components["parameters"]["InvestigationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The subtree */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationTree"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
            501: components["responses"]["NotImplemented"];
        };
    };
}
