//go:build go1.22

// Package findings provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package findings

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ContextStatus.
const (
	Complete ContextStatus = "complete"
	Partial  ContextStatus = "partial"
)

// Valid indicates whether the value is a known member of the ContextStatus enum.
func (e ContextStatus) Valid() bool {
	switch e {
	case Complete:
		return true
	case Partial:
		return true
	default:
		return false
	}
}

// Defines values for ErrorResponseErrorCode.
const (
	ErrorResponseErrorCodeConflict          ErrorResponseErrorCode = "conflict"
	ErrorResponseErrorCodeForbidden         ErrorResponseErrorCode = "forbidden"
	ErrorResponseErrorCodeInternal          ErrorResponseErrorCode = "internal"
	ErrorResponseErrorCodeNotFound          ErrorResponseErrorCode = "not_found"
	ErrorResponseErrorCodeNotImplemented    ErrorResponseErrorCode = "not_implemented"
	ErrorResponseErrorCodeSourceUnavailable ErrorResponseErrorCode = "source_unavailable"
	ErrorResponseErrorCodeUnauthorized      ErrorResponseErrorCode = "unauthorized"
	ErrorResponseErrorCodeValidation        ErrorResponseErrorCode = "validation"
)

// Valid indicates whether the value is a known member of the ErrorResponseErrorCode enum.
func (e ErrorResponseErrorCode) Valid() bool {
	switch e {
	case ErrorResponseErrorCodeConflict:
		return true
	case ErrorResponseErrorCodeForbidden:
		return true
	case ErrorResponseErrorCodeInternal:
		return true
	case ErrorResponseErrorCodeNotFound:
		return true
	case ErrorResponseErrorCodeNotImplemented:
		return true
	case ErrorResponseErrorCodeSourceUnavailable:
		return true
	case ErrorResponseErrorCodeUnauthorized:
		return true
	case ErrorResponseErrorCodeValidation:
		return true
	default:
		return false
	}
}

// Defines values for FindingKind.
const (
	FindingKindNadAttack       FindingKind = "nad_attack"
	FindingKindSiemCorrelation FindingKind = "siem_correlation"
	FindingKindSiemIncident    FindingKind = "siem_incident"
)

// Valid indicates whether the value is a known member of the FindingKind enum.
func (e FindingKind) Valid() bool {
	switch e {
	case FindingKindNadAttack:
		return true
	case FindingKindSiemCorrelation:
		return true
	case FindingKindSiemIncident:
		return true
	default:
		return false
	}
}

// Defines values for ObjectSeverity.
const (
	Critical ObjectSeverity = "critical"
	High     ObjectSeverity = "high"
	Info     ObjectSeverity = "info"
	Low      ObjectSeverity = "low"
	Medium   ObjectSeverity = "medium"
	Unknown  ObjectSeverity = "unknown"
)

// Valid indicates whether the value is a known member of the ObjectSeverity enum.
func (e ObjectSeverity) Valid() bool {
	switch e {
	case Critical:
		return true
	case High:
		return true
	case Info:
		return true
	case Low:
		return true
	case Medium:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for SourceObjectRefRecordType.
const (
	SourceObjectRefRecordTypeNadAttack       SourceObjectRefRecordType = "nad_attack"
	SourceObjectRefRecordTypeNadSession      SourceObjectRefRecordType = "nad_session"
	SourceObjectRefRecordTypeSiemCorrelation SourceObjectRefRecordType = "siem_correlation"
	SourceObjectRefRecordTypeSiemIncident    SourceObjectRefRecordType = "siem_incident"
)

// Valid indicates whether the value is a known member of the SourceObjectRefRecordType enum.
func (e SourceObjectRefRecordType) Valid() bool {
	switch e {
	case SourceObjectRefRecordTypeNadAttack:
		return true
	case SourceObjectRefRecordTypeNadSession:
		return true
	case SourceObjectRefRecordTypeSiemCorrelation:
		return true
	case SourceObjectRefRecordTypeSiemIncident:
		return true
	default:
		return false
	}
}

// ContextError defines model for ContextError.
type ContextError struct {
	Code string `json:"code"`

	// Message Safe summary without credentials, queries, or vendor payloads.
	Message   string `json:"message"`
	Retryable bool   `json:"retryable"`
	Source    string `json:"source"`
}

// ContextStatus defines model for ContextStatus.
type ContextStatus string

// ErrorResponse Body of every non-2xx response. Clients branch on `code`, not on the HTTP status: the status says what happened at the protocol level, the code says what happened in the domain.
type ErrorResponse struct {
	// Error The failure itself. Never carries internal details of a 500.
	Error struct {
		// Code Machine-readable reason, stable across releases. `validation` covers both a malformed body (400) and a well-formed but invalid one (422). `not_implemented` means the operation exists in the contract but has no implementation yet — a client can hide the control instead of showing an error.
		Code ErrorResponseErrorCode `json:"code"`

		// Details Extra context tied to the code. Version conflicts list the clashing ids in `conflicts`; validation failures name the field.
		Details *map[string]interface{} `json:"details,omitempty"`

		// Message Human-readable explanation, safe to show. For an internal error it is deliberately generic — the real cause goes to the log.
		Message string `json:"message"`
	} `json:"error"`
}

// ErrorResponseErrorCode Machine-readable reason, stable across releases. `validation` covers both a malformed body (400) and a well-formed but invalid one (422). `not_implemented` means the operation exists in the contract but has no implementation yet — a client can hide the control instead of showing an error.
type ErrorResponseErrorCode string

// Finding defines model for Finding.
type Finding struct {
	AttachedAt    *time.Time     `json:"attached_at,omitempty"`
	ContextErrors []ContextError `json:"context_errors"`
	ContextStatus ContextStatus  `json:"context_status"`
	CreatedAt     time.Time      `json:"created_at"`

	// Derived The finding was discovered while resolving another selected object.
	Derived     *bool   `json:"derived,omitempty"`
	Description *string `json:"description,omitempty"`

	// DirectlyAdded Present and meaningful when listed through an investigation.
	DirectlyAdded      *bool                  `json:"directly_added,omitempty"`
	FetchedAt          time.Time              `json:"fetched_at"`
	Id                 openapi_types.UUID     `json:"id"`
	InvestigationIds   *[]openapi_types.UUID  `json:"investigation_ids,omitempty"`
	Kind               FindingKind            `json:"kind"`
	NormalizedSnapshot map[string]interface{} `json:"normalized_snapshot"`
	OccurredAt         time.Time              `json:"occurred_at"`
	Provenance         map[string]interface{} `json:"provenance"`

	// Ref Stable source identity and the bounded replay window; time is not identity.
	Ref       SourceObjectRef `json:"ref"`
	Severity  ObjectSeverity  `json:"severity"`
	SourceRef *string         `json:"source_ref,omitempty"`
	Status    *string         `json:"status,omitempty"`
	Title     string          `json:"title"`
	UpdatedAt time.Time       `json:"updated_at"`
}

// FindingKind defines model for FindingKind.
type FindingKind string

// FindingPage defines model for FindingPage.
type FindingPage struct {
	Findings   []Finding `json:"findings"`
	NextCursor *string   `json:"next_cursor,omitempty"`
}

// ObjectSeverity defines model for ObjectSeverity.
type ObjectSeverity string

// SourceObjectRef Stable source identity and the bounded replay window; time is not identity.
type SourceObjectRef struct {
	ExternalId     string                    `json:"external_id"`
	RecordType     SourceObjectRefRecordType `json:"record_type"`
	SourceCode     string                    `json:"source_code"`
	SourceInstance *string                   `json:"source_instance,omitempty"`
	TimeRange      TimeRange                 `json:"time_range"`
}

// SourceObjectRefRecordType defines model for SourceObjectRef.RecordType.
type SourceObjectRefRecordType string

// TimeRange defines model for TimeRange.
type TimeRange struct {
	From time.Time `json:"from"`
	To   time.Time `json:"to"`
}

// Cursor defines model for Cursor.
type Cursor = string

// InvestigationId defines model for InvestigationId.
type InvestigationId = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int

// ProjectId defines model for ProjectId.
type ProjectId = string

// Forbidden Body of every non-2xx response. Clients branch on `code`, not on the HTTP status: the status says what happened at the protocol level, the code says what happened in the domain.
type Forbidden = ErrorResponse

// InternalError Body of every non-2xx response. Clients branch on `code`, not on the HTTP status: the status says what happened at the protocol level, the code says what happened in the domain.
type InternalError = ErrorResponse

// NotFound Body of every non-2xx response. Clients branch on `code`, not on the HTTP status: the status says what happened at the protocol level, the code says what happened in the domain.
type NotFound = ErrorResponse

// Unauthorized Body of every non-2xx response. Clients branch on `code`, not on the HTTP status: the status says what happened at the protocol level, the code says what happened in the domain.
type Unauthorized = ErrorResponse

// ValidationError Body of every non-2xx response. Clients branch on `code`, not on the HTTP status: the status says what happened at the protocol level, the code says what happened in the domain.
type ValidationError = ErrorResponse

// GetFindingParams defines parameters for GetFinding.
type GetFindingParams struct {
	// XProjectID Sb0rka project selected for this request. It scopes IR data, the project's external-source configuration, and project Secrets.
	XProjectID ProjectId `json:"X-Project-ID"`
}

// ListFindingsParams defines parameters for ListFindings.
type ListFindingsParams struct {
	RecordType    *FindingKind    `form:"record_type,omitempty" json:"record_type,omitempty"`
	Severity      *ObjectSeverity `form:"severity,omitempty" json:"severity,omitempty"`
	ContextStatus *ContextStatus  `form:"context_status,omitempty" json:"context_status,omitempty"`

	// Limit How many items to return. The server may return fewer, never more.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque keyset cursor taken from `next_cursor` of the previous page. Encodes a position, not a query — do not build one by hand. Omit it to start from the beginning.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// XProjectID Sb0rka project selected for this request. It scopes IR data, the project's external-source configuration, and project Secrets.
	XProjectID ProjectId `json:"X-Project-ID"`
}

// DetachFindingParams defines parameters for DetachFinding.
type DetachFindingParams struct {
	// XProjectID Sb0rka project selected for this request. It scopes IR data, the project's external-source configuration, and project Secrets.
	XProjectID ProjectId `json:"X-Project-ID"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetFinding Get one project finding
	// (GET /findings/{finding_id})
	GetFinding(w http.ResponseWriter, r *http.Request, findingId openapi_types.UUID, params GetFindingParams)
	// ListFindings List findings attached to an investigation
	// (GET /investigations/{investigation_id}/findings)
	ListFindings(w http.ResponseWriter, r *http.Request, investigationId InvestigationId, params ListFindingsParams)
	// DetachFinding Detach a finding and its exclusively derived context
	// (DELETE /investigations/{investigation_id}/findings/{finding_id})
	DetachFinding(w http.ResponseWriter, r *http.Request, investigationId InvestigationId, findingId openapi_types.UUID, params DetachFindingParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetFinding operation middleware
func (siw *ServerInterfaceWrapper) GetFinding(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "finding_id" -------------
	var findingId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "finding_id", r.PathValue("finding_id"), &findingId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "finding_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetFindingParams

	headers := r.Header

	// ------------- Required header parameter "X-Project-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Project-ID")]; found {
		var XProjectID ProjectId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Project-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Project-ID", valueList[0], &XProjectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Project-ID", Err: err})
			return
		}

		params.XProjectID = XProjectID

	} else {
		err := fmt.Errorf("Header parameter X-Project-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Project-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFinding(w, r, findingId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListFindings operation middleware
func (siw *ServerInterfaceWrapper) ListFindings(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "investigation_id" -------------
	var investigationId InvestigationId

	err = runtime.BindStyledParameterWithOptions("simple", "investigation_id", r.PathValue("investigation_id"), &investigationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "investigation_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListFindingsParams

	// ------------- Optional query parameter "record_type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "record_type", r.URL.Query(), &params.RecordType, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "record_type"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "record_type", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "severity" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "severity", r.URL.Query(), &params.Severity, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "severity"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "severity", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "context_status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "context_status", r.URL.Query(), &params.ContextStatus, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "context_status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "context_status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Required header parameter "X-Project-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Project-ID")]; found {
		var XProjectID ProjectId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Project-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Project-ID", valueList[0], &XProjectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Project-ID", Err: err})
			return
		}

		params.XProjectID = XProjectID

	} else {
		err := fmt.Errorf("Header parameter X-Project-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Project-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListFindings(w, r, investigationId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DetachFinding operation middleware
func (siw *ServerInterfaceWrapper) DetachFinding(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "investigation_id" -------------
	var investigationId InvestigationId

	err = runtime.BindStyledParameterWithOptions("simple", "investigation_id", r.PathValue("investigation_id"), &investigationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "investigation_id", Err: err})
		return
	}

	// ------------- Path parameter "finding_id" -------------
	var findingId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "finding_id", r.PathValue("finding_id"), &findingId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "finding_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DetachFindingParams

	headers := r.Header

	// ------------- Required header parameter "X-Project-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Project-ID")]; found {
		var XProjectID ProjectId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Project-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Project-ID", valueList[0], &XProjectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Project-ID", Err: err})
			return
		}

		params.XProjectID = XProjectID

	} else {
		err := fmt.Errorf("Header parameter X-Project-ID is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Project-ID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DetachFinding(w, r, investigationId, findingId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/investigations/{investigation_id}/findings", wrapper.ListFindings)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/findings/{finding_id}", wrapper.GetFinding)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/investigations/{investigation_id}/findings/{finding_id}", wrapper.DetachFinding)

	return m
}

type ForbiddenJSONResponse ErrorResponse

type InternalErrorJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type UnauthorizedJSONResponse ErrorResponse

type ValidationErrorJSONResponse ErrorResponse

type GetFindingRequestObject struct {
	FindingId openapi_types.UUID `json:"finding_id"`
	Params    GetFindingParams
}

type GetFindingResponseObject interface {
	VisitGetFindingResponse(w http.ResponseWriter) error
}

type GetFinding200JSONResponse Finding

func (response GetFinding200JSONResponse) VisitGetFindingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetFinding401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetFinding401JSONResponse) VisitGetFindingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetFinding403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetFinding403JSONResponse) VisitGetFindingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetFinding404JSONResponse struct{ NotFoundJSONResponse }

func (response GetFinding404JSONResponse) VisitGetFindingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetFinding500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetFinding500JSONResponse) VisitGetFindingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListFindingsRequestObject struct {
	InvestigationId InvestigationId `json:"investigation_id"`
	Params          ListFindingsParams
}

type ListFindingsResponseObject interface {
	VisitListFindingsResponse(w http.ResponseWriter) error
}

type ListFindings200JSONResponse FindingPage

func (response ListFindings200JSONResponse) VisitListFindingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListFindings401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListFindings401JSONResponse) VisitListFindingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListFindings403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListFindings403JSONResponse) VisitListFindingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListFindings404JSONResponse struct{ NotFoundJSONResponse }

func (response ListFindings404JSONResponse) VisitListFindingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListFindings422JSONResponse struct{ ValidationErrorJSONResponse }

func (response ListFindings422JSONResponse) VisitListFindingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type ListFindings500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListFindings500JSONResponse) VisitListFindingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DetachFindingRequestObject struct {
	InvestigationId InvestigationId    `json:"investigation_id"`
	FindingId       openapi_types.UUID `json:"finding_id"`
	Params          DetachFindingParams
}

type DetachFindingResponseObject interface {
	VisitDetachFindingResponse(w http.ResponseWriter) error
}

type DetachFinding204Response struct {
}

func (response DetachFinding204Response) VisitDetachFindingResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DetachFinding401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DetachFinding401JSONResponse) VisitDetachFindingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DetachFinding403JSONResponse struct{ ForbiddenJSONResponse }

func (response DetachFinding403JSONResponse) VisitDetachFindingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DetachFinding404JSONResponse struct{ NotFoundJSONResponse }

func (response DetachFinding404JSONResponse) VisitDetachFindingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DetachFinding500JSONResponse struct{ InternalErrorJSONResponse }

func (response DetachFinding500JSONResponse) VisitDetachFindingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetFinding Get one project finding
	// (GET /findings/{finding_id})
	GetFinding(ctx context.Context, request GetFindingRequestObject) (GetFindingResponseObject, error)
	// ListFindings List findings attached to an investigation
	// (GET /investigations/{investigation_id}/findings)
	ListFindings(ctx context.Context, request ListFindingsRequestObject) (ListFindingsResponseObject, error)
	// DetachFinding Detach a finding and its exclusively derived context
	// (DELETE /investigations/{investigation_id}/findings/{finding_id})
	DetachFinding(ctx context.Context, request DetachFindingRequestObject) (DetachFindingResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetFinding operation middleware
func (sh *strictHandler) GetFinding(w http.ResponseWriter, r *http.Request, findingId openapi_types.UUID, params GetFindingParams) {
	var request GetFindingRequestObject

	request.FindingId = findingId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetFinding(ctx, request.(GetFindingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetFinding")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetFindingResponseObject); ok {
		if err := validResponse.VisitGetFindingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListFindings operation middleware
func (sh *strictHandler) ListFindings(w http.ResponseWriter, r *http.Request, investigationId InvestigationId, params ListFindingsParams) {
	var request ListFindingsRequestObject

	request.InvestigationId = investigationId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListFindings(ctx, request.(ListFindingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListFindings")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListFindingsResponseObject); ok {
		if err := validResponse.VisitListFindingsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DetachFinding operation middleware
func (sh *strictHandler) DetachFinding(w http.ResponseWriter, r *http.Request, investigationId InvestigationId, findingId openapi_types.UUID, params DetachFindingParams) {
	var request DetachFindingRequestObject

	request.InvestigationId = investigationId
	request.FindingId = findingId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DetachFinding(ctx, request.(DetachFindingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DetachFinding")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DetachFindingResponseObject); ok {
		if err := validResponse.VisitDetachFindingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
